### PR TITLE
Add Open Source Initiative License Info

### PR DESCRIPTION
**Pull request by JustinBeauchesne**
For this PR ive added a new sub folder "licenses" with a license.md to open source -> open-source-software. In this subfolder ive documented some general info about why these licenses are important and a list of popular licenses from the 'open source initiative' site. This location was selected since the previous topic mentioned specific license but does not address the concept itself

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by mohitO12-dev — APPROVED** [review]
approved

**Comment by ishg-153** [comment]
@JustinBeauchesne While I work on reviewing this, please sign the CLA.

Also for future contributions, you must ask to be assigned to one of the [available issues](https://github.com/Codecademy/docs/issues?q=is%3Aopen+is%3Aissue+-label%3A%22claimed%22) and once assigned you can create a PR for that issue.

**Comment by ishg-153** [comment]
@JustinBeauchesne We can't move forward with this unless you sign the CLA.

**Comment by ishg-153** [comment]
@JustinBeauchesne Due to lack of response from your end this PR is being Closed.

**Pull request closed without merging**
