### PR TITLE
[Term Entry] Python NumPy - Math functions .floor() #5239

### PR DESCRIPTION
**Pull request by LucaArisci**
### Description

I've added a new entry for the .floor() mathematical function for NumPy package as requested, explaining how can be used and for what purpose. The newly created file with the corresponding new entry can be found at this [path](content/numpy/concepts/math-methods/terms/floor/floor.md)

### Issue Solved

Closes #5239

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by mamtawardhani — APPROVED** [review]
Thank you for contributing to Codecademy Docs @LucaArisci , the entry is well written 😄 

It looks good for a second round of review! 🚀

**Comment by mamtawardhani** [comment]
> [CLA assistant check](https://cla-assistant.io/Codecademy/docs?pullRequest=5464) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5464) before we can accept your contribution.**1** out of **2** committers have signed the CLA.✅ mamtawardhani❌ Luca Arisci
> 
> **Luca Arisci** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5464) it.

@LucaArisci please sign the CLA

**Comment by LucaArisci** [comment]
@mamtawardhani I have already signed the CLA a few days ago and if I try to sign it again it tells me that I have already agreed, is there anything else I can do to try solve the problem? Thanks in advance

**Comment by LucaArisci** [comment]
@mamtawardhani I've found out what the problem is. I forgot that my local git configuration was using a work related e-mail instead of my personal one that I use on GitHub too. The one that I used is not paired with the GitHub account and I prefer not to use it, is there any possibility to find an alternative solution?

**Comment by mamtawardhani** [comment]
> [CLA assistant check](https://cla-assistant.io/Codecademy/docs?pullRequest=5464) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5464) before we can accept your contribution.**1** out of **2** committers have signed the CLA.✅ mamtawardhani❌ Luca Arisci
> 
> **Luca Arisci** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5464) it.

If you look here, the profile is different. Looks like the commit was made through your local device, is there any other email that you use @LucaArisci ?

**Comment by mamtawardhani** [comment]
> @mamtawardhani I've found out what the problem is. I forgot that my local git configuration was using a work related e-mail instead of my personal one that I use on GitHub too. The one that I used is not paired with the GitHub account and I prefer not to use it, is there any possibility to find an alternative solution?

Hey @dakshdeepHERE @Sriparno08 quick help needed here, is there any solution for this? I suppose no

**Comment by mamtawardhani** [comment]
> Maybe the best solution is to create another PR based on a new branch using the correct email, what do you think about it?

That's correct. @LucaArisci 
You can change the email address in its local git configuration to the preferred one, make the changes, and open a new PR.

Closing this PR for now. Let me know whenever you raise another PR 😄

**Pull request closed without merging**
