### PR TITLE
[Term Entry] JavaScript Strings .at()

### LINKED ISSUE #4725: [Term Entry] JavaScript Strings .at()
### Reason/inspiration (optional)

We would like a new term entry on the `.at()` method for Strings in JavaScript. The entry should go in a new file under `docs/content/javascript/concepts/strings/terms/at/at.md`

The entry should include the following:

- A description of the function
- A Syntax section that includes the syntax of the function and its details
- An Example section that includes a ```js ``` codeblock and ```shell ``` that shows the example output.
- A Codebyte Example to show the working of the method

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by andersooi**
### Description

- Added new term entry for Javascript `.at()` method

### Issue Solved

Closes #4725  

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by Sriparno08 — CHANGES_REQUESTED** [review]
Hey @andersooi, thanks for contributing to Codecademy!

I've listed all the modifications that you need to make in your entry below:

**Comment by andersooi** [comment]
Hi @Sriparno08, I have made the necessary changes. Do let me know if there are any other areas that require attention.

**Review by Sriparno08 — APPROVED** [review]
Good job, @andersooi!

This looks good for a second review 👍

**Review by mamtawardhani — APPROVED** [review]
Thank you for the submission @andersooi! The entry is nicely written! 😃 

It is ready to be merged! 🚀

**Pull request merged**
