### PR TITLE
Python - Add codebytes for math.ceil, pytorch and tqdm

### PR DESCRIPTION
**Pull request by karthikmurali60**
### Description

- Added Codebytes examples for three Python file methods: math.ceil, PyTorch and tqdm.
- Closes Issue https://github.com/Codecademy/docs/issues/2888

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by caupolicandiaz — APPROVED** [review]
@karthikmurali60 I've gone ahead and pushed a few additional edits to the PR (I removed the PyTorch example because it's not a module that's currently accessible through code bytes). This is ready for a second review.

**Comment by karthikmurali60** [comment]
> @karthikmurali60 I've gone ahead and pushed a few additional edits to the PR (I removed the PyTorch example because it's not a module that's currently accessible through code bytes). This is ready for a second review.

Thank you for the review and edits @caupolicandiaz !!

**Comment by karthikmurali60** [comment]
@caupolicandiaz the latest force push seems to have messed up the commits made by me. Should I recommit the changes I had made ?

**Comment by caupolicandiaz** [comment]
> @caupolicandiaz the latest force push seems to have messed up the commits made by me. Should I recommit the changes I had made ?

What specifically? Are there changes missing?

**Comment by karthikmurali60** [comment]
@caupolicandiaz the changes required were for math.ceil, pytorch and tqdm

**Comment by SSwiniarski** [comment]
@karthikmurali60 It looks like you overwrote this branch with the other PR. Because of the conflicts, it may be best to close this, create a new branch off of main, and resubmit your original edits. cc: @caupolicandiaz

**Comment by karthikmurali60** [comment]
@SSwiniarski got it, will close this PR and create a new one

**Pull request closed without merging**
