### PR TITLE
Add common plotting commands on matplotlib

### PR DESCRIPTION
**Pull request by ahmejia93**
### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by Dusch4593** [comment]
We have a [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md) to help with making this kind of content. 😄

**Comment by ahmejia93** [comment]
> Hi @ahmejia93! Thank you so much for your interest in contributing to Codecademy Docs! 🚀
> 
> I'd be happy to conduct the first review for this PR but I wanted to propose the following challenge to you: Would be be willing to make separate term entry files for this plotting commands?
> 
> Since these are technically functions that exist within the `pyplot` module, I think this would be a great opportunity to make new term files like the following:
> 
> * `matplotlib/concepts/pyplot/terms/bar/bar.md`
> * `matplotlib/concepts/pyplot/terms/boxplot/boxplot.md`
> * `matplotlib/concepts/pyplot/terms/hist/hist.md`
> * `matplotlib/concepts/pyplot/terms/pie/pie.md`
> * `matplotlib/concepts/pyplot/terms/scatter/scatter.md`

**Comment by ahmejia93** [comment]
Hi @Dusch4593  It could be great, I'm kind of new to GitHub, so I'll appreciate it if you can guide through the path I need to follow to to that. https://github.com/Codecademy/docs/pull/1304#issuecomment-1341154025

**Comment by Dusch4593** [comment]
@ahmejia93 Sure! So while you're checked out inside of this PR branch, `entry-branch`, create the following inside of the `matplotlib/concepts/pyplot/terms/` directory:

- A folder called `bar`, then create a file called `bar.md` inside of this folder.
- A folder called `boxplot`, then create a file called `boxplot.md` inside of this folder.
- A folder called `hist`, then create a file called `hist.md` inside of this folder.
- A folder called `pie`, then create a file called `pie.md` inside of this folder.
- A folder called `scatter`, then create a file called `scatter.md` inside of this folder.

In each markdown `.md` file, we should have the following (starting from top to bottom):

1. Some metadata written in YAML (usually the first 15 lines). This allows the file to be published on our website. You can learn about how to create and style this section [here](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md#metadata).
2. The opening sentence is 1-2 lines is mostly always emphasize a given concept/term in **bold** (just the first instance, though). In the `bar.md` file, for example, the first use of `bar()` would be styled like this: "The \*\*\`.bar()\`\*\* method ..."
3. A "## Syntax" section with a \```pseudo code snippet followed by text that describes the syntax and any required/optional parameters and edge cases.
4. An "## Example" section with 1-2 sentences of text that previews/describes a \```py code snippet featuring a given concept/term.
5. (this entirely depends on a given concept/term) Any media such as images or GIFs that support the points made in a given concept/term entry.

**Comment by Dusch4593** [comment]
Hey @ahmejia93! 👋🏻 Did you have any questions or need any help with implementing the [setup instructions](https://github.com/Codecademy/docs/pull/1304#issuecomment-1341319331) I shared?

**Comment by Dusch4593** [comment]
@ahmejia93 it's been a while since there was activity here. Were you still working on this PR? Please let us know (or feel free to commit and push new changes) within 7 days.

**Comment by yangc95** [comment]
@ahmejia93 Just wanted to check in with how this is going.

It looks like this PR is turning out to be quite lengthy. We can either close out this PR, or you can feel free to choose **one** of the five terms to add:

- matplotlib/concepts/pyplot/terms/bar/bar.md
- matplotlib/concepts/pyplot/terms/boxplot/boxplot.md
- matplotlib/concepts/pyplot/terms/hist/hist.md
- matplotlib/concepts/pyplot/terms/pie/pie.md
- matplotlib/concepts/pyplot/terms/scatter/scatter.md

The other terms that will be made into [issues](https://github.com/Codecademy/docs/issues). If for some reason this PR becomes stale due to inconsistent response times, I can go ahead and close this PR.

**Comment by yangc95** [comment]
@ahmejia93 Issues #1658, #1659, #1660, #1661 & #1662 have been created 🙂 feel free to claim one of those issues is you'd still like to work on your contribution. Thanks for the thought!

**Pull request closed without merging**
