### PR TITLE
[Concept Entry] Rust Data Types #3373

### PR DESCRIPTION
**Pull request by moha230**
### Description

- added concept entry rust data-types
- added a folder data-types 
- added a file data-types.md
- Closes issue  #3373 

### Type of Change

- Adding concept entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [  ] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR

### CODE REVIEW

**Comment by moha230** [comment]
Hi @ishg-153 @dakshdeepHERE  this is the new PR . I have used cherry-pick. Thank you

**Comment by dakshdeepHERE** [comment]
Its all wrong @moha230. In this PR once go and check the files changes section. The best solution for you right now will be to just save the entry and the other content you want to be seen in the PR somewhere else. Delete the current branch go to the main branch update it. Once all this is done create a new branch and add the files you shifted before and commit the changes, very simple.

**Comment by dakshdeepHERE** [comment]
@moha230, please try it and do not close this PR until you have successfully created a new one with the correct files. Simply follow my steps, and the issue will be resolved. Additionally, here's a tip for you: I can see numerous commits in this PR that are from older PRs. Do you know why this happens? It occurs because your current branch is a sub-branch of older branches, not its own distinct branch. This happens when you forget to checkout 'main' before creating a new branch or start committing things directly to the 'main' branch. This is a common mistake that people make when starting with Git.

**Comment by moha230** [comment]
Hi @dakshdeepHERE i use the simple fix sorry for  the late reply I got sick badly. But I am back 💪.

**Comment by moha230** [comment]
closing PR

**Pull request closed without merging**
