### PR TITLE
C loop entry

### PR DESCRIPTION
**Pull request by braanj**
### Description
I made a new directory in the docs/content/c/concepts/loops section and added a markdown file named "loops.md".

Inside the file, I explained the concept of loops in C. Explain the different types of loops with pseudo code and examples.

Closes https://github.com/Codecademy/docs/issues/1832 - [Concept Entry] C Loops

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by Saitheja20 — COMMENTED** [review]
@braanj it's perfect solution thanks for helping me to know this loops and make examples more advance

**Comment by braanj** [comment]
@Saitheja20 Can you elaborate? Should I add only one loop example?

**Comment by braanj** [comment]
Hey Adam (@aherman91), thanks for the clarification. All good then! And yes I based the entry on an existing one.

**Review by SSwiniarski — APPROVED** [review]
@braanj I did a review and it all looks good to me. I'm passing it on to a second review.

**Review by caupolicandiaz — CHANGES_REQUESTED** [review]
@braanj I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

**Comment by braanj** [comment]
@caupolicandiaz I've updated the entry by committing the suggested changes. Thanks

**Review by caupolicandiaz — APPROVED** [review]
@braanj Looks good.

**Comment by braanj** [comment]
@SSwiniarski Thank you so much for your kind message and for taking the time to congratulate me on my new entry to the Codecademy docs! I really appreciate it.

I'm excited to continue contributing to the docs and to learn more about programming along the way. It's great to know that my contributions are appreciated and I'm looking forward to making more in the future.

Thanks again for your support and encouragement. It means a lot!

**Pull request merged**
