### PR TITLE
[Edit] SwiftUI ViewModifier metadata

### PR DESCRIPTION
**Pull request by yangc95**
### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by caupolicandiaz — COMMENTED** [review]
@yangc95 Looks like the main viewmodifier.md file is missing

**Comment by yangc95** [comment]
@caupolicandiaz I didn't make any changes to the file but it should be there 😮

**Comment by caupolicandiaz** [comment]
@yangc95 I meant that the main file also includes that tag, which needs to be updated.

**Comment by yangc95** [comment]
@caupolicandiaz thanks for finding that and clarifying!

**Review by caupolicandiaz — APPROVED** [review]
@yangc95 LGTM

**Review by KTom101 — APPROVED** [review]
👍

**Pull request merged**
