### PR TITLE
Added Data Types Comparison Table

### PR DESCRIPTION
**Pull request by the1coder-pro**
Add a table to compare between data types in other languages with dart.

### Description

I edited the data-types.md in Dart. to add a table to compare the difference between dart data-types and other languages data types. I felt it was need to share how dart is straightforward and easy to learn. And how it is very similar to other languages. Which in return makes it easy for others to learn it.

### Type of Change

- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by Sriparno08 — COMMENTED** [review]
Hey @the1coder-pro, thanks for contributing to Codecademy!

I've listed the only change that you need to make in your PR below:

**Comment by the1coder-pro** [comment]
@Sriparno08 Thank you for your suggestion 👍👍

**Review by Sriparno08 — APPROVED** [review]
Looks good for a second review 👍

**Review by letsbuildanything — APPROVED** [review]
Ready to merge! 🚀

**Pull request merged**
