### PR TITLE
[Term Entry] Go Math Functions Pow()

### PR DESCRIPTION
**Pull request by 4hbab**
### Description

- Added the Math.Pow() term for go
- Closes Issue #2507 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by caupolicandiaz — CHANGES_REQUESTED** [review]
@4hbab I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

**Comment by 4hbab** [comment]
I've made some changes and tried to make the points concise.

**Review by caupolicandiaz — APPROVED** [review]
@4hbab This is much improved. Looks good for a second review.

**Review by SSwiniarski — APPROVED** [review]
@4hbab I did one minor edit and now it looks good to merge.

**Pull request merged**
