### PR TITLE
[Term Entry] General / Semantic Technologies / OWL

### PR DESCRIPTION
**Pull request by noahpgordon**
### Description

Added **owl.md** within semantic-technologies.

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by Sriparno08** [comment]
Hey @noahpgordon, is the PR linked to an issue?

**Comment by noahpgordon** [comment]
> Hey @noahpgordon, is the PR linked to an issue?

@Sriparno08 No, there is no issue associated with this PR.

**Review by Sriparno08 — COMMENTED** [review]
Hey @noahpgordon, thanks for contributing to Codecademy!

I've listed all the modifications that you need to make in your article below:

**Comment by noahpgordon** [comment]
@Sriparno08 Incorporated the above edits.

**Comment by Sriparno08** [comment]
Good job, @noahpgordon 👍

This looks good for a second review.

**Review by SSwiniarski — APPROVED** [review]
@noahpgordon Looks good.

**Pull request merged**
