### PR TITLE
Added MySQL data-types markdown

### PR DESCRIPTION
**Pull request by emunoz8**
### Description

Created concepts/data-types/data-types.md under mysql directory. Followed concept entry template, content standards and markdown style guides (also utilized sql and java data-types.md as reference)
### Issue Solved

Issue 4675: create a Markdown document for MySQL datatypes.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by cigar-galaxy82** [comment]
Hi @emunoz8 I have reviewed the PR but you also changed the `yarn.lock` file so can you please revert the changes in this file

**Review by cigar-galaxy82 — CHANGES_REQUESTED** [review]
Hi, I have completed my review please make the changes

**Comment by rashi95** [comment]
@emunoz8  Please respond with the progress (or the changes) within 2 days else we might have to close it.

**Comment by cigar-galaxy82** [comment]
Closing this PR due to lack of activity.

**Pull request closed without merging**
