### PR TITLE
[Edit] Go struct file

### PR DESCRIPTION
**Pull request by Nessvah**
### Description

I made some small changes in the Go Struct file that I was working on. @CBID2 made some grammar suggestions that made sense to me. Let me know what you think. Thanks!

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by CBID2** [comment]
@Nessvah, don't forget to link the issue that this PR responds to.

**Comment by Nessvah** [comment]
> @Nessvah, don't forget to link the issue that this PR responds to.

Ohh, should I link the issue if it's already closed as well?

**Comment by CBID2** [comment]
> > @Nessvah, don't forget to link the issue that this PR responds to.
> 
> 
> 
> Ohh, should I link the issue if it's already closed as well?
Do you mean your other PR? No @Nessvah

**Comment by Nessvah** [comment]
@SSwiniarski  @cryoung1998 Hi guys! I made this new PR in a different way. Let me know if it's correct and if I have to link the issue from the previous one that it's already closed.

**Comment by SSwiniarski** [comment]
@Nessvah no issue linking, this is an edit to an existing entry. The issue requesting the entry be made in the first place has already been resolved.

**Review by SSwiniarski — APPROVED** [review]
@Nessvah Looks good to me. We just need a second review.

**Comment by Nessvah** [comment]
@caupolicandiaz @KTom101 @yangc95 Hi guys! Let me know if there's something that I can improve here or if its good to go!

**Review by caupolicandiaz — APPROVED** [review]
@Nessvah @SSwiniarski LGTM

**Comment by CBID2** [comment]
@Nessvah, don't forget to update your branch.

**Comment by SSwiniarski** [comment]
@Nessvah congrats on the new edit. Live link here: https://www.codecademy.com/resources/docs/go/structs

**Pull request merged**
