### PR TITLE
Distinguishing-element()-peek()-methods

### PR DESCRIPTION
**Pull request by elmanorc**
Updated element() and peek() descriptions at the Java/Concepts/Queue entry in order to clear distinguish them.

### Description

Just updating the description of the methods element() and peek() from the Queue entry. The previous version made no distinction between these two methods, but the former may throws an exception and the later may return a null value instead.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — APPROVED** [review]
@elmanorc, Looks good for second review as is.

**Review by Dusch4593 — CHANGES_REQUESTED** [review]
@elmanorc Your edits are good, but I had a few comments/suggestions that I wanted to list out here:

- On line # 16, let's **bold** the first instance of \`Queue\`.
- On line # 22, let's change \```java to \```pseudo.
- On line # 28, let's link "data type" to here: https://www.codecademy.com/resources/docs/java/data-types
- For lines # 50 through # 60, let's indent by **one (1) space**.

**Comment by elmanorc** [comment]
> @elmanorc Your edits are good, but I had a few comments/suggestions that I wanted to list out here:
> 
> * On line # 16, let's **bold** the first instance of `Queue`.
> * On line # 22, let's change ```java to ```pseudo.
> * On line # 28, let's link "data type" to here: https://www.codecademy.com/resources/docs/java/data-types
> * For lines # 50 through # 60, let's indent by **one (1) space**.

@Dusch4593 thanks for this feedback. I've committed the changes you pointed out.

**Comment by Dusch4593** [comment]
Hey @elmanorc! Did the changed get pushed to a different branch? The last commit pushed to this PR was Nov. 3rd.

**Comment by elmanorc** [comment]
> Hey @elmanorc! Did the changed get pushed to a different branch? The last commit pushed to this PR was Nov. 3rd.

I hope I did it right this time (I'm still newbie when it comes to git/github!). I think the last commit has all the requested changes.

**Comment by Dusch4593** [comment]
Thank you and congrats on your first contribution to Codecademy Docs, @elmanorc! 🎊 🙌🏻 🥳

The entry should now be live: https://www.codecademy.com/resources/docs/java/queue

Screen Shot 2022-11-21 at 12 28 40 PM

Looking forward to your next Docs contribution! 😄

**Comment by elmanorc** [comment]
Thanks!

**Pull request merged**
