### PR TITLE
Create structs.md

### PR DESCRIPTION
**Pull request by bharathgaddam1712**
added concepts/structs/structs.md files in rust

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by bharathgaddam1712** [comment]
Solved issue : #3375

**Comment by SSwiniarski** [comment]
This is a duplicate of [3455](https://github.com/Codecademy/docs/pull/3455) so I'm closing it.

**Comment by bharathgaddam1712** [comment]
can i again create a new branch and work on it!!

**Comment by SSwiniarski** [comment]
@bharathgaddam1712 Work on the existing branch connected to the existing PR.

**Pull request closed without merging**
