### PR TITLE
Created term entry for Python symmetric difference.

### PR DESCRIPTION
**Pull request by manig-writer**
### Description

Created term entry for the Python .symmetric_difference(). This was for the purpose of completing the "Contributing to Codecademy Docs" exercise in the Git & GitHub skill path.

### Issue Solved

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by Sriparno08** [comment]
Hey @manig-writer, please sign the CLA by clicking on the 'Contributor License Agreement' link in the message from @CLAassistant above.

**Review by Sriparno08 — CHANGES_REQUESTED** [review]
Hey @manig-writer, thanks for contributing to Codecademy!

I've listed all the modifications that you need to make in your entry below:

**Comment by Sriparno08** [comment]
Hey @manig-writer, please make the suggested changes so that we can move on with the review.

Please note that if there's no response from your side after one week, this PR will be closed.

**Review by Sriparno08 — APPROVED** [review]
Looks good for a second review, @manig-writer! 👍

**Review by mamtawardhani — APPROVED** [review]
The entry looks good @manig-writer! Thank you for contributing to Codecademy Docs 😃 

Good to be merged 🚀

**Pull request merged**
