### PR TITLE
[Edit] HTML add media: FIle paths

### LINKED ISSUE #3181: [Edit] HTML Add Media: File Paths
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to make an edit for HTML File Paths. The entry should go in the existing file in docs/content/html/concepts/file-paths/file-paths.md

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Bear in mind:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media should accurately represent the existing content and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by nicky-diaz**
### Description

changed the image extensions to .png as per a reviewers comment
changed the image description to be more descriptive about the actual image at hand

Closes #3181

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by dakshdeepHERE — CHANGES_REQUESTED** [review]
Everything looks good for now but before the review start please fix the path for the images that you have in the current PR. The images should go into the media folder in the docs folder.

**Comment by dakshdeepHERE** [comment]
Also, this is how your images link should look like `https://raw.githubusercontent.com/Codecademy/docs/main/media/css-position-example2.png`.

**Comment by nicky-diaz** [comment]
@dakshdeepHERE I did as you said and put the media inside media folder. and used the same https you gave me. and it is not showing up is that normal?

**Comment by dakshdeepHERE** [comment]
@nicky-diaz once it is hosted on the web it will show don't worry. Just keep the link as the example I gave you above. Keep the images type as png.

**Comment by nicky-diaz** [comment]
@dakshdeepHERE finished up the changed the images to follow your https.....

**Comment by ishg-153** [comment]
@dakshdeepHERE @nicky-diaz, how far are we with this PR? Please let me know if I can help merge this PR.

**Comment by shukriarahimitech** [comment]
@nicky-diaz I am interested in this issue.

**Review by Sriparno08 — APPROVED** [review]
Looks good! 👍

**Pull request merged**
