### PR TITLE
Updating Python hash description

### LINKED ISSUE #5390: [Edit] Python Hash
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Hash` concept entry under Python. The entry lives in `content/python/concepts/built-in-functions/terms/hash/hash.md`.

The edit needs to have:

- The example description is too long so shorten it.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) The example description is too big, needs to be shortened.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by Manish-Giri**
### Description

This PR updates the description of the Python built-in `hash()` function to be more precise.

### Issue Solved

Closes #5390 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by mamtawardhani — APPROVED** [review]
Thank you for contributing to Codecademy Docs @Manish-Giri, the entry is nicely written! 

It looks good for a second round of review 🚀

**Comment by Manish-Giri** [comment]
@mamtawardhani Thank you for the quick review!

If you could also review my other PR whenever you have some time - https://github.com/Codecademy/docs/pull/5418, would be much appreciated!

**Comment by mamtawardhani** [comment]
> @mamtawardhani Thank you for the quick review!
> 
> If you could also review my other PR whenever you have some time - #5418, would be much appreciated!

Hey @Manish-Giri As I see another reviewer is assigned to it, but I will try to escalate the review. Thanks for letting me know 😃

**Review by SaviDahegaonkar — APPROVED** [review]
Hey @Manish-Giri ,
LGMT! Thank you for contributing to Codecademy Docs. :)


Thanks,
Savi

**Pull request merged**
