### PR TITLE
[Term Entry] Adding SQL's IIF function

### LINKED ISSUE #4961: [New Entry] Subject: SQL IIF function
### Reason/inspiration (optional)

We want a new term entry on the IIF function in SQL. The entry should go into a new folder under docs/content/sql/concepts/operators/terms/iif/iif.md

The entry should include the following:

- A description of the term
- ‘Syntax’ section that includes how to use it
- Example section to show how to use it

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Topic Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by bpicoCode**
### Description
Adding term entry for iif.md

### Issue Solved
Closes #4961 

### Type of Change
- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by SaviDahegaonkar — CHANGES_REQUESTED** [review]
Hey @bpicoCode,
I had a look at your file and it is almost correct. I have requested that you make just a few minor changes. Please try to make the changes accordingly and let me know.

Thanks
Savi

**Comment by SaviDahegaonkar** [comment]
Hello @bpicoCode,
Have you applied the changes that I commented? If yes then let me know so I can review and approve this changes.


Thanks,
Savi

**Comment by mamtawardhani** [comment]
> Hello @bpicoCode, Have you applied the changes that I commented? If yes then let me know so I can review and approve this changes.
> 
> Thanks, Savi

@SaviDahegaonkar kindly apply the changes and send it for second review on priority, it has already been more than two months to this

**Review by SaviDahegaonkar — APPROVED** [review]

**Review by SaviDahegaonkar — APPROVED** [review]
Hey @bpicoCode ,
LGTM! Thank you for Contributing to Codecademy docs. :)

Thanks,
Savi

**Comment by mamtawardhani** [comment]
@SaviDahegaonkar why was this merged? @Sriparno08 is yet to the review?

**Comment by SaviDahegaonkar** [comment]
I can;t see that sriparno was assigned for this PR, I can't find his name
here, maybe it's a network issue, because I can't fond him as assignee on
my github. Is there any way to undo this ?

**Pull request merged**
