### PR TITLE
New pull request for go map.md

### PR DESCRIPTION
**Pull request by JustinSu77**
### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — APPROVED** [review]
@JustinSu77 Thanks for the new PR.

**Comment by SSwiniarski** [comment]
This is a redo of [1263](https://github.com/Codecademy/docs/pull/1263) and the content has already been reviewed by @yangc95 and @HishamT so it should be ready to merge.

**Review by yangc95 — APPROVED** [review]

**Comment by yangc95** [comment]
@JustinSu77 great addition! Here is the live link: https://www.codecademy.com/resources/docs/go/map
Screen Shot 2022-12-21 at 9 22 06 PM
You're currently anonymous but if you'd like to become a public contributor, make sure to add your GitHub username to your Codecademy profile and set you visibility to everyone! Thanks 😄 
cc: @HishamT @SSwiniarski

**Comment by JustinSu77** [comment]
How do I not be anonymous after contributing to the docs? I did not link my
codecademy profile to github properly when I thought I did. It took a long
time for me to get my contribution merged. I will like my profile pic below
the contributors.

**Pull request merged**
