### PR TITLE
added codebyte to JavaScript arrays to slice and toString method 

### LINKED ISSUE #2277: [Edit] JavaScript Add Codebytes
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Please add Codebytes to the listed entries.
https://www.codecademy.com/resources/docs/javascript/arrays/slice
https://www.codecademy.com/resources/docs/javascript/arrays/toString

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

Bear in mind the following two principles:
1) There should only be one Codebyte per entry listed as `## Codebyte Example` at the end of the entry.
2) The codebytes should be new examples, not copies of the prior examples.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by yashladekar**
### Description

@yoiang  please review my changes 

issue #2277

Add code bytes for array slilce() and array toString() method 

This PR adds two new codebytes to the javaScript documentation that demonstrate how to use these two methods 

the first code byte shows  how to create a copy of a portion fo an array using the slice() method. 
the second code byte shows how to  convert an array into a string using the toString() method. 

these code bytes provide clear and concise examples that will help reader to understand how to use these important array methods.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #2277 in the "Description" above).

### CODE REVIEW

**Review by caupolicandiaz — APPROVED** [review]
@yashladekar Overall this looks good, I just added a few minor edits. This is ready for a second review.

**Review by SSwiniarski — APPROVED** [review]
@yashladekar, looks good to merge.

**Comment by SSwiniarski** [comment]
@yashladekar Congrats on the new edits!

Live links here:
- https://www.codecademy.com/resources/docs/javascript/arrays/slice
- https://www.codecademy.com/resources/docs/javascript/arrays/toString

**Comment by yashladekar** [comment]
thanks for letting me contribute , it was fun!

**Pull request merged**
