### PR TITLE
[ Term Entry ] Exp

### PR DESCRIPTION
**Pull request by MMMMMMMZ**
### Description

addresses issue #2269

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by MMMMMMMZ** [comment]
for some reason the mixed-up timeline from str_repeat snuck into the exp branch I created I tried a lot of stuff to remove the commits from str_repeat , I removed most of it but the str_repeat_edit commits still are here

**Comment by MMMMMMMZ** [comment]
oh and whoever reviews please answer #2460 as I would like my name to be on both entries

**Comment by shivangnayar-crypto** [comment]
Hey i need help how to pass those ci checks can u guide me

**Comment by shivangnayar-crypto** [comment]
@MMMMMMMZ

**Comment by shivangnayar-crypto** [comment]
This is my pr https://github.com/Codecademy/docs/pull/2459

**Comment by SSwiniarski** [comment]
> for some reason the mixed-up timeline from str_repeat snuck into the exp branch I created I tried a lot of stuff to remove the commits from str_repeat , I removed most of it but the str_repeat_edit commits still are here

@MMMMMMMZ That happened because you created your branch from the prior branch rather than main. You have two choices: 
1) You can make a fresh branch from main and copy the file from this PR to that branch and create a new PR. 
2) Undo the edits to the other file in this branch. (This won't affect the prior branch.)

Choose whatever would be easiest for you. Once that's sorted out we can review this PR. (Or the new one, if you go that route.)

**Pull request closed without merging**
