### PR TITLE
[Edit] Swift Bold Big O

### LINKED ISSUE #2222: [Edit] Swift Bold Big O
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

Please bold any mentions of big-o notation. For instance, if the text includes "O(x)" to some effect, we'lll go ahead and use a pair of two asterisks, e.g., **O(x)**.

The entry should change the following files:

- `content/swift/concepts/arrays/terms/append/append.md`
- `content/swift/concepts/arrays/terms/contains/contains.md`

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by gracekishino**
### Description

Bold any mentions of big O notation.

Closes #2222

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — APPROVED** [review]
@gracekishino Looks good.

**Comment by SSwiniarski** [comment]
@gracekishino I think this is straightforward enough to merge with one review.

**Comment by SSwiniarski** [comment]
@gracekishino Congrats on the new edit.

Live links:
- https://www.codecademy.com/resources/docs/swift/arrays/append
- https://www.codecademy.com/resources/docs/swift/arrays/contains

**Comment by gracekishino** [comment]
@SSwiniarski Thank you for reviewing and merging this!

**Pull request merged**
