### PR TITLE
[Term Entry] Python Built-in Functions ord()

### PR DESCRIPTION
**Pull request by missh11**
### Description

- Added the ord() term for Python
- Closes Issue #2150 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by caupolicandiaz — CHANGES_REQUESTED** [review]
@missh11 I've added just one edit. Overall, looks good. Please tag me when you've made the changes. Thanks

**Comment by missh11** [comment]
@caupolicandiaz Made the changes you suggested

**Review by caupolicandiaz — APPROVED** [review]
@missh11 LGTM. This is ready for a second review.

**Review by SSwiniarski — APPROVED** [review]
@missh11 Looks good to merge!

**Comment by SSwiniarski** [comment]
@missh11 congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/python/built-in-functions/ord

image

**Pull request merged**
