### PR TITLE
Added loops.md in the kotlin folder. Also rePushing the arrays.md file.

### PR DESCRIPTION
**Pull request by dakshdeepHERE**
### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by dakshdeepHERE** [comment]
@SSwiniarski I created a new branch different from the last branch then why are the commits same as that pull request that we closed before because of this cla issue?

**Comment by dakshdeepHERE** [comment]
you can see I even created a new branch which is **loops** but still why this pr opened with the old one?

**Comment by dakshdeepHERE** [comment]
image

**Comment by SSwiniarski** [comment]
@dakshdeepHERE. You must have branched this from the earlier arrays branch, rather than your main branch. Create a new branch for each of these, (one for loops, one for arrays) off of the main branch and then copy the changes to the separate branches. Do you want me to close this PR so you can do this?

**Comment by dakshdeepHERE** [comment]
@SSwiniarski What? but I did that only I created new loops branch.First I have to checkout main then then write **git branch newBranchName** right? to create a new branch? Separate from loops

**Comment by dakshdeepHERE** [comment]
I dont know really what is happening at all. I even cloned this project in new folder and there created the new branch loops and created the arrays and loops file from zero then how this PR is getting pushed in the old loops pr ? 😭

**Comment by dakshdeepHERE** [comment]
@SSwiniarski close this pr and the other one too I have no idea what is going on.I'm trying my best even passed all the tests on my vs code terminal. yarn test and yarn lint both passed I have no idea what is going on now. 😭

**Pull request closed without merging**
