### PR TITLE
add-c#-codebytes

### LINKED ISSUE #2153: [Edit] C# Add Codebytes
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Please add Codebytes to the listed entries.       
https://www.codecademy.com/resources/docs/c-sharp/arrays/clear
https://www.codecademy.com/resources/docs/c-sharp/arrays/length
https://www.codecademy.com/resources/docs/c-sharp/arrays/resize

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [style guide](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md) when working on the PR for this issue.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by nikolaspoczekaj**
### Description

Hi, thanks for assigning. I added short codebytes. Let me know if they are good or if they should be longer.
This closes #2153 .

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — CHANGES_REQUESTED** [review]
@nikolaspoczekaj I did a first review and had a couple of comments.

**Review by SSwiniarski — APPROVED** [review]
@nikolaspoczekaj Looks good for a second review.

**Review by caupolicandiaz — APPROVED** [review]
@nikolaspoczekaj I've finished my review. I went ahead and made a few minor edits which included removing extra lines and changing some of the introductory text for one of the code bytes.

**Review by SSwiniarski — APPROVED** [review]

**Comment by SSwiniarski** [comment]
@nikolaspoczekaj congrats on the new updates! 

Live links:
- https://www.codecademy.com/resources/docs/c-sharp/arrays/clear
- https://www.codecademy.com/resources/docs/c-sharp/arrays/length
- https://www.codecademy.com/resources/docs/c-sharp/arrays/resize

**Pull request merged**
