### PR TITLE
SQL Command Typo Corrections

### PR DESCRIPTION
**Pull request by JulesOfAllTrades**
### Description
Made a few small typo corrections to the sql content commands files, specifically, inner join, outer join, and select. Not all tests are currently passing, would love some guidance on how to correct that.

### Type of Change

- [ ] Adding a new entry
- [x] Editing an existing entry (fixing a typo, bug, issues, etc)
- [ ] Updating the documentation

### Checklist

- [x] My entry follows the Codecademy Docs style guide
- [x] I have performed a self-review of my own writing and code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have checked my entry and corrected any misspellings
- [x] All writings are my own

### Codecademy Username

If you want your Codecademy username be displayed in your entry (feature coming in October), make sure to have your Codecademy user profile linked to your GitHub:

1. Go to your Codecademy dashboard.
2. Click on your profile image in the top-right and then choose "Profile".
3. Then click "Edit Profile".
4. In the GitHub field, add your GitHub profile URL.

### CODE REVIEW

**Review by sonnynomnom — APPROVED** [review]
Congrats on your first PR! 

Also, great catches. Woohoo :)

**Review by JoshuaKGoldberg — APPROVED** [review]
💯

**Comment by JulesOfAllTrades** [comment]
> Congrats on your first PR!
> 
> Also, great catches. Woohoo :)

Thanks @sonnynomnom !

I can't merge due to a failing test. Do you know how I can fix it?
image

**Comment by mdwiltfong** [comment]
I've gone ahead and shared @lukeecart PR with Julia but in case anyone else goes digging for it here is what is recommended: 
https://github.com/Codecademy/docs/pull/238

**Comment by JulesOfAllTrades** [comment]
@JoshuaKGoldberg thanks for merging main into my branch. Looks like all CI checks have succeeded - is this ready to go now?

**Comment by JoshuaKGoldberg** [comment]
:shipit:

**Pull request merged**
