### PR TITLE
Add branch naming instructions

### PR DESCRIPTION
**Pull request by Dusch4593**
### Description

This PR replaces PRs #233 and #239 per a goof-up on my end. The changes 

### Type of Change

- [ ] Adding a new entry
- [ ] Editing an existing entry (fixing a typo, bug, issues, etc)
- [X] Updating the documentation

### Checklist

- [X] My entry follows the Codecademy Docs style guide
- [X] I have performed a self-review of my own writing and code
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have checked my entry and corrected any misspellings
- [X] All writings are my own

### CODE REVIEW

**Review by lukeca362 — APPROVED** [review]
LGTM 👍🏻

**Review by lukeecart — APPROVED** [review]

**Review by yangc95 — APPROVED** [review]

**Comment by Dusch4593** [comment]
Hmm looks like CircleCI doesn't seem to be happy with the format of `content/c/concepts/memory-management/memory-management.md`. 

After running `npm run format:all`, @codecademy/prettier makes a change to this file on line 20 and this seems to be causing the hiccup. 

This is the exact message I'm getting in CircleCI:

```
#!/bin/bash -eo pipefail
yarn format:verify
yarn run v1.21.1
$ prettier "./**/*.(ts|md)" --list-different
content/c/concepts/memory-management/memory-management.md
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Exited with code exit status 1
CircleCI received exit code 1
```

Any thoughts on how to proceed?

**Comment by Dusch4593** [comment]
I also notice on `verify_lint` that the issue seems to be a trailing space in `memory-management.md`?

```
./content/c/concepts/memory-management/memory-management.md:20:191 MD009/no-trailing-spaces Trailing spaces [Expected: 0 or 2; Actual: 1]
```

But I can't tell if there is one? 

Screen Shot 2021-09-14 at 8 31 47 AM

**Comment by Dusch4593** [comment]
Ok, so I created a new PR ([#247](https://github.com/Codecademy/docs/pull/247)) to squash this whitespace issue. Once that is merged, I'll re-`pull` the changes into this branch, re-run `npm run format:all`, and see how the tests run then.

**Comment by Dusch4593** [comment]
Cool looks like tests are passing now! 🎊

**Review by yangc95 — APPROVED** [review]

**Comment by Dusch4593** [comment]
Has everybody signed the CLA?

**Review by yangc95 — APPROVED** [review]

**Pull request merged**
