### PR TITLE
added png images of Einstein, Jobs

### LINKED ISSUE #3232: [Edit] HTML Add Media: Quotations
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to make an edit for HTML Quotations. The entry should go in the existing file in docs/content/html/concepts/quotations/quotations.md

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Bear in mind:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media should accurately represent the existing content and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by MartynaBee**
### Description

Added images the form of .png to supplement content.
Closes #3232

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR

### CODE REVIEW

**Comment by yangc95** [comment]
Hey @MartynaBee,

Thanks for opening this PR! You can use any method to have some HTML block display on a browser of your preference, but an image that doesn't match contextually won't be accepted.

If you have any questions, I'm glad to be of assistance!

**Comment by SSwiniarski** [comment]
@MartynaBee you need to upload the images you wish to use to the `/media` folder in the repository. You also need to use image links as specified in the style-guide [here](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#file-hosting). Also, file names should be more descriptive and be in lower case, using dashes as separators.

**Comment by SSwiniarski** [comment]
@MartynaBee you also still need to sign the [CLA](https://cla-assistant.io/Codecademy/docs?pullRequest=3257).

**Review by SSwiniarski — APPROVED** [review]
@MartynaBee I made a few edits and now this is ready for a second review.

**Review by yangc95 — APPROVED** [review]

**Pull request merged**
