### PR TITLE
fix typos in general documentation

### PR DESCRIPTION
**Pull request by garanews**
fix typos in general documentation

### CODE REVIEW

**Review by SSwiniarski — CHANGES_REQUESTED** [review]
@garanews, I reviewed and left comments shortening the descriptions being touched.

**Comment by SSwiniarski** [comment]
> @SSwiniarski so can I go ahead and confirm your "shortening description" edits?

@garanews please do.

**Comment by garanews** [comment]
@SSwiniarski done!

**Review by SSwiniarski — APPROVED** [review]
Looks good.

**Review by yangc95 — APPROVED** [review]

**Comment by yangc95** [comment]
Thanks for these fixes @garanews 

In interest of time, I bolded some key words here (with some grammar fixes and italics removal): [a3db61b](https://github.com/Codecademy/docs/pull/1067/commits/a3db61bbbb9257db84620173eda8b1185a54c4a3)
Your changes should be visible in the General topics section!

cc: @Dusch4593 @SSwiniarski

**Comment by garanews** [comment]
Thanks @yangc95 !

**Pull request merged**
