### PR TITLE
New js concept vuejs

### PR DESCRIPTION
**Pull request by Armania**
### Description

This is a starting base for a new Javascript concept Vuejs. I started this pull request like this so I can submit each section as its own pr and be able to review it.

### Type of Change

- Adding a new entry

### Checklist

- [ x] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by Armania** [comment]
I created a "skeleton" of pages for the content for this section.

I have 21 "terms" to submit.

I was thinking about creating a pull request for each term. This should make it easier to review and edit

**Comment by yangc95** [comment]
@Armania after taking a quick glance, I noticed that many files were created with only metadata and no content.

In hopes of continuing the work on Issue #1285 and this [comment](https://github.com/Codecademy/docs/issues/1285#issuecomment-1344798400), it appears that only one new file on Vue.js was excepted. I recommend deleting all files except the one named `vue` and adding some content. There is a [template](https://github.com/Codecademy/docs/blob/main/documentation/entry-template.md) in the [`documentation/`](https://github.com/Codecademy/docs/tree/main/documentation) folder that can be followed.

Please let me know if you have any concerns!

**Comment by SSwiniarski** [comment]
@Armania It's been two weeks, and I want to follow up on @yangc95's comments. Are you going to edit this PR, or should we just close it and wait for a new PR from you?

**Comment by yangc95** [comment]
@SSwiniarski I'm going to go ahead and close this PR in hopes of a new PR. Continued discussion on the original issue!

Cc: @Armania

**Pull request closed without merging**
