### PR TITLE
[Term Entry] CSS Filter Function: drop-shadow()

### PR DESCRIPTION
**Pull request by giliopoulosaz**
### Type of Change

- Adding a new entry
- Updating the documentation
- Closes Issue  #3965

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by Kadif-Ravik** [comment]
Is this issue open?

**Review by dakshdeepHERE — APPROVED** [review]
Looks good for second review 🚀

**Comment by SSwiniarski** [comment]
@Kadif-Ravik This is a PR not an issue. Someone else is already working on it.

**Review by SSwiniarski — APPROVED** [review]
@giliopoulosaz I made one small spacing change so the checks passed. Now it looks good to merge.

**Pull request merged**
