### PR TITLE
Wip 984 term entry remainder

### PR DESCRIPTION
**Pull request by ddiegow**
### Description

I have created a remainder folder and a remainder.md file as stated in task instructions.  I have included the remainder() function syntax, a few important notes on the function itself, a syntax example with the results after running the code and a codebyte c++ example.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — CHANGES_REQUESTED** [review]
@ddiegow, I did a first review and left a few comments.

**Comment by Dusch4593** [comment]
Hey @ddiegow, thank you so much for your patience with this PR. After conferring with my colleagues about the best/safest way to go about the "Daniel" issue, we've determined that we should open a new PR (under a new PR branch), transfer the changes made thus far to the appropriate file(s)

1. Ensure the correct email and username are configured with Git and GitHub. Correct me if I'm wrong, but I believe you'd said you already did this?

2. **On GitHub:** your fork of this repo, switch back to your `main` branch and catch it up with the most recent changes to Docs:

  Screen Shot 2022-11-17 at 12 08 38 PM

**On the terminal/command line:** Let's run the following Git commands:

```shell
git checkout main
git pull
```

3. Now that your fork's `main` branch is caught up both locally and remotely, let's create and checkout into a new branch called `term-entry-remainder`, like so:

```shell
git checkout -b term-entry-remainder
```

4. Then, however you see fit, we'll need to transfer the changes made in `remainder/remainder.md` thus far into this new branch. I recommend the following steps:
  i. Create a new folder named `remainder` under `cpp/concepts/math-functions/terms/`.
  ii. Create a new file in `remainder/`, called `remainder.md`.
  iii. Copy the contents of the changes thus far from [here](https://github.com/ddiegow/CodeAcademyDocs/edit/wip-984-term-entry-remainder/content/cpp/concepts/math-functions/terms/remainder/remainder.md?pr=%2FCodecademy%2Fdocs%2Fpull%2F1239), and then paste into the new `remainder.md` file.
  iv. Save the changes in the new `remainder.md` file.

5. Go ahead and add, commit, and push these changes and create the new PR on GitHub. 😄

**Comment by Dusch4593** [comment]
@ddiegow After you create the new PR, and we've ensured you're the only account tethered to all the commits for it, we'll merge after the next review + approval. 😄 🚀

**Comment by ddiegow** [comment]
Thanks for the help @Dusch4593 ! I created a new pull request :)

**Comment by SSwiniarski** [comment]
Closing because of new [pull request](https://github.com/Codecademy/docs/pull/1267).

**Pull request closed without merging**
