### PR TITLE
Added info about `.length` in the arrays term folder of `java`

### LINKED ISSUE #1451: [Term Entry] Java Array: `.length` property
### Reason/inspiration (optional)

Add a new term entry under the [Java: Array](https://www.codecademy.com/resources/docs/java/array-list) concept. This entry should include:

- An explanation of the property.
- A "Syntax" section with a ```pseudo code snippet showing the general syntax.
- An "Example" section with a ```java code snippet showing how it works.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by dakshdeepHERE**
### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

Fixes #1451

### CODE REVIEW

**Comment by KTom101** [comment]
@dakshdeepHERE I've taken a quick look at this and I'm noticing an issue with this. 


This is for the `.length()` method for "Strings". The linked issue asked for the `.length` property for "Arrays". These are two different topics and there is already an entry for `.length()` under "Strings": https://www.codecademy.com/resources/docs/java/strings/length

If you're getting confused between the two, notice `.length()` for "Strings" has `()` after it indicating it is a method while `.length` for "Arrays" doesn't have `()`.

**Comment by KTom101** [comment]
@dakshdeepHERE Also, once the issues I've mentioned above are corrected, this would need to be added to the correct folder. You currently have it under "array-list" when it should be under "arrays".

**Comment by dakshdeepHERE** [comment]
@KTom101 wait oh yes! Yes you are correct I was suppose to change this I thought its already done. I guess we discussed this issue on some other issue. No worries I will update it right now.

**Comment by KTom101** [comment]
@dakshdeepHERE Are you still working on this? Please let me know so I can look into reassigning this if necessary.

**Comment by dakshdeepHERE** [comment]
Yes @KTom101

**Comment by KTom101** [comment]
@dakshdeepHERE I've marked this as invalid and I am closing this PR out due to inactivity. You can make a new PR with the correct term topic and proper file placement. If a new PR is not created soon, you may be unassigned from [issue #1451](https://github.com/Codecademy/docs/issues/1451) entirely.

**Pull request closed without merging**
