### PR TITLE
added .length in the array terms folder

### LINKED ISSUE #1451: [Term Entry] Java Array: `.length` property
### Reason/inspiration (optional)

Add a new term entry under the [Java: Array](https://www.codecademy.com/resources/docs/java/array-list) concept. This entry should include:

- An explanation of the property.
- A "Syntax" section with a ```pseudo code snippet showing the general syntax.
- An "Example" section with a ```java code snippet showing how it works.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by dakshdeepHERE**
### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

Fixes #1451

### CODE REVIEW

**Review by SSwiniarski — APPROVED** [review]
@dakshdeepHERE Looks good to me on first review. I'm sending it on to a second.

**Review by KTom101 — CHANGES_REQUESTED** [review]
@dakshdeepHERE I've added some changes!

**Comment by dakshdeepHERE** [comment]
@KTom101 done

**Review by KTom101 — APPROVED** [review]
@dakshdeepHERE LGTM

**Comment by SSwiniarski** [comment]
@dakshdeepHERE congrats on another strong entry. Live link is here:https://www.codecademy.com/resources/docs/java/arrays/length

image

**Pull request merged**
