### PR TITLE
Update hashmap.md

### PR DESCRIPTION
**Pull request by WarpWing**
### Description

Fixed Hashmap Entry link to Map by changing from uppercase M to lowercase m in map.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [ x] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — APPROVED** [review]
@WarpWing looks good as-is.

**Comment by WarpWing** [comment]
Thanks @SSwiniarski . I do want to note that I've also found errors in Treemap as well in terms of a broken map redirect. Will fix in another PR

**Review by yangc95 — APPROVED** [review]
LGTM for merge. I edited some code blocks as one had a technical typo. Also removed the extra spacing for some blocks of code and small edits here and there. (See [14aff93](https://github.com/Codecademy/docs/pull/1200/commits/14aff93b3e8cf3b5e58ac8c849342593ea925f9f for more details))

**Comment by yangc95** [comment]
@WarpWing updates can be seen here! https://www.codecademy.com/resources/docs/java/hashmap

**Comment by WarpWing** [comment]
> @WarpWing updates can be seen here! https://www.codecademy.com/resources/docs/java/hashmap
> Screen Shot 2022-11-01 at 6 27 39 PM

Great! I'm going to audit the rest of the pages and see if there are more broken links!

**Pull request merged**
