### PR TITLE
[Edit Entry] Center 

### LINKED ISSUE #2857: Add information about depreciation
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

Center is no longer used to center elements so I think there should be a note providing this information and a link to the text-align center entry. 
Note: I want to do this change 

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by CBID2**
### Type of Change
In this PR, I turned the paragraph about the `text-align: center` being used into a note. Making this change would emphasize the need for developers and people who code to stop using the `<center>` element to center content. 
Fixes #2857   

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by CBID2** [comment]
Hi @KTom101! :) This PR is ready for a review! :)

**Review by yangc95 — COMMENTED** [review]
@CBID2 yay for this initiative! And good idea - I'm thinking the note can include what's written on line 17 as well

**Comment by CBID2** [comment]
> @CBID2 yay for this initiative! And good idea - I'm thinking the note can include what's written on line 17 as well

Hi @yangc95. Can you do a in-line suggestion of your idea? I'm struggling with seeing the benefit of mentioning the specification again. This would make it repetitive.

**Review by yangc95 — APPROVED** [review]
@CBID2 sorry for the confusion, I went ahead with the direct edit. I meant to move the deprecation mention into the note.

**Comment by CBID2** [comment]
> @CBID2 sorry for the confusion, I went ahead with the direct edit. I meant to move the deprecation mention into the note.

It's ok @yangc95.

**Review by SSwiniarski — APPROVED** [review]
@CBID2 Looks good.

**Pull request merged**
