### PR TITLE
[Edit] JavaScript: Loops

### PR DESCRIPTION
**Pull request by ntsukada2**
### Issue Solved

- Added an example of the continue keyword being used in a for loop in JavaScript
- Closes Issue #4889 
### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by SaviDahegaonkar — CHANGES_REQUESTED** [review]
Hey @ntsukada2 ,
I had a look at your file and It's almost correct I have suggested some minor changes so please check for it.

**Comment by SaviDahegaonkar** [comment]
Hello @ntsukada2,
Are you still working on this PR. Please let me know.

**Comment by ntsukada2** [comment]
> Hello @ntsukada2, Are you still working on this PR ? Please let me know.

Yes - just added your suggested changes. Let me know if any other edits are necessary.

**Review by SaviDahegaonkar — APPROVED** [review]
Hey @ntsukada2 ,
LGTM! I hereby approve it.

**Review by avdhoottt — APPROVED** [review]
LGTM

**Pull request merged**
