### PR TITLE
fixed a typo - changed excepts to accepts

### LINKED ISSUE #2841: [Term Entry] Go Math Function Sqrt() entry sqrt.md contains a typographical error
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

There is a typographical error in [content/go/concepts/math-functions/terms/sqrt/sqrt.md](https://github.com/Codecademy/docs/blob/726ef60d335dd1fc927daa9d5f072b08d13ecf80/content/go/concepts/math-functions/terms/sqrt/sqrt.md) whereby 'excepts' was used instead of 'accepts'.

In the syntax section of the document, the following:

`Sqrt()` excepts an argument of type `float64` and returns a value of type `float64`.

should be changed to:

`Sqrt()` accepts an argument of type `float64` and returns a value of type `float64`.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by Don-Booth**
### Description

Changed one word in Go Terms Math Sqrt() - changed 'excepts' to 'accepts'
Closes #2841 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
LGTM! :)

**Review by caupolicandiaz — APPROVED** [review]
@Don-Booth Looks good

**Review by SSwiniarski — APPROVED** [review]
@Don-Booth looks good to merge.

**Comment by SSwiniarski** [comment]
@Don-Booth congrats on the new edit. 

Live link:
- https://www.codecademy.com/resources/docs/go/math-functions/sqrt

**Pull request merged**
