### PR TITLE
Fix: [Broken Links] Links Audit: Entry 5 #1903

### PR DESCRIPTION
**Pull request by Yannssouza**
### Description

I fixed the two links in the entry 5 of issue #1903. 
Note: not all links in the entries are really broken.

### Type of Change

- Fixed Broken Links

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by caupolicandiaz** [comment]
@Yannssouza Generally speaking, we ask that anyone interested in contributing request an assignment by commenting on a specific issue. No one has claimed this issue yet, so you are free to work on it. But, we ask that you address all the entries that are included in the issue. Please let us know if you have any questions.

**Comment by KTom101** [comment]
@Yannssouza I took a quick look at this and I believe you're supposed to make the corrections for each entry listed in the issue, not just one. 

@caupolicandiaz Is this correct?

**Comment by caupolicandiaz** [comment]
> @Yannssouza I took a quick look at this and I believe you're supposed to make the corrections for each entry listed in the issue, not just one.
> 
> @caupolicandiaz Is this correct?

Yes, all the entries in the table should be fixed as part of this PR.

**Comment by KTom101** [comment]
@Yannssouza I'm marking this as invalid until there is an update from you. Please look carefully at the issue and add all the missing entries. Also, remove all the extra files from the `.idea` folder, these shouldn't be in the PR.

**Comment by caupolicandiaz** [comment]
@Yannssouza Apologies, but we haven't heard back from you so we're going to close this PR and assign it to someone else. Feel free to request an assignment to another issues in the future. Please take a look at the open issues and leave a comment on an open issue that you would like to take on. Thanks

**Pull request closed without merging**
