### PR TITLE
Mark tag example

### PR DESCRIPTION
**Pull request by ethan-master-coding**
### Description

Added the result of the code. Also removed some boilerplate code.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — APPROVED** [review]
@ethan-master-coding: This looks good to me. My only comment is that since you're editing this entry already, you might as well add 'Semantic' to the Tags section. @Dusch4593, @yangc95 , @KTom101, second review?

**Comment by ethan-master-coding** [comment]
@SSwiniarski made the edit. Out of curiosity what are the tags for.

**Review by yangc95 — APPROVED** [review]
This is looking good to me!

@ethan-master-coding would you mind if I go into your branch to format this?

**Comment by ethan-master-coding** [comment]
@yangc95 I don't care if any of you made direct changes to the branch as long as the change would not be up to debate. So yes.

**Comment by christian-dinh** [comment]
🤘😈

**Comment by yangc95** [comment]
@ethan-master-coding edits should be live here:

https://www.codecademy.com/resources/docs/html/semantic-html/mark

ty @SSwiniarski @Dusch4593 @christian-dinh 🙌

**Pull request merged**
