### PR TITLE
Remove src example

### PR DESCRIPTION
**Pull request by elliezub**
### Description

Closes issue [Codecademy#2491](https://github.com/Codecademy/docs/issues/2491)
This change is in reference to [this issue](https://github.com/Codecademy/docs/issues/2491).
Now that the entry for the [src attribute](https://www.codecademy.com/resources/docs/html/attributes/src) is created, STBs src example in [the attributes entry](https://www.codecademy.com/resources/docs/html/attributes)
is removed.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks good to me! :) You just have to sign the CLI agreement

**Comment by CBID2** [comment]
Oh great you did it! :) @SSwiniarski, this PR is ready to be reviewed! :)

**Review by SSwiniarski — APPROVED** [review]
@elliezub Looks good to me. On to a second review.

**Comment by CBID2** [comment]
@yangc95, this PR is ready to be reviewed. :)

**Review by KTom101 — APPROVED** [review]
@elliezub Thank you for this change!

**Comment by CBID2** [comment]
> @elliezub Thank you for this change!

Woohoo! You did it @elliezub! 😄 You made your first PR! 😄 I'm so proud of you! 😄  🫂

**Comment by KTom101** [comment]
@elliezub The changes are live: https://www.codecademy.com/resources/docs/html/attributes

You're currently labeled as an anonymous contributor. If you wish to remain that way, there is nothing more you need to do. If you want to be listed, please follow the instructions in this [forum thread](https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036). 

cc @yangc95

**Comment by elliezub** [comment]
Thank you everyone !! Thanks Chrissy 💜

**Pull request merged**
