### PR TITLE
[Edit] CSS Colors: opacity

### PR DESCRIPTION
**Pull request by Kadif-Ravik**
### Description
Image showing full and half opacity of text.

### Type of Change

- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by Kadif-Ravik** [comment]
@SSwiniarski

**Comment by Kadif-Ravik** [comment]
@SSwiniarski do I need to do something in reference to #3736?

**Comment by SSwiniarski** [comment]
> @SSwiniarski do I need to do something in reference to #3736?

@Kadif-Ravik no, I've linked thit PR to the issue so when this is merged it should close the issue automatically.

**Comment by Kadif-Ravik** [comment]
@SSwiniarski Okay, thanks.

**Review by caupolicandiaz — APPROVED** [review]
@Kadif-Ravik This is a bit of a nitpick, but it would be preferable if the image was cropped a bit tighter. The margins on the top and bottom are very large.

**Comment by Kadif-Ravik** [comment]
@caupolicandiaz Will do.

**Comment by Kadif-Ravik** [comment]
@caupolicandiaz resized opacity image.

**Review by SSwiniarski — APPROVED** [review]
@Kadif-Ravik Looks good.

**Pull request merged**
