### PR TITLE
Quick Sort

### LINKED ISSUE #4149: [Entry] Algorithms: Adding QuickSort
### Reason/inspiration (optional)

In the Algorithms Folder, I would like to add the following Sorting Algo:
- QuickSort

Within this doc, there should be 
- A brief explanation of the sorting algorithm (including time complexity):
- graphical/photographic representation 
- example code of sorting algo
- explanation of the sorting code 

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by JustinhSE**
### Description

Closes #4149

### Type of Change

- Adding a new entry

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by dakshdeepHERE — CHANGES_REQUESTED** [review]
Some changes and I would like you to mention these points in the entry too:
- If we already have merge sort with Time complexity (nlogn) then why quick sort? Hint: mention about the temporary list that merge sort creates (in place sorting) and better space allocation.
- Worst case addition: In your worst case explanation you just explained what the worst case scenario is but mention also how to bypass that. Mention about `Randomized quicksort` which can be used to almost never hit that time complexity. 
Work on these two comments and we will again review the entry.

**Comment by JustinhSE** [comment]
@dakshdeepHERE sorry for the delay, been really busy since college started up and preparing for interviews. Once I finish my interview on Thursday I will finish this up. I have 1/2 the edits done.

**Comment by JustinhSE** [comment]
Yes, just finished my CS midterm yesterday. It’s actually on my todo list I made this morning.

**Comment by JustinhSE** [comment]
@dakshdeepHERE expect a request no later then Tuesday

**Comment by JustinhSE** [comment]
@dakshdeepHERE sorry for the delay, but it is finished!

**Comment by JustinhSE** [comment]
Np! @dakshdeepHERE

**Review by Sriparno08 — APPROVED** [review]
Looks good! 👍

**Pull request merged**
