### PR TITLE
Dart methods

### LINKED ISSUE #4252: [Concept Entry] Methods: New concept entry `methods.md`
### Reason/inspiration (optional)

We would like a new term entry on the `Methods` concept for [Dart](https://www.codecademy.com/resources/docs/dart). The entry should go under the following path `docs/content/dart/concepts/methods/methods.md`.

The entry should describe the term and how it is used within Dart. Also include: 
- There should be "## Syntax" and "## Example" headings in this entry.
- Explain briefly what methods are in Dart with suitable code snippets.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by brandk94**
### Description

- Created a new sub-directory called 'methods' for the existing directory:   'content/dart/concepts'
- Created and edited a new file called 'methods.md' for the directory:    'content/dart/concepts/methods'

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by helfese — APPROVED** [review]

**Comment by brandk94** [comment]
Hello @dakshdeepHERE.  I am stilling willing to do any more needed work on this issue.  Two months ago, I submitted a pull request to merge my personal branch containing the revised file for the "Dart methods" document, but I never got a response on whether it was approved for merging or needed to be worked on even further.  Has it been received it and reviewed yet?

**Comment by ishg-153** [comment]
@brandk94 There seems to be an issue with the CLA. It might be that you have not configured your local bash/command line with the same email as your GitHub account. To fix this, please set up your git config email and username. Once done, create a new branch from your forks main and push this same file and create a new PR.

When you do let me know and we will take it from there. (After you create the new PR I will close this PR as stale).

**Comment by ishg-153** [comment]
@brandk94 There seems to be an issue with the CLA. It might be that you have not configured your local bash/command line with the same email as your GitHub account. To fix this, please set up your git config email and username. Once done, create a new branch from your forks main and push this same file and create a new PR.

When you do let me know and we will take it from there. (After you create the new PR I will close this PR as stale).

**Comment by brandk94** [comment]
Hi @ishg-153.  I reconfigured my local Git Bash command line's email address and username to match the ones I have set in my GitHub account.  I also created a new branch called "new_dart_methods_branch" on my forked repository that matches my old "dart_methods" branch and I have also made a new Pull Request titled "Dart Methods (New Pull Request)" for that new branch. 
 Thus, I have resigned the CLA to hopefully fix the issue. If there are still any problems with this, please let me know.  Thank You.

**Comment by ishg-153** [comment]
@brandk94 Great! Closing this PR as a duplicate.

**Pull request closed without merging**
