### PR TITLE
Adding math-fsum.md to explain how math.fsum() works

### LINKED ISSUE #5033: [Term Entry] Python math-module math.fsum()
### Reason/inspiration (optional)

We would like a new term entry on the `math.fsum()` method of the [`math-module`](https://www.codecademy.com/resources/docs/python/math-module) concept in Python. The entry should go in a new file under `docs/content/python/concepts/math-module/terms/math-fsum/math-fsum.md`

The entry should include the following:

- A description of the term
- A ##Syntax section that includes the syntax of the method and its details
- An ##Example section that includes a ```py ``` codeblock and ```shell ``` that shows the example output.
- A ##Codebyte Example to show the working of the method

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by imscuevas**
### Description

Adding math-fsum.md to python folder to explain how math.fsum() works. This was done because I was studying for the Learn Git and Github course and this is my first contribution to someone else's repository.

### Issue Solved

Closes #5033

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by cigar-galaxy82 — CHANGES_REQUESTED** [review]

**Comment by cigar-galaxy82** [comment]
Hi @imscuevas thank you for contributing to Codecademy docs, I have suggested a few changes please modify them.

**Comment by mamtawardhani** [comment]
What's the status on this? @cigar-galaxy82

**Review by cigar-galaxy82 — APPROVED** [review]

**Comment by cigar-galaxy82** [comment]
@mamtawardhani ready for next review

**Review by mamtawardhani — APPROVED** [review]
Thank you for contributing @imscuevas 

The entry is ready to be merged 🚀

**Pull request merged**
