### PR TITLE
update typo error

### PR DESCRIPTION
**Pull request by etendra2501**
### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by KTom101** [comment]
@etendra2501 Thank you for spotting these typos! For this to be merged, you will need to sign the CLA above. Please sign this so we can continue the process!

**Comment by etendra2501** [comment]
I'm signed CLA

**Comment by KTom101** [comment]
@etendra2501 The changes are live [here](https://www.codecademy.com/resources/docs/cpp/arrays). Currently you're not listed as a contributor. 

image

If you would like to be listed, add your GitHub username to your Codecademy profile (instructions below). If not, there is nothing else that needs to be done. 

To add your GitHub username to your Codecademy profile:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

image

2.) Then log out and log back into Codecademy using your GitHub login:

image

**Comment by KTom101** [comment]
@etendra2501 Also, feel free to take a look at the [issues tab](https://github.com/Codecademy/docs/issues) to see if there is any unclaimed issue you would like to work or let us know if there is something you would like to add!

**Pull request merged**
