### PR TITLE
New term added scatter3d()

### LINKED ISSUE #5169: [Term Entry] Python Plotly - express .scatter_3d()
### Reason/inspiration (optional)

We would like a new term entry on the `.scatter_3d()` method of the [`express module`](https://www.codecademy.com/resources/docs/plotly/express) in Plotly, Python. The entry should go in a new file under `docs/content/plotly/concepts/express/terms/scatter_3d/scatter_3d.md`

The entry should include the following:

- A description of the term
- A ##Syntax section that includes the syntax of the method and its details
- An ##Example section that includes a ```py ``` codeblock and ```shell ``` that shows the example output.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by pritamjr**
### Description

Added a new term entry on the .scatter_3d() method of the express in the path docs/content/plotly/concepts/express/terms/scatter_3d under the file name scatter_3d.md 

### Issue Solved

Closes #5169

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by cigar-galaxy82** [comment]
Hi @pritamjr thank you for contributing to Codecademy docs, I have suggested a few changes please modify them and change the folder and the file name to [scatter-3d/scatter-3d.md

**Review by cigar-galaxy82 — CHANGES_REQUESTED** [review]

**Comment by mamtawardhani** [comment]
@pritamjr are you still working on this?
If you do not revert back within the next 3 days, I'll have to unassign you and close this PR

**Comment by mamtawardhani** [comment]
@Sriparno08 I was planning to make the changes by myself, as I think since this issue is old, we can close it. However, this PR has the `scatter.md` file as well, how should I proceed here, please help

**Comment by Sriparno08** [comment]
Hey @mamtawardhani, you can do one thing. You can copy the contents from the `scatter.md` file in the main branch to the `scatter.md` file in the PR branch. This way, the `scatter.md` file will most probably vanish from the 'Files changed' tab.

**Review by mamtawardhani — APPROVED** [review]
Thank you for contributing to Codecademy Docs @pritamjr 😄 

The entry looks good for a second round of review 🚀

**Review by Sriparno08 — APPROVED** [review]
Looks good, @pritamjr!

**Pull request merged**
