### PR TITLE
Updated file path with a new section

### PR DESCRIPTION
**Pull request by javastudent2133**
### Description

Added a section to show how to link stylesheets and javascript to HTML file and file path if required.
Style sheets and Javascript code are the last to bullets described at the top of this file.

### Type of Change

- Adding a new section.
- Editing an existing entry, updated the first mention of 'file path'.

### Checklist

- [x ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by javastudent2133** [comment]
Good morning. Since this is my first time, I just wanted to check if anything is required of me at this time or if I am just waiting for my changes to be reviewed. Is there anything I could have done better as far as git and github, branches and how I committed and pushed my changes? 
Thank you,

**Comment by SSwiniarski** [comment]
@javastudent2133 Nothing is required of you. We just have to review your changes.

**Comment by SSwiniarski** [comment]
@KTom101, @caupolicandiaz What's your opinion of this edit? My thought is that it strays from the topic of the entry a little too much.

**Comment by caupolicandiaz** [comment]
> @KTom101, @caupolicandiaz What's your opinion of this edit? My thought is that it strays from the topic of the entry a little too much.

I agree that is not quite in line with the rest of the entry. It feels like an add on. Also, this ground is covered in the links entry.

**Comment by SSwiniarski** [comment]
@javastudent2133 we reviewed your entry and have decided that your edit is not in line with the rest of the entry, and is duplicitive of other entries that cover the same ground. I'm afraid we're going to close it.

**Pull request closed without merging**
