### PR TITLE
correct typo in code example

### PR DESCRIPTION
**Pull request by ootwither**
Example 1 was 'console.log('hello world'.toLowerCase()); but this is the toUpperCase page; corrected.

### Description

fixed typo in a code example at https://www.codecademy.com/resources/docs/javascript/strings/toUpperCase

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — APPROVED** [review]
@ootwither looks good for second review.

**Comment by ootwither** [comment]
Hi @SSwiniarski this is the first time I've done anything like this; do I need to do anything else or do I wait for someone else with authority to have a look?

**Comment by SSwiniarski** [comment]
> Hi @SSwiniarski this is the first time I've done anything like this; do I need to do anything else or do I wait for someone else with authority to have a look?

@ootwither you don't need to do anything. Our policy is just to have two maintainers look over each PR. The next maintainer will probably just take a look and merge this, as it's just a small typo.

**Review by yangc95 — APPROVED** [review]

**Comment by yangc95** [comment]
Good eye 🙌 @ootwither thanks for spotting this!

edits will be live here: https://www.codecademy.com/resources/docs/javascript/strings/toUpperCase

Feel free to head over to the [Issues tab]([https://github.com/Codecademy/docs/issues](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+no%3Aassignee)) to claim any available issues you're interested in! If no issue is compatible and you wish to discuss other potential topics/concepts, feel free to leave a comment in the [Forums: Find a Starting Point](https://discuss.codecademy.com/t/find-a-starting-point-possible-content-discussion/745868).
Thanks for your contribution!

cc: @SSwiniarski

**Pull request merged**
