### PR TITLE
Proof edits

### PR DESCRIPTION
**Pull request by noahpgordon**
### Description

Edited the file proofs.md.

Changes made:

-Fixed some inaccuracies about the concepts of proofs and conjectures.
-Reorganized and clarified the discussion of mathematical induction.
-Included example in explanation of induction.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — APPROVED** [review]
@noahpgordon Looks good for a second review.

**Comment by noahpgordon** [comment]
I've made a small change to proofs.md since the first review was done. Should I submit a new pull request, wait for this one to complete, or somehow modify this pull request? This is my first pull request and I am unsure about the workflow for this.

**Comment by SSwiniarski** [comment]
> I've made a small change to proofs.md since the first review was done. Should I submit a new pull request, wait for this one to complete, or somehow modify this pull request? This is my first pull request and I am unsure about the workflow for this.

@noahpgordon please just update this PR. Commits to this branch will show up here.

**Comment by noahpgordon** [comment]
> > I've made a small change to proofs.md since the first review was done. Should I submit a new pull request, wait for this one to complete, or somehow modify this pull request? This is my first pull request and I am unsure about the workflow for this.
> 
> @noahpgordon please just update this PR. Commits to this branch will show up here.

I did this.

**Review by yangc95 — APPROVED** [review]
@noahpgordon big improvement!

**Pull request merged**
