### PR TITLE
[Edit] General (Reorganization): Design Patterns

### PR DESCRIPTION
**Pull request by yangc95**
### Description

Added design patterns entry and moved all design patterns in the General section under the newly created folder.

Todo: Fix links if any

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by Dusch4593** [comment]
I wasn't sure how we were going to write the `design-patterns.md` entry but I replaced the old links for each `-pattern` in the `creational-design-patterns` file. (ce3610a374536ad0a47f58b1fa3a940717cc32f1) 😄

**Comment by yangc95** [comment]
> @yangc95 I wasn't sure how we were going to write the `design-patterns.md` entry but I replaced the old links for each `-pattern` in the `creational-design-patterns` file. ([ce3610a](https://github.com/Codecademy/docs/commit/ce3610a374536ad0a47f58b1fa3a940717cc32f1)) 😄

@Dusch4593 I'm still contemplating on the best way to structure this concept. There are three types of design patterns I thought we should cover which are industry-standard. Behavioral, creational (which we have), and structural.

We could outline all three in the main `design-pattern.md`, but that would mean the terms would get mixed up in which case we could keep the bulleted list of each design pattern's main patterns.

In any case it would be good to have this hierarchy of info (design patterns > behavioral/creational/structural > singleton/builder/etc + adapter/facade/etc + etc)

Wondering if you think there may be a good way to handle this. TY in advance for your input!

cc: @KTom101 @SSwiniarski

**Comment by KTom101** [comment]
> > @yangc95 I wasn't sure how we were going to write the `design-patterns.md` entry but I replaced the old links for each `-pattern` in the `creational-design-patterns` file. ([ce3610a](https://github.com/Codecademy/docs/commit/ce3610a374536ad0a47f58b1fa3a940717cc32f1)) 😄
> 
> @Dusch4593 I'm still contemplating on the best way to structure this concept. There are three types of design patterns I thought we should cover which are industry-standard. Behavioral, creational (which we have), and structural.
> 
> We could outline all three in the main `design-pattern.md`, but that would mean the terms would get mixed up in which case we could keep the bulleted list of each design pattern's main patterns.
> 
> In any case it would be good to have this hierarchy of info (design patterns > behavioral/creational/structural > singleton/builder/etc + adapter/facade/etc + etc)
> 
> Wondering if you think there may be a good way to handle this. TY in advance for your input!
> 
> cc: @KTom101 @SSwiniarski

@yangc95 IMO, I think outlining them in the main design-patterns.md may be a little much. I think it should just focus on explaining design patterns in general but the types could be mentioned and linked out to their own entries.

**Comment by yangc95** [comment]
@KTom101 @Dusch4593 I'm closing this PR out for now as we're confirming a workflow for these reorganization efforts in making sure contributors are not removed from the entries.

**Pull request closed without merging**
