### PR TITLE
Remove HTML trailing slashes

### LINKED ISSUE #447: [Bug/Error] HTML Trailing Slashes : Best practice to not include XHTML-style trailing slashes in the HTML docs.
### Type of Edit (select all that apply)

Clarify unclear content and/or terms

### Description (optional)

According to [MDN HTML Guidelines](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/HTML#trailing_slashes), 

> Don't include XHTML-style trailing slashes for empty elements, as they are unnecessary and slow things down. They can also break old browsers if you are not careful (although from what we can recall, this hasn't been a problem since Netscape 4).

It's only a matter of style, but removing the trailing slashes improves the clarity and consistency of the code - especially since they are not referenced in the curriculum. 

The pages where I have found trailing slashes include:
- [Attributes](https://www.codecademy.com/resources/docs/html/attributes)
- [Forms](https://www.codecademy.com/resources/docs/html/forms)
- [Images](https://www.codecademy.com/resources/docs/html/images)
- [Links](https://www.codecademy.com/resources/docs/html/links)
- [Videos](https://www.codecademy.com/resources/docs/html/videos)

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by SSwiniarski**
### Description

From the Issue in question:

> According to [MDN HTML](https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/HTML#trailing_slashes) Guidelines,
> 
> Don't include XHTML-style trailing slashes for empty elements, as they are unnecessary and slow things down. They can also break old browsers if you are not careful (although from what we can recall, this hasn't been a problem since Netscape 4).

I've gone through everything under HTML and removed the trailing slashes.

Closes #447 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by SSwiniarski** [comment]
Hmm, @Dusch4593, @yangc95, the format:verify check doesn't like the lack of trailing slashes. We might not be able to merge this.

**Comment by SSwiniarski** [comment]
Hmm, @Dusch4593, @yangc95, the format:verify check doesn't like the lack of trailing slashes. At least when I ran yarn format, it put the slashes back. We might not be able to merge this.

**Comment by Dusch4593** [comment]
> Hmm, @Dusch4593, @yangc95, the format:verify check doesn't like the lack of trailing slashes. At least when I ran yarn format, it put the slashes back. We might not be able to merge this.

Whoa super weird. I just tested it out locally and you're right, Prettier seems to prefer those trailing slashes. Before we consider closing this PR/Issue, since this deals with a tooling issue, I wanted to cc: @christian-dinh's take. 

[The original issue](https://github.com/Codecademy/docs/issues/447) brought up an interesting point about how trailing slashes aren't even used in the curriculum. Can the prettier rule be changed to accept a lack of trailing slashes? Or is this not urgent enough to pursue right now?

**Comment by christian-dinh** [comment]
There has been [a lot of discussion](https://github.com/prettier/prettier/issues/5246) about this in the prettier repo and they're pretty adamant about not adding an option for it. Trailing slashes on void elements are valid in HTML 5 so any style guide saying not to use them is doing so for purely stylistic reasons unless they need to support HTML 4 (which is probably pretty rare) or _really_ need to keep the code slim (in which case a minifier is probably taking care of it for them).

I think it's probably worth noting in `content/html/concepts/elements/elements.md` that...
- some elements, like `input`, `img`, `br`, etc are void elements (aka "empty" elements in the current description, elements that can never have children)
- void elements can optionally be self-closing (ie have a trailing slash) and it's pretty much up to personal preference

there is also a caveat that making all void elements self-closing improves compatibility with XHTML, not sure if that's worth mentioning or not.

**Comment by yangc95** [comment]
> there is also a caveat that making all void elements self-closing improves compatibility with XHTML, not sure if that's worth mentioning or not.

I think that last point is worth mentioning along with a note in the appropriate file -- maybe the note in [elements](https://www.codecademy.com/resources/docs/html/elements) can be adjusted to include these points.

**Comment by Dusch4593** [comment]
Closing this PR for now but will take not of [@yangc95's comment](https://github.com/Codecademy/docs/pull/533#issuecomment-1027917357) for a future edit in HTML: Elements.

**Pull request closed without merging**
