### PR TITLE
Removed the duplicate file. This should only be present in serialization.

### PR DESCRIPTION
**Pull request by dakshdeepHERE**
### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by ishg-153 — APPROVED** [review]
Looks good for a second review!

**Comment by ishg-153** [comment]
Hey @dakshdeepHERE! Can you confirm if we still need to merge this? I don't see the `encodeToString` folder in `datetime`.

**Comment by dakshdeepHERE** [comment]
@ishg-153 maybe you haven't updated the local repo. Check [here](https://github.com/Codecademy/docs/tree/main/content/kotlin/concepts/datetime/terms/encodeToString) the file is present here. The author changed the file to right dir but forgot to remove this file which was present under datetime. I also missed that the author haven't deleted the file here.

**Comment by dakshdeepHERE** [comment]
See it is present [here](https://github.com/Codecademy/docs/tree/main/content/kotlin/concepts/serialization/terms/encodeToString) too

**Review by SSwiniarski — APPROVED** [review]
@dakshdeepHERE Looks good.

**Pull request merged**
