### PR TITLE
Fix Swift UI View Modifier .bold() tag

### PR DESCRIPTION
**Pull request by gracekishino**
### Description

Change tag 'SwiftUI Modifiers' to 'SwiftUI ViewModifiers'.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — APPROVED** [review]
@gracekishino looks good to merge as is.

**Review by SSwiniarski — CHANGES_REQUESTED** [review]
@gracekishino Actually, one change needed: "ViewModifiers" needs to be added in the tags.md file under documentation.

**Comment by gracekishino** [comment]
> @gracekishino Actually, one change needed: "ViewModifiers" needs to be added in the tags.md file under documentation.

@SSwiniarski Thanks for merging! "[Swift UI ViewModifiers](https://github.com/Codecademy/docs/blob/main/documentation/tags.md#:~:text=SwiftUI%20ViewModifiers)" is already in there, shall I add just "ViewModifier" as well?

**Comment by SSwiniarski** [comment]
@gracekishino if "Swift UI ViewModifiers" is in the tags list, use that for this instead.

**Review by SSwiniarski — APPROVED** [review]

**Pull request merged**
