### PR TITLE
Found a Way Out of Vim 🧙 

### PR DESCRIPTION
**Pull request by Dusch4593**
### Description

Every entrance must have an exit!

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by christian-dinh** [comment]
might be worth specifying that this will discard changes, while `:wq` will save + quit

**Comment by Dusch4593** [comment]
> might be worth specifying that this will discard all changes, while `:wq` will save the current buffer + quit

Super fair point. I personally use `:qa!` (for some reason?) even though I am not running multiple buffers(?)

Should we also mention that and `:xa` (which does what I do and what you're recommending) just to cover our bases?

**Review by SSwiniarski — APPROVED** [review]
Looks good to me as is.

**Comment by Dusch4593** [comment]
Nice nice! Anything we should add or check @KTom101?

**Review by KTom101 — APPROVED** [review]
@Dusch4593 Looks good! I don't see anything that needs to be added or changed.

**Pull request merged**
