### PR TITLE
add control-flow.md

### PR DESCRIPTION
**Pull request by DianaWMD**
### Description

Added a control-flow.md file into the general content docs folder
[control flow issue# 2211](https://github.com/Codecademy/docs/issues/2211#issue-1717710582)
currently working on my git skills and a codecademy entry project satisfies its requirements

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by KTom101** [comment]
@DianaWMD The file seems to be empty, were you meaning to draft this?

**Comment by DianaWMD** [comment]
> @DianaWMD The file seems to be empty, were you meaning to draft this?

I realized it was empty after the fact, was really upset about it but had to leave right away.
I might have to try again, how much time before I can submit work?

**Comment by KTom101** [comment]
@DianaWMD It's alright, I just wanted to make sure you were aware. Submit as soon as you can so we can begin the review process.

**Comment by SSwiniarski** [comment]
@KTom101 I added the invalid tag until this is fixed.

**Comment by KTom101** [comment]
@DianaWMD I see you closed this out. Have you decided to create a new PR? Let us know if you need help with anything. 😄

**Comment by KTom101** [comment]
@DianaWMD I see that you did here: https://github.com/Codecademy/docs/pull/2285 Thanks!

**Pull request closed without merging**
