### PR TITLE
Add Media to Link Branch

### PR DESCRIPTION
**Pull request by nsLittle**
### Description

Submitting my first contribution to Codecademy's Doc as part of the Git & GitHub syllabus.  Made additions to an existing entry, `Links`.

### Type of Change

- Addition to an existing entry
- How to add media
- Updating the documentation

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [  ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by KTom101** [comment]
@nsLittle You need to change this PR to what is being asked in the [issue](https://github.com/Codecademy/docs/issues/3231) you're assigned to. It is asking you to add images showing what the example would look like if they were rendered.

The additional content you added is unnecessary since there are separate entries for those topics.

**Comment by KTom101** [comment]
@nsLittle We're specifically looking for images of the existing examples. The added content on media should be removed since these are covered elsewhere on the site. 

If you're still confused, look at the entries for those and how the examples have images showing what it would look like when rendered. For example, in the [Image entry](https://www.codecademy.com/resources/docs/html/images) and [Audio entry](https://www.codecademy.com/resources/docs/html/elements/audio), you can see where an image is added immediately after the examples at the end of those entries.

**Comment by nsLittle** [comment]
Images added.  Extraneous content deleted.  Apologies for the continued misunderstanding.

**Comment by KTom101** [comment]
@nsLittle Did you push your changes yet? I do not see anything different.

**Comment by SSwiniarski** [comment]
@nsLittle If we don't see any changes to this PR we'll have to close the PR and unassign the issue.

**Comment by nsLittle** [comment]
My apologies.  I did get frustrated with pull and push issues not working
and got side tracked.  May I have another week to resolve this?

**Comment by SSwiniarski** [comment]
@nsLittle yes, but in a week we'll close this.

**Comment by KTom101** [comment]
@nsLittle Hi, I'm just checking in to see if there is anything we can help with.

**Pull request closed without merging**
