### PR TITLE
renerepina-patches

### PR DESCRIPTION
**Pull request by renerepina**
### Description

Currently I am learning  "Computer Science" path and I am currently learning about Python. While reading the documentation and code, I have encountered several mistakes, which I corrected. The list is below.

- content/python/concepts/casting/casting.md → Description is already in the commit. The sentence should be removed OR use "codebyte" that allows user input otherwise it will create an error (as it does now).
- content/python/concepts/data-types/data-types.md → Fixed comment typo.
- content/python/concepts/built-in-functions/terms/list/list.md → Missing "f" for format in the code, causing wrong output, fixed.
- content/python/concepts/iterators/iterators.md → Fixed typos. Wrong words were used. Removed whitespace and added whitespaces in the code for better consistency and readability of the code.
- Two merges applied from "main" branch. → Just to be on updated version.

P.S.:
I am contributing and doing pull request for the first time. Sorry, if I missed anything and will be glad for any information / feedback.
- [x] I left "My changes generate no new warnings." unchecked, since it is probably connected to "workflow check runs", which I can not perform as a first timer.

### Type of Change

 

- ~~Adding a new entry~~
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — APPROVED** [review]
@renerepina Looks good. Sending this straight to a second review.

**Review by yangc95 — APPROVED** [review]

**Comment by yangc95** [comment]
@renerepina looks good to me as-is!

**Comment by renerepina** [comment]
@SSwiniarski @yangc95 
Thank you both for checking!

@yangc95 
1. I saw that I had to update the branch, but I was caucious, because I did not know, if I can do that while you guys "review" (sorry, I am newbie 😅).
2. I updated the branch and it is waiting for "check". I can not do them, since I do not have "write access".
3. Can you additionally explain your statement "There's some hints below under "command line instructions""? I am not sure where to look. Thank you!

**Comment by yangc95** [comment]
@renerepina great questions!

1. You can update your branch at any time. It will merge in any updates from the `main` branch into your PR's branch.
2. Maintainers approve the tests to be run, after which you'll be able to double-check that the tests are passing!

I mis-wrote about that last one, apologies! I'd recommend just updating through the button when you can. The other option is to update it through your command line, which I can discuss here if you would like more context.

**Comment by renerepina** [comment]
@yangc95 

1. Thank you for the explanation! I am really grateful for that!
2. Understandable.
3. No worries! Yes, I did it via button. I did not use "Command Line" yet, so every additional information would be great! You mean "GitHub CLI"?

And thank you for merging! Quite a feeling when contributing toward such platform and for the first time! ^^

**Comment by yangc95** [comment]
@renerepina no prob! The GitHub CLI is referring to the `gh` command of which you can install (see: https://cli.github.com). It's not a requirement but I do find it can quicken your workflow.

I was referring to your terminal or command line on your computer.

Also, I know the feeling all too well! Here's the live links for where the edits will appear:
Python: Built-in Functions: [list()](https://www.codecademy.com/resources/docs/python/built-in-functions/list), [Casting](https://www.codecademy.com/resources/docs/python/casting), [Data Types](https://www.codecademy.com/resources/docs/python/data-types), [Iterators](https://www.codecademy.com/resources/docs/python/inheritance)

**Comment by renerepina** [comment]
@yangc95 
Ah! Thank you for the suggestion, I will look into it. I do not have experience with command lines yet. Is "Git" similiar to "GH"?
Hmm. I do not have that on my PC (yet). 😅
Yes! And thank you for the links! (P.S.: I admit I could not wait, so I even checked them before already hh.)
I am monitoring those issues, but unfortunately I do not have any experiences in currect issue that I would be able to contribute. Maybe in future in something pops-up. As for similiar PR as this, I will make sure to make them, if I found something. ^^

**Pull request merged**
