### PR TITLE
Create bit-functions.md

### PR DESCRIPTION
**Pull request by Alexa86**
add bit functions markdown file

### Description

Add bit functions markdown file.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by Alexa86 — COMMENTED** [review]
removed spaces & extra empty rows
added `` at each bit function (syntax section)
added more details at examples section for clarity

**Comment by ishg-153** [comment]
@Alexa86 You've added this entry in `content/mysql/concepts/bit-functions.md` can you please change its directory to `content/mysql/concepts/bit-functions/bit-functions.md`.

Once you do this I will suggest a batch of changes.

**Comment by Alexa86** [comment]
Hello, I have no idea how to push the change with the new directory.
Is created now unde the right bit-function folder (link: content/mysql/concepts/bit-functions/bit-functions.md)

 all looks fine but here I do not find a way to publish the change. I tried Github desktop and here in the browser. I wonder if I can delete everything and start again. I am completely lost in the branches. Apologies for the troubles..

**Comment by Alexa86** [comment]
restart work on this one, sorry

**Pull request closed without merging**
