### PR TITLE
Create basic-syntax.md

### PR DESCRIPTION
**Pull request by ebube-tech**
This includes standardized details of the Kotlin Language syntax to be observed. Readers of this file would learn how to declare a function, class, variable, constant, and object in Kotlin.

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by SSwiniarski** [comment]
@ebube-tech I'm going to ask the other maintainers, @Dusch4593, @yangc95, @KTom101, if this is appropriate for docs. It seems to me that this is largely redundant with other entries we have or will have on functions, variables, classes etc.

**Comment by KTom101** [comment]
> @ebube-tech I'm going to ask the other maintainers, @Dusch4593, @yangc95, @KTom101, if this is appropriate for docs. It seems to me that this is largely redundant with other entries we have or will have on functions, variables, classes etc.

@SSwiniarski I'm not opposed to this being repurposed as a general concept on syntax while including a more generalized example instead of the Kotlin examples. 

We currently have PRs open for [variables](https://github.com/Codecademy/docs/pull/1437) and [classes](https://github.com/Codecademy/docs/pull/1421) which would cover the syntaxes for classes, variables, and constants in Kotlin.  But since there is nothing open for function and object (correct me if I'm wrong), those examples could be reworked into their own concept entries for Kotlin.

**Comment by Dusch4593** [comment]
cc: @KTom101 @SSwiniarski

@ebube-tech Here's what I would suggest for this matter. Instead of this being about syntax, why don't we use this PR to create two new concept entries about functions and objects in Kotlin (as mentioned by @KTom101)? Neither of these concepts seem to be in production, currently.

The file paths would look like this:

~`content/kotlin/concepts/basic-syntax.md`~ --> `content/kotlin/concepts/functions/functions.md` & `content/kotlin/concepts/objects/objects.md`

Each file should at least have the following:

- A "Syntax" section with a \```pseudo code snippet.
- An "Example" section with a \```kotlin code snippet.

**Comment by ebube-tech** [comment]
@Dusch4593 Noted. I'll implement the changes right away.

**Comment by SSwiniarski** [comment]
@ebube-tech Have you worked on the suggestions above? If you're no longer working on this PR, we can close it.

**Comment by yangc95** [comment]
@SSwiniarski 

I've created two issues branching off this discussion here:

- https://github.com/Codecademy/docs/issues/1689
- https://github.com/Codecademy/docs/issues/1688

@ebube-tech Feel free to pick one of these up and thanks for brainstorming this one out with us!

**Pull request closed without merging**
