### PR TITLE
[Edit] Lua Strings .char() typo

### PR DESCRIPTION
**Pull request by SSwiniarski**
### Description

Edit the title of `.char()` to include the leading period like the other Lua string functions.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by KTom101 — CHANGES_REQUESTED** [review]
@SSwiniarski I'm noticing the first example looks copied from [here](https://www.tutorialspoint.com/string-char-function-in-lua-programming). Can we change it up while we have this open?

**Comment by SSwiniarski** [comment]
@KTom101 I went ahead and changed the example. How's it look now?

**Review by KTom101 — APPROVED** [review]
@SSwiniarski LGTM, since we changed the example we can give this one more review.

**Review by caupolicandiaz — APPROVED** [review]
@SSwiniarski @KTom101 LGTM

**Pull request merged**
