### PR TITLE
sql-function-ceiling

### LINKED ISSUE #2217: [Term Entry] SQL Math Functions CEILING
### Reason/inspiration (optional)

We would like a new term entry for the Math Function, `CEILING`, in SQL.

The entry should go in a file in docs/content/sql/concepts/math-functions/terms/ceiling/ceiling.md

The entry should: 

- Explain what the math function `CEILING` is in SQL and what it’s used for, starting with an introductory paragraph (2-3 sentences).
- Include SQL database compatibility as a note.
- Links out to entries as needed.

Please refer to the [entry templates (term entry template in particular)](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by nikolaspoczekaj**
### Description

Hi, thanks for assigning me. This closes #2217 .

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by caupolicandiaz — APPROVED** [review]
@nikolaspoczekaj Looks good, just added one small edit. This is ready for a second review.

**Review by SSwiniarski — CHANGES_REQUESTED** [review]
@nikolaspoczekaj I did a second review and had one comment.

**Comment by nikolaspoczekaj** [comment]
okay, did that. @SSwiniarski

**Review by SSwiniarski — APPROVED** [review]
@nikolaspoczekaj Looks good to merge!

**Comment by SSwiniarski** [comment]
@nikolaspoczekaj Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/sql/math-functions/ceiling

image

**Pull request merged**
