### PR TITLE
[Term Entry] Dart List .contains()

### LINKED ISSUE #4295: [Term Entry] Dart List .contains()
### Reason/inspiration (optional)

We would like a new term entry under Dart [List](https://www.codecademy.com/resources/docs/dart/concept/list) for the Dart List .contains()` method. 
Provide the entry in a markdown file under `docs/content/dart/concept/list/terms/contains/contains.md`

The entry should
    - Have an introductory paragraph about what the method is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - An example showing the method in use.

Please refer to the [concept entry templates](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by irynakanst**
### Description

- Added the List .contains() term for Dart

### Issue Solved

Closes #4295 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by Helfese — APPROVED** [review]

**Review by Sriparno08 — COMMENTED** [review]
Hey @irynakanst, thanks for contributing to Codecademy!

I've listed all the modifications that you need to make in your entry below:

**Comment by irynakanst** [comment]
Hi @Sriparno08 , all issues were fixed. Please check.

Thank you!

**Review by Sriparno08 — APPROVED** [review]
Good job, @irynakanst 👍

This looks good for a second review.

**Review by avdhoottt — APPROVED** [review]
LGTM!!

**Pull request merged**
