### PR TITLE
updated typo

### PR DESCRIPTION
**Pull request by binarystarr**
### Description

small typo fixed

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by Dusch4593** [comment]
Hey, @binarystarr I edited your PR form a bit so that the checkboxes are actually "checked" (8/8) and it's reflected on the PR dashboard.

**Review by Dusch4593 — APPROVED** [review]
LGTM! Good catch!

**Comment by sonnynomnom** [comment]
Hi @binarystarr! One last thing left: the CLA. Ping us once you signed the CLA and I can merge!

**Review by sonnynomnom — APPROVED** [review]

**Review by EugeneGohh — APPROVED** [review]

**Comment by sonnynomnom** [comment]
Because it's just one character. I'm going to squash and merge.

**Comment by sonnynomnom** [comment]
Congrats on your first PR to Codecademy Docs! Let us know if you find anymore typos.

**Pull request merged**
