### PR TITLE
Get utc full year issue

### PR DESCRIPTION
**Pull request by light-roast**
@caupolicandiaz and @SSwiniarski already revie this file. Changes applied.

### Description
getUTCFullYear folder  created in the specified path: docs/content/javascript/concepts/dates/terms/
Inside the folder you can find the getUTCFullYear.md file

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by SSwiniarski** [comment]
@light-roast Congrats on your new entry. Live link here: https://www.codecademy.com/resources/docs/javascript/dates/getUTCFullYear

You're currently listed as an anonymous contributor. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.

image

To add your GitHub username to your Codecademy profile:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

image

2.) Make sure to set your visibility to “everyone”:

image

3.) Then log out and log back into Codecademy using your GitHub login:

image

**Note**: Your email used for Codecademy will have to be listed in your GitHub profile for the login feature to properly work. If you use the same email for both GitHub and Codecademy already, then you're set.

In addition, we may reach out in the future if any adjustments to these entries are required.

**Comment by light-roast** [comment]
I meet all the requirements you mentioned. What else do I have to do.

**Comment by SSwiniarski** [comment]
@KTom101, @yangc95, @caupolicandiaz Any idea why @light-roast is still anonymous?

**Comment by yangc95** [comment]
@light-roast Can you confirm that the email you're using for Codecademy and GitHub are either the same or linked?

**Comment by light-roast** [comment]
They both use the same email: echeverri121@gmail.com

**Comment by yangc95** [comment]
@light-roast Could you also link me to your Codecademy profile?

**Pull request merged**
