### PR TITLE
[Term Edit] Update count.md to use correct syntax of count() for Lists

### PR DESCRIPTION
**Pull request by hitesh-gitdev**
### Description

Python Lists' count method uses just one parameter - value. Start and End are not applicable for List count method. 

Using Start and End parameters in the method results in the following error in Example 2 - 

```
# Output: 2
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    numPen = backpack.count('pen', 0, 5)
TypeError: count() takes exactly one argument (3 given)
```

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by caupolicandiaz — APPROVED** [review]
@hitesh-gitdev I've added a couple of additional changes. Passing this on for a second review.

**Comment by hitesh-gitdev** [comment]
Thanks @caupolicandiaz! I'll try to be more thorough with my changes next time.

**Review by SSwiniarski — APPROVED** [review]
@hitesh-gitdev Looks good to merge

**Comment by SSwiniarski** [comment]
@hitesh-gitdev Congrats on the new edit.

Live link:
-https://www.codecademy.com/resources/docs/python/lists/count

**Pull request merged**
