### PR TITLE
Python math.degrees()

### PR DESCRIPTION
**Pull request by colinlsmatthews**
### Description

- ~Created two new docs entries for the functions `math.radians()` and `math.degrees()` in the built-in `math` module for Python.~
- EDIT: Remove entry for math.radians(). Will submit as a separate PR
- Added one image to the media folder:
`media\radian-measure-45-degree-rotations-256.png`

### Issues Solved

~5035 [Term Entry] Python math-module math.radians()~
#5036 [Term Entry] Python math-module math.degrees()

### Type of Change

- Adding a new entry
- ~Editing an existing entry (fixing a typo, bug, issues, etc)~
- ~Updating the documentation~

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by mamtawardhani** [comment]
Hey @colinlsmatthews you need to create separate PR for every issue, keep one file in this PR and raise another file for the other issue. Once done let me know 😄

**Comment by colinlsmatthews** [comment]
Hey @mamtawardhani, I've removed the entry for math.radians and will submit as a separate PR.

**Comment by mamtawardhani** [comment]
Hey @colinlsmatthews this entry consists of 8 files, could you please remove the other files from this branch and only keep the `math-degrees.md` file

**Comment by colinlsmatthews** [comment]
> Hey @colinlsmatthews this entry consists of 8 files, could you please remove the other files from this branch and only keep the `math-degrees.md` file

I've removed most of the extra files. However [media/radian-measure-45-degree-rotations-256.png](https://github.com/Codecademy/docs/pull/5039/files#diff-2551bf0f9a37e1c64d2f7597b4be7284bc8da8e68caa79e197636f3d75f7a358) is actually referenced in the new entry for both `math.degrees()` and `math.radians()`, so I've left it in there for now.

**Review by mamtawardhani — APPROVED** [review]
Thank you for your contribution to Codecademy Docs @colinlsmatthews, the entry is nicely written 😄 

It looks good for a second round of review! 🚀

**Review by Sriparno08 — APPROVED** [review]
Looks good, @colinlsmatthews! 👍

**Pull request merged**
