### PR TITLE
Update emphasis.md

### PR DESCRIPTION
**Pull request by lucwhite**
### Description

Fixed repetitious markdown, added what examples look like when not in codeblocks, corrected avocado spelling

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating documentation

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by lucwhite** [comment]
@Dusch4593 The changes made by prettier were actually the point of this PR. They revert the changes I made.

**Comment by Dusch4593** [comment]
> @Dusch4593 The changes made by prettier were actually the point of this PR. They revert the changes I made. If we can't merge without prettier then we should take those lines out, not let them be changed to be identical to the lines above.

Gotcha. I prefer the checks to pass before merge. If you're changes seem contrary to the Prettier config (I think?) should that be adjusted? Either way, I can just reset/revert back to your changes for now when I'm back at keyboard. Sorry about that.

**Comment by lucwhite** [comment]
> Gotcha. I prefer the checks to pass before merge. If you're changes seem contrary to the Prettier config (I think?) should that be adjusted? Either way, I can just reset/revert back to your changes for now when I'm back at keyboard. Sorry about that.

Understood, then I'll eliminate the lines that conflict with the prettier config and recommit.

**Review by Dusch4593 — APPROVED** [review]
LGTM! 👍

**Pull request merged**
