### PR TITLE
Branch issue 5074

### PR DESCRIPTION
**Pull request by Maheshwaran17**
### Description

Added a new entry about linear regression for sklearn content.

### Issue Solved

Closes the issue 5074

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by mamtawardhani** [comment]
Hey @Maheshwaran17 this issue doesn't exist yet, let me check this once.

@Sriparno08 should we create an issue for this, or do we need a concept entry before this? Could you please check the path and confirm this?
Thank you 😃

**Comment by Sriparno08** [comment]
Hey @mamtawardhani, the issue for 'Linear Regression' (or 'Linear Regression Analysis') is already created (#4823) and assigned to another contributor. So, I think we can close this one.

**Comment by mamtawardhani** [comment]
> Hey @mamtawardhani, the issue for 'Linear Regression' (or 'Linear Regression Analysis') is already created (#4823) and assigned to another contributor. So, I think we can close this one.

Oh my bad, didn't see it. Alright closing this PR

Hey @Maheshwaran17 closing this PR since the issue regarding `Linear Regression` ([#4823](https://github.com/Codecademy/docs/issues/4823)) is already taken by some other author. For future references, make sure you raise a PR only after you've been assigned to an issue. Thank you 😃

**Comment by Maheshwaran17** [comment]
@mamtawardhani Sure Thank you!

**Pull request closed without merging**
