### PR TITLE
Review changes issue 4150

### PR DESCRIPTION
**Pull request by bpicoCode**
### Description
- Adding Review Changes
- Adding Codebyte for .getUTCHours() entry
- Closes issue #4150  

### Type of Change
- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by bpicoCode** [comment]
@dakshdeepHERE Hi, so here is the new pull request. The CLA is still linking the old commits to the new pull request. Not sure where to go from here.

**Comment by dakshdeepHERE** [comment]
@bpicoCode onc check is the email that you are using locally and this github account are on same emails.

**Comment by dakshdeepHERE** [comment]
Use this command `gh config get -l | grep user.email`

**Review by dakshdeepHERE — APPROVED** [review]
LGTM 🚀

**Comment by dakshdeepHERE** [comment]
@bpicoCode let me know what you hace decided about the CLA issue. I have moved their forward to second review.

**Comment by bpicoCode** [comment]
> @bpicoCode let me know what you hace decided about the CLA issue. I have moved their forward to second review.

I'm not sure it is possible to unlink that commit from any pull request related to this branch.

**Comment by ishg-153** [comment]
Hey @bpicoCode! I'd suggest you use `cherry-pick`. 

Make sure to create a new branch from the main branch and then `cherry-pick` only the commits that you made add or make changes to the `content/javascript/concepts/dates/terms/getUTCHours/getUTCHours.md` file. Before creating the new branch make sure that your remote and local repos are up-to-date and you have a clean working tree to avoid any issues.

After that create a new PR from that branch. Let me know once you are done so that I can close down this PR.

Now if you want to clean your working tree you can go ahead and delete `review-changes-issue-4150` branch (only do this if cherry-pick works and do it after you create a new PR from the new branch).

**Comment by ishg-153** [comment]
Closing this PR as a new one was successfully made.

**Pull request closed without merging**
