### PR TITLE
Python Plotly > FIgure_Factory > create_distplot() new entry

### LINKED ISSUE #4723: [Term Entry] Python Plotly - Figure_factory .create_distplot()
### Reason/inspiration (optional)

We would like a new term entry on the '.create_distplot()' method for the `Plotly` library in Python. The entry should go in a new file under `docs/content/plotly/concepts/figure-factory/terms/create-distplot/create-distplot.md`

The entry should include the following:

- A description of the function
- A Syntax section that includes the syntax of the function and its details
- An Example section that includes a ```python ``` codeblock and ```shell ``` that shows the example output.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by kennyotani**
### Description

I created a term entry for the plotly > figure_factory > create-distplot() method, as I am a codecademy student and this is my first time contributing to codecademy and making a github pull request! I added files C:\Users\kotani\docs\content\plotly\concepts\figure-factory\terms\create-distplot\create-distplot.md and C:\Users\kotani\docs\media\ff_distplot_example.png

### Issue Solved

Closes #4723 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by mamtawardhani** [comment]
> [CLA assistant check](https://cla-assistant.io/Codecademy/docs?pullRequest=4780) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4780) before we can accept your contribution.
> 
> **Kenny** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4780) it.

Hey @kennyotani, could you please sign the CLA? It seems like when you pushed the commits, you were not signed into your GitHub account. Please check these instructions?

**Comment by kennyotani** [comment]
I just signed the CLA after signing in, hopefully that worked as intended. Thanks.

**Comment by mamtawardhani** [comment]
> I just signed the CLA after signing in, hopefully that worked as intended. Thanks.

Hey @kennyotani, as you mentioned that you've signed the cla, could you please try pushing some minor changes, lets see if the CLA status changes. Thank you 😃

**Comment by mamtawardhani** [comment]
Hey @kennyotani! I would suggest you to configure your git and then go ahead and raise another PR, since it still shows that the CLA is not signed. 

```
git config user.email
git config [user.name](http://user.name/)
```

If these are not configured, please set them using the commands below:
```
git config --global user.email <[your_correct_email@example.com](mailto:your_correct_email@example.com)>
git config --global [user.name](http://user.name/) <your_correct_username>
```

**Comment by kennyotani** [comment]
Thanks for the help. I will create a new pull request after configuring my github.

**Pull request closed without merging**
