### PR TITLE
[Edit] CSS [Edit] CSS Colors: color #3647

### PR DESCRIPTION
**Pull request by ndumidoescode**
### Description

- Made an edit to a term within CSS Colors
- Added a supplemental image/media as instructed
- Closes issue #3647 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation
- Added and image representing code blocks

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by ishg-153 — CHANGES_REQUESTED** [review]
@ndumidoescode I understand that the issue didn't specify where the change was expected. You need to add an image that showcases the output for the existing entry `content/css/concepts/colors/terms/color/color.md` here. Please remove the files you've added- `color.md`, `colors-css.md`, and `colors-image-from-workspace.png`.

Let me know when you are done making the necessary changes.

**Comment by ndumidoescode** [comment]
@ishg-153 Hi, thank you for the review. Just to clarify, all you require of me is to add an image reflecting the output for the existing entry; nothing more, nothing less? And I would push it to my existing branch, css-colors?

**Comment by ishg-153** [comment]
> @ishg-153 Hi, thank you for the review. Just to clarify, all you require of me is to add an image reflecting the output for the existing entry; nothing more, nothing less? And I would push it to my existing branch, css-colors?

@ndumidoescode I understand that your example showcases the `color` property better so you can switch out the existing example and output for one of yours in the file in this path:
`content/css/concepts/colors/terms/color/color.md`

You can then delete the current `color.md` file in the root directory. 

And yes you can work on this same branch and PR.

**Comment by ndumidoescode** [comment]
> > @ishg-153 Hi, thank you for the review. Just to clarify, all you require of me is to add an image reflecting the output for the existing entry; nothing more, nothing less? And I would push it to my existing branch, css-colors?
> 
> @ndumidoescode I understand that your example showcases the `color` property better so you can switch out the existing example and output for one of yours in the file in this path: `content/css/concepts/colors/terms/color/color.md`
> 
> You can then delete the current `color.md` file in the root directory.
> 
> And yes you can work on this same branch and PR.

@ishg-153 Thank you, I will work on that.

**Comment by ishg-153** [comment]
Hey @ndumidoescode How are the changes coming along?

**Comment by ndumidoescode** [comment]
> Hey @ndumidoescode! How are the changes coming along?

Hi @ishg-153. It's going well; the only issue now is that I'm having difficulty deleting the color.md file from the root directory.

**Comment by ishg-153** [comment]
> Hi @ishg-153. It's going well; the only issue now is that I'm having difficulty deleting the color.md file from the root directory.

@ndumidoescode This is how I'd approach this issue:
- Delete the file from your local repo `git rm color.md` (make sure you are in the root directory of the git repo)
- Then commit that change as usual and push it to this remote branch

Let me know if you need more help troubleshooting.

**Comment by ndumidoescode** [comment]
> > Hi @ishg-153. It's going well; the only issue now is that I'm having difficulty deleting the color.md file from the root directory.
> 
> @ndumidoescode This is how I'd approach this issue:
> 
> * Delete the file from your local repo `git rm color.md` (make sure you are in the root directory of the git repo)
> * Then commit that change as usual and push it to this remote branch
> 
> Let me know if you need more help troubleshooting.

Thank you @ishg-153, I will take those recommendations on board.

**Pull request closed without merging**
