### PR TITLE
Cpp deque insert 5358

### LINKED ISSUE #5358: [Term Entry] C++ Deque Insert()
### Reason/inspiration (optional)

We would like a new entry on the `.insert()` term under Deque in C++. The entry should go in a new file under `docs/content/cpp/concepts/deque/terms/insert/insert.md`.  
  
The entry should include:  
  
- An introduction to the concept  
- A `Syntax` section that provides the syntax for the concept  
- An `Example` section that provides an example demonstrating the concept in use  
- A `Codebyte Example` section that provides a codebyte example demonstrating the concept in use  
  
Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by Cibiyanna26**
### Description
 New entry `.insert()` added under the c++ deque section.

### Issue Solved

Closes #5358 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by mamtawardhani — CHANGES_REQUESTED** [review]
Hey @Cibiyanna26 thank you for contributing to Codecademy Docs, the entry is nicely written. 😄 

I've suggested a few changes, please review and modify them at your earliest convenience. Also, please remove the `push_back.md` file from this branch, keep only the `insert.md` file on this branch.

Thank you!

**Comment by Cibiyanna26** [comment]
@mamtawardhani I will make the changes and let you know

**Comment by Cibiyanna26** [comment]
@mamtawardhani I have made the changes you have mentioned, do checkout it out. Let me know if there are any other changes to be made.

**Review by mamtawardhani — APPROVED** [review]
Thank you for contributing to Codecademy Docs @Cibiyanna26 😄 

The entry looks good for a second round of review! 🚀

**Review by Sriparno08 — APPROVED** [review]
Looks good, @Cibiyanna26!

**Pull request merged**
