### PR TITLE
Added information about reference data types to java/data-types documentation

### LINKED ISSUE #850: [Edit] Java: Data Types + related entries
### Type of Edit (select all that apply)

Clarify unclear content and/or terms

### Description (optional)

Add a section to the [Java: Data Types entry](https://www.codecademy.com/resources/docs/java/data-types) about **reference types**, including:

- Annotations
- Arrays
- Classes
- Enumeration
- Interfaces

For the following entries, include info about how the given concept is one of the reference data types (hyperlink back to Java: Data Types entry):

- [Arrays](https://www.codecademy.com/resources/docs/java/arrays)
- [Classes](https://www.codecademy.com/resources/docs/java/classes)
- [Enums](https://www.codecademy.com/resources/docs/java/enums)
- [Interfaces](https://www.codecademy.com/resources/docs/java/interfaces)

Let us know if you'd like to be assigned to this issue 😄

### Code of Conduct

- [X] I agree to follow Codecademy Doc's Code of Conduct

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by csavell**
…entation and added links in appropriate entries

### Description

As part of the Collaborating with the GitHub Community lesson, I searched for an issue to resolve. I edited java/data-types.md to include a section about reference data types. I also added lines to java/arrays.md, java/classes.md, java/enums.md, and java/interfaces.md that identify these as reference data types with a link to the relevant section in data-types.md. Closes #850 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [ x] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — APPROVED** [review]
@csavell, I did a first review and didn't see anything to change, so I'm passing this on for a second review.

**Review by KTom101 — CHANGES_REQUESTED** [review]
@csavell I've added some minor changes to this.

**Comment by KTom101** [comment]
@csavell Just checking in to see if you need assistance with anything?

**Review by KTom101 — APPROVED** [review]
@csavell I went ahead and made the changes with some additional ones ->  [4eb6d45](https://github.com/Codecademy/docs/pull/1289/commits/4eb6d457db956fd98f3854c5eb1c5be27e5c0ced), [d7b0837](https://github.com/Codecademy/docs/pull/1289/commits/d7b083782562dd1b93a306a68c2a40b1a5f01c8a), [0bcec76](https://github.com/Codecademy/docs/pull/1289/commits/0bcec76e2d96a7ef56b6897702c1cc98238469ed), [3e6a7ff](https://github.com/Codecademy/docs/pull/1289/commits/3e6a7ffe49a4c7e2892fc788fe8ce094f3e37a01), [fb36074](https://github.com/Codecademy/docs/pull/1289/commits/fb36074fdd83a4b51f6fba56f10adf230132618c). Looks good to merge 👍

**Comment by KTom101** [comment]
@csavell Thank you for your contribution! 🎉 The live links are here:

- [Java|Interfaces](https://www.codecademy.com/resources/docs/java/interfaces)
- [Java|Arrays](https://www.codecademy.com/resources/docs/java/arrays)
- [Java|Classes](https://www.codecademy.com/resources/docs/java/classes)
- [Java|Data Types](https://www.codecademy.com/resources/docs/java/data-types)
- [Java|Enums](https://www.codecademy.com/resources/docs/java/enums)

I noticed you're not listed as a contributor. If, you want to be listed please verify you have done the following steps to add your GitHub account to your Codecademy profile:

               1.  Added your GitHub username to your Codecademy profile;
Share your interests and goals (160 characters max)
                2. Log out and log in on Codecademy using your GitHub login.
Log in to Codecademy

Let me know if you need any help! 🙏

**Pull request merged**
