### PR TITLE
Python data types

### PR DESCRIPTION
**Pull request by SSwiniarski**
### Description

Update Python data types to remove remnants of original plagiarism from [here](https://www.w3schools.com/python/python_datatypes.asp). Also some additional language cleanup. 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by SSwiniarski** [comment]
[This] (https://github.com/Codecademy/docs/blob/9bf5b12a92524e77aa5e4b9ec5d3f9ffef0bb576/content/python/encyclopedia/data-types-in-python.md) was the original hackathon entry, which was copied wholesale from [here] (https://www.w3schools.com/python/python_datatypes.asp). Fortunately, subsequent edits removed most of the plagiarism. I just tried to remove the reminder and do some polishing while I was editing.

**Review by Dusch4593 — APPROVED** [review]
LGTM! 👍

**Comment by yangc95** [comment]
Second review underway. I'll tag you once I've given my comments/suggestions!

**Review by yangc95 — COMMENTED** [review]
@SSwiniarski Review 2️⃣ done, I'm also going to go in and combine the examples below with their outputs.

**Comment by SSwiniarski** [comment]
@yangc95, I incorporated your suggestions.

**Review by yangc95 — APPROVED** [review]

**Comment by yangc95** [comment]
Edits live here: https://www.codecademy.com/resources/docs/python/data-types

Everything looks much better 🙏 thanks @SSwiniarski @Dusch4593

**Pull request merged**
