### PR TITLE
Update cpp.md in simple and precise points

### PR DESCRIPTION
**Pull request by 05hiteshbansal**
### Description

C++ description is hard to understand in paragraph format so I break it into simple and easy language 

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by 05hiteshbansal** [comment]
@caupolicandiaz please review my PR

**Comment by 05hiteshbansal** [comment]
@avdhoottt please review my PR

**Comment by 05hiteshbansal** [comment]
@caupolicandiaz please review my PR

**Comment by 05hiteshbansal** [comment]
@caupolicandiaz please review my PR

**Comment by 05hiteshbansal** [comment]
@KTom101 please review my PR

**Comment by 05hiteshbansal** [comment]
@KTom101 please review my PR

**Comment by 05hiteshbansal** [comment]
@lucwhite please review my PR

**Comment by 05hiteshbansal** [comment]
@caupolicandiaz please review my PR

**Comment by SSwiniarski** [comment]
@caupolicandiaz, @KTom101, I am unsure what this is adding to the c++ landing page. Do either of you see this as a worthwhile edit?

**Comment by caupolicandiaz** [comment]
> @caupolicandiaz, @KTom101, I am unsure what this is adding to the c++ landing page. Do either of you see this as a worthwhile edit?

I'm inclined to reject these changes. I don't see that much is being added here.

**Comment by 05hiteshbansal** [comment]
previously it was difficult to understand and with points every thing is simplified  with minimal explanation and greater understanding

**Comment by SSwiniarski** [comment]
@05hiteshbansal I'm afraid we don't happen to agree with your rationale. Simply breaking paragraphs into bulleted lists is not improving the article. We're going to close this.

**Pull request closed without merging**
