### PR TITLE
C++ abstraction is added

### PR DESCRIPTION
**Pull request by Sushilverma002**
close issue-> #3043 

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by Sushilverma002** [comment]
@SSwiniarski please review my PR.

**Comment by Sushilverma002** [comment]
@SSwiniarski please review

**Review by KTom101 — APPROVED** [review]
@Sushilverma002 I added a couple of changes directly. Please wait for a second review.

**Comment by Sushilverma002** [comment]
@yangc95 please do a final review and merge it.

**Review by yangc95 — APPROVED** [review]
LGTM

**Pull request merged**
