### PR TITLE
[Term Entry] Swift Protocols Encodable

### LINKED ISSUE #2884: [Term Entry] Swift Protocols Encodable
### Reason/inspiration (optional)

We would like a new term entry for Swift [Protocols](https://www.codecademy.com/resources/docs/swift/protocols) about the Encodable protocol. The entry should go in a new file in docs/content/swift/concepts/protocols/terms/encodable/encodable.md

The entry should
    - Have an introductory paragraph about what the protocol is and does.
    - A syntax section with a pseudo code block with an explanation of it.
    - A basic example showing the protocol in use

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by gracekishino**
### Description

* Added new folder `encodable` inside `content/swift/concepts/protocols/terms/`.
* Added new term entry file `content/swift/concepts/protocols/terms/encodable/encodable.md` for Swift Protocols Encodable.
Closes #2884

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by caupolicandiaz — CHANGES_REQUESTED** [review]
@gracekishino Overall, looks very good. I just added one comment. Please update, and tag me when you've made the changes. Thanks

**Comment by gracekishino** [comment]
@caupolicandiaz thanks so much for reviewing! I committed the suggested change.

**Review by caupolicandiaz — APPROVED** [review]
@gracekishino This is ready for a second review.

**Review by SSwiniarski — APPROVED** [review]
@gracekishino Looks good!

**Pull request merged**
