### PR TITLE
Python : add Iterators

### PR DESCRIPTION
**Pull request by DeepakReddyVelagala**
### Description

Created a folder named iterators containing iterators.md contained in content>python>concepts, for the issue #287  
### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by DeepakReddyVelagala** [comment]
> Hi @DeepakReddyVelagala, this is Brandon from the Free Team. It looks like your fork's `main` branch is 4 commits ahead of and 48 commits behind the `main` branch in the core `Codecademy/docs` repo. Your fork's `main` branch should always be even, or caught up, with the Docs `main` branch. Below, I have a recommended fix:
> 
> If you don't already have the core Docs repo set as an `upstream` remote, do this first:
> 
> ```
> $ git remote add https://github.com/Codecademy/docs.git
> ```
> 
> Your `origin` remote should be linked to the url of your forked Docs repo by default:
> 
> ```
> $ git remote -v
> origin  https://github.com/DeepakReddyVelagala/docs.git (fetch)
> origin  https://github.com/DeepakReddyVelagala/docs.git (push)
> upstream        https://github.com/Codecademy/docs.git (fetch)
> upstream        https://github.com/Codecademy/docs.git (push)
> ```
> 
> Next, run the following commands:
> 
> ```
> $ git checkout main
> $ git pull upstream main
> $ git reset --hard upstream/main
> $ git push origin main --force
> ```
> 
> This should reset your local `main` branch to be even with `upstream`, then force-push to `origin`.
> 
> After that, your fork's `main` branch will (hopefully) be even with the Docs `main` branch. This should also allow the remaining tests (🟠) to proceed, run, and finish.
> 
> Let us know if you have any trouble with this and we will be happy to help!

thanks for the help, followed the steps

**Comment by sonnynomnom** [comment]
Merging! @DeepakReddyVelagala Make sure to add a profile picture for your GitHub profile so that you show up in our contributor's list!

**Comment by DeepakReddyVelagala** [comment]
> Merging! @DeepakReddyVelagala Make sure to add a profile picture for your GitHub profile so that you show up in our contributor's list!

thanks!

**Comment by sonnynomnom** [comment]
Also congrats on the new entry!

Made another round of review: https://github.com/Codecademy/docs/commit/9b4f0feaa444d3150a850f5c6e0ee742fc307d03

Notes:
- No more than 2 items in ContentCatalog.
- No italics for new keywords
- `iter()` and `next()` are functions, not methods

@DeepakReddyVelagala @SSwiniarski @yangc95 

So we are good!

**Comment by sonnynomnom** [comment]
Also this is what I meant with GitHub profile picture @DeepakReddyVelagala:

Screen Shot 2021-11-04 at 12 10 55 AM

**Pull request merged**
