### PR TITLE
[Edit] Markdown: Paragraphs

### LINKED ISSUE #3852: [Edit] Markdown: Paragraphs
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

I have noticed a typo in the text. I would love to work on it as my very first contribution. 

image

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by pikkukurkku**
### Description

- I spotted a typo in the doc about markdown paragraphs and fixed it
- Closes #3852 

### Type of Change

- Editing an existing entry (fixing a typo)

### Checklist

- [x ] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by ishg-153 — CHANGES_REQUESTED** [review]
Hey @pikkukurkku! I see you've fixed the typo in `content/markdown/concepts/paragraphs/paragraphs.md`. But you also seem to have added in the `paragraph.md` file again in the root directory. Can you remove that?

**Comment by pikkukurkku** [comment]
Hi @ishg-153 ! Thanks for pointing this out. I have now removed the `paragraphs.md` from the root directory and commited the changes. Hope all is good now.

**Review by ishg-153 — APPROVED** [review]
@pikkukurkku, yep this looks good for a second review.

**Review by SSwiniarski — APPROVED** [review]
@pikkukurkku Looks good.

**Pull request merged**
