### PR TITLE
New term entry kotlin serialization encodeToByteArray

### LINKED ISSUE #3872: [Term Entry] Kotlin Serialization .encodeToByteArray()
### Reason/inspiration (optional)

We would like a new term entry on the `.encodeToByteArray()` method for Kotlin: [Serialization](https://www.codecademy.com/resources/docs/kotlin/serialization). The entry should go in a new file under `docs/content/kotlin/concepts/serialization/terms/encodeToByteArray/encodeToByteArray.md`.

The entry should describe what the method does. Be sure to include the following sections:

- A "Syntax" section with a ` ```pseudo` code snippet.
- An "Example" section with a ` ```kotlin `code snippet.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by mozesi**
### Description

- New term entry on Kotlin Serialization .encodeToByteArray() method
- Closes #3872 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by Sriparno08** [comment]
Hey @mozesi, please change the following line in your example code:

```
val course = Course("Introduction to Programming.", "An introductory course to programming using Kotlin.")
```
to:

```
val course = Course("Learn Kotlin", "The expressive, open-source programming language developed by JetBrains.")
```

Then, paste the code and the new output to the article and commit the changes.

**Comment by mozesi** [comment]
@Sriparno08 I have done the changes.

**Review by Sriparno08 — COMMENTED** [review]
Hey @mozesi, thanks for contributing to Codecademy!

I've listed all the modifications that you need to make in your article below:

**Comment by mozesi** [comment]
@Sriparno08, thanks for the review, I have done the commits.  I have liked the references to other articles.

**Review by Sriparno08 — APPROVED** [review]
Good job, @mozesi 👍

This looks good for a second review.

**Review by avdhoottt — APPROVED** [review]
Looks good to get merged.

**Pull request merged**
