### PR TITLE
Swift array term entry filter

### PR DESCRIPTION
**Pull request by MandyDoree**
### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by MandyDoree** [comment]
@caupolicandiaz

**Review by SSwiniarski — APPROVED** [review]
@MandyDoree Looks good. Just need @caupolicandiaz to look it over again.

**Review by caupolicandiaz — APPROVED** [review]
@MandyDoree @SSwiniarski LGTM

**Comment by SSwiniarski** [comment]
@MandyDoree Congrats on the new entry. Live link here: https://www.codecademy.com/resources/docs/swift/arrays/filter

image

You're currently anonymous. If you don't wish to be anonymous, check out this forum thread on how to link your GitHub and Codecademy profiles: https://discuss.codecademy.com/t/my-contribution-is-live-but-im-not-being-shown-as-a-contributor-why-is-this/758036  **Note:** it may take a few minutes for the change to register on the entry page.

**Pull request merged**
