### PR TITLE
HTML Images: Updated typo

### PR DESCRIPTION
**Pull request by lademinoye**
### Type of Change

- Editing an existing entry (fixing a typo)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by Dusch4593** [comment]
Hi @lademinoye! Brandon from the Free Team 😄 Thank you for catching that typo! I'm gonna take a look at your changes and leave any comments/suggestions, if necessary. I'll tag you once I'm done.

**Review by lukeecart — APPROVED** [review]
Great spot, thank you!

**Review by Dusch4593 — APPROVED** [review]
LGTM! Merging. I'll let everyone know when the changes go live.

**Comment by Dusch4593** [comment]
@lademinoye @lukeecart The changes are now live!

https://www.codecademy.com/resources/docs/html/images

**Pull request merged**
