### PR TITLE
Images display issue resolved

### PR DESCRIPTION
**Pull request by SarthakD15**
### Description

There was an issue while displaying images on this page :
https://www.codecademy.com/resources/docs/html/images
Solved the issue by fixing a small error/typo in the code

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — APPROVED** [review]
@SarthakD15 I undid the changes to the `yarn.lock` file and now it looks good for a second review.

**Comment by SarthakD15** [comment]
Yeah Thanks @SSwiniarski, I forgot about yarn.lock !
Thanks for the help :)

**Review by caupolicandiaz — APPROVED** [review]
@SarthakD15 @SSwiniarski LGTM

**Comment by SarthakD15** [comment]
Closes #3416

**Pull request merged**
