### PR TITLE
[Edit] Lua String: .find()

### PR DESCRIPTION
**Pull request by T-Mwangi**
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

I initially created this term entry, but noticed some issues that were accidentally left into the final merge, specifically:

1) a duplicated note left at the bottom of the entry. the first is on line 42.
2) a use of markdown footnotes either was incorrectly formatted or doesn't show up on the docs. either way, the footnote reference on line 40 is not necessary.

 These are my mistakes, and therefore, I should be allowed to make the necessary edits.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [ ] Labels added
- [ ] Issue is assigned

### CODE REVIEW

**Comment by T-Mwangi** [comment]
hey @dakshdeepHERE @SSwiniarski I noticed some edits that were not intended in the final merge and made the necessary edits. Sorry about missing it before

**Comment by T-Mwangi** [comment]
hey @dakshdeepHERE @SSwiniarski I noticed some edits that were not intended in the final merge, and made the necessary edits.

**Comment by dakshdeepHERE** [comment]
@T-Mwangi Nice one. I also missed that we had planned to shift that note above. Looks good for second review.

**Review by dakshdeepHERE — APPROVED** [review]

**Review by SSwiniarski — APPROVED** [review]
@T-Mwangi Looks good.

**Pull request merged**
