### PR TITLE
Broken links #1912

### PR DESCRIPTION
**Pull request by Son0-lory**
### Description

Close#<1912> The issue identified some broken links inside Codecademy Docs section dedicated to Phyton's concepts.
Entries (11-13, 15-20) have been fixed by editing the given files with the correct URLs.

*Exception*, the entry# 14 had the follow link to be corrected:

Screenshot 2023-04-01 105409

After exploring the code of the relative file and recognized that the given link belongs to a snipped code example as simple text it's clear that doesn't need to be active(follows screenshot).

Screenshot 2023-03-31 214301

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

Let me know if any more changes are need, or how to improve the PR, thank you.

### CODE REVIEW

**Comment by Son0-lory** [comment]
I just noticed that my commit messages recall previous Codecademy issues, please ignore it.
I apologize.
I'm available for any clarification and suggestions.

**Review by caupolicandiaz — APPROVED** [review]
@Son0-lory Looks good. I made one small edit to correct another typo in one of the entries. This is ready for another review.

**Review by SSwiniarski — APPROVED** [review]
@Son0-lory looks good to merge.

**Comment by SSwiniarski** [comment]
@Son0-lory congrats on your merged PR.

**Comment by Son0-lory** [comment]
Great, thank you.

**Comment by yangc95** [comment]
👏 Here are all the changed files: Python Built-in Functions: [open()](https://www.codecademy.com/resources/docs/python/built-in-functions/open), [Classes](https://www.codecademy.com/resources/docs/python/classes), [Dunder Methods](https://www.codecademy.com/resources/docs/python/dunder-methods), Files:[ .remove()](https://www.codecademy.com/resources/docs/python/files/remove), [.rmdir()](https://www.codecademy.com/resources/docs/python/files/rmdir), [.unlink()](https://www.codecademy.com/resources/docs/python/files/unlink), Modules:[ PySpark](https://www.codecademy.com/resources/docs/python/modules/pyspark), OS Path Module: [.join()](https://www.codecademy.com/resources/docs/python/os-path-module/join), [Requests Module](https://www.codecademy.com/resources/docs/python/requests-module)

Feel free to take on any open Issues and hope to see you around on Docs!

**Pull request merged**
