### PR TITLE
Added documentation for sort function in NumPy (#5700)

### PR DESCRIPTION
**Pull request by Maverick073**
### Issue Solved
#5700 

### Type of Change

- Adding a new entry
### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by SaviDahegaonkar — CHANGES_REQUESTED** [review]
Hey @Maverick073 ,
Thank you for contributing to Docs! I had a look at your file and suggested a few changes; please make them as soon as possible.

Thanks,
Savi

**Comment by SaviDahegaonkar** [comment]
Hey @Maverick073,
Can you tell me why this issue has been closed?

Thanks,
Savi

**Comment by Maverick073** [comment]
Hey @SaviDahegaonkar , I deleted this branch , and created a new branch with the changes that you had mentioned  .

**Comment by SaviDahegaonkar** [comment]
Okay @Maverick073, No issues. Thanks for contributing to Codecademy :)

Thanks,
Savi

**Pull request closed without merging**
