### PR TITLE
[New Entry] Java: Stacks

### PR DESCRIPTION
**Pull request by sanvisharma003**
heyy.. here is the stack documentation using java. i have explained some functions and also written a code for implementaion of stack data structure.
taking part in the hacktoberfest for the first time so if there are any changes needed, do ping me.

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by sanvisharma003 — COMMENTED** [review]
done with the documentation

**Comment by sanvisharma003** [comment]
heyy.. what do i need to do now? i created a pr yesterday..

**Comment by SSwiniarski** [comment]
@sanvisharma003, Thanks for contributing, but this PR is not conforming to the Docs content standards listed [here](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md). You should also review the entry template [here](https://github.com/Codecademy/docs/blob/main/documentation/entry-template.md). Also this file should be relocated to docs/content/java/stacks/stacks.md. You should rewrite this with those in mind before it gets reviewed.

**Comment by Dusch4593** [comment]
Hey @sanvisharma003 I wanted to know if you had any questions regarding @SSwiniarski's feedback, formatting of Docs entries, etc.? Happy to help! 😄

**Comment by SSwiniarski** [comment]
@sanvisharma003, we're going to close this entry. Feel free to re-submit a PR with a version that conforms to the content standards.

**Pull request closed without merging**
