### PR TITLE
[Term Entry] PyTorch Tensors .ones()

### LINKED ISSUE #4936: [Term Entry] PyTorch Tensors .ones()
### Reason/inspiration (optional)

We would like a new entry on the `.ones()` term under PyTorch `Tensors` concept. The entry should go in a new file under `docs/content/pytorch/concepts/tensors/terms/ones/ones.md`.

The entry should include:

- An introduction to the concept
- A ‘Syntax’ section that provides the syntax for the concept (if applicable)
- An ‘Example’ section that provides an example demonstrating the concept in use

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by kerikek**
### Description
- Added the .ones() function for Pytorch
- Closes #4936  

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by kerikek** [comment]
@Sriparno08 Made formatting changes and awaiting approval of edits. Thanks!

**Comment by kerikek** [comment]
@Sriparno08 Made additional formatting edits and awaiting approval. Thanks!

**Review by Sriparno08 — CHANGES_REQUESTED** [review]
Hey @kerikek, thanks for contributing to Codecademy Docs!

I've listed all the modifications that you need to make in your entry below:

**Review by Sriparno08 — APPROVED** [review]
Good job, @kerikek!

This PR looks good for a second round of review. 👍

**Review by mamtawardhani — APPROVED** [review]
Thank you for your contribution @kerikek 😄 

The entry looks good to be merged 🚀

**Pull request merged**
