### PR TITLE
Fix error in test output

### LINKED ISSUE #5090: [Edit] Golang Strings
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

We would like to edit the `.cutsuffix()` term entry under the strings concept in Golang. The entry lives in `content/go/concepts/strings/terms/cutsuffix/cutsuffix.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:

Correct the output of the example code given in the entry. 

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by MarkFarmiloe**
CutSuffix() returns true when the suffix is an empty string. The test output shown does not reflect this.

### Description

Fix of a small error in the test output of your strings.CutSuffix page

### Issue Solved
Closes #5090 

Not raised as an issue

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by mamtawardhani — APPROVED** [review]
Thank you for your contribution @MarkFarmiloe and thanks for highlighting this! 😄 

The entry looks great for a second round of review 🚀

**Comment by mamtawardhani** [comment]
@Sriparno08 assigned this to you so that we can close this at the earliest 😃

**Comment by Sriparno08** [comment]
Yeah sure, @mamtawardhani! 👍

**Review by Sriparno08 — APPROVED** [review]
Looks good, @MarkFarmiloe! 👍

**Comment by Sriparno08** [comment]
Hey @mamtawardhani, I think we should wait for the author to get assigned to the corresponding issue before we merge it. What do you say?

**Comment by mamtawardhani** [comment]
> Hey @mamtawardhani, I think we should wait for the author to get assigned to the corresponding issue before we merge it. What do you say?

Sure, we can wait for a few hours, I'll tag the author to comment on the issue, since I'm not able to assign until they comment 😢

**Comment by mamtawardhani** [comment]
> > Hey @mamtawardhani, I think we should wait for the author to get assigned to the corresponding issue before we merge it. What do you say?
> 
> Sure, we can wait for a few hours, I'll tag the author to comment on the issue, since I'm not able to assign until they comment 😢

@Sriparno08 you can merge it now, the author has been assigned to the issue 😃 Thank you!

**Pull request merged**
