### PR TITLE
Conditionals.md

### PR DESCRIPTION
**Pull request by VishakhaSi**
### Description

I was assigned an issue for creating a document of general conditionals.. 
### Type of Change

- Adding a new entry
Added conditionals.
### Checklist

- [Y] All writings are my own.
- [ Y] My entry follows the Codecademy Docs style guide.
- [Y ] My changes generate no new warnings.
- [ Y] I have performed a self-review of my own writing and code.
- [Y ] I have checked my entry and corrected any misspellings.
- [ Y] I have made corresponding changes to the documentation if needed.
- [ Y] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ Y] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ Y] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by yangc95** [comment]
Thanks for putting in a PR for this corresponding issue!

@VishakhaSi before I take this one for the first review, please self-revise. Take a look at this specific template: https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md

Notice that we're missing the metadata here. In addition, please look over the rest of the entry and take a closer look at the style guide: https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md

When you believe this is ready for a review, please re-tag me and we can go from there.

**Review by VishakhaSi — COMMENTED** [review]
@yangc95 Kindly review.
I have added the metadata and need a little help in linking the other languages.

**Review by yangc95 — APPROVED** [review]
@VishakhaSi Going to pass this onto @caupolicandiaz for a second review.

I do wonder if using the if and switch examples are necessary if we're linking to the specific language implementations. On one hand, reading this entry with the examples helps reinforce the idea, it is redundant to the language-specific entries on conditionals.

**Review by caupolicandiaz — CHANGES_REQUESTED** [review]
@VishakhaSi I've completed my initial review. Please update the entry, and tag me when you've finished making changes. Thanks

**Comment by SSwiniarski** [comment]
@VishakhaSi congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/general/conditionals

You're currently listed as an anonymous contributor. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.

image

To add your GitHub username to your Codecademy profile:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

image

2.) Make sure to set your visibility to “everyone”:

image

3.) Then log out and log back into Codecademy using your GitHub login:

image

**Note**: Your email used for Codecademy will have to be listed in your GitHub profile for the login feature to properly work. If you use the same email for both GitHub and Codecademy already, then you're set.

In addition, we may reach out in the future if any adjustments to these entries are required.

**Pull request merged**
