### PR TITLE
typo fix && introduce .size() method

### PR DESCRIPTION
**Pull request by arinze19**
### Description

Added typo fixes for cpp lesson and an mini introduction to `.size` method in `cpp-vectors` docs

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — CHANGES_REQUESTED** [review]
@arinze19, I did a first review and had one comment.

**Comment by SSwiniarski** [comment]
@arinze19 Because it's been three weeks, I'm committing my suggestion so this can go on to a second review.

**Review by KTom101 — APPROVED** [review]
@arinze19 I directly added a couple of minor changes [f27970d](https://github.com/Codecademy/docs/pull/1817/commits/f27970dc96625d4d5cb1c5c363a472b2ae9b5af4) & [5ea2eea](https://github.com/Codecademy/docs/pull/1817/commits/5ea2eea72f755177fbee9e48bb5e7f82ae3a17b8). Looks good, otherwise 👍.

**Comment by KTom101** [comment]
@arinze19 Your contributions are listed C++: [Enums](https://www.codecademy.com/resources/docs/cpp/enum), [Vectors](https://www.codecademy.com/resources/docs/cpp/vectors).

Screenshot 2023-04-08 at 10 21 53 PM


Screenshot 2023-04-08 at 10 21 41 PM

**Pull request merged**
