### PR TITLE
Update arrow-functions.md

### PR DESCRIPTION
**Pull request by Stevengdev1**
Removed extra word from "functions" on line 36.
Corrected the spelling of the word "Exammple to Example" on line 67.

### Description

Fixed sentence by removing the a word that was used twice.  (Removed word was "function")
Also corrected the spelling of a word. (Corrected the word "Exammple" to "Example'.)

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by Dusch4593 — COMMENTED** [review]
@Stevengdev1 thank you for flagging this! 😄

Looks good to merge as-is 👍🏻

**Review by Dusch4593 — APPROVED** [review]

**Comment by Dusch4593** [comment]
Congrats and thank you for contributing to Codecademy Docs, @Stevengdev1! 🎊 🎉 🥳

The changes should be live here: https://www.codecademy.com/resources/docs/javascript/arrow-functions

Your Codecademy profile seem to currently be anonymous under the contributors list on the entry page. To make it visible, you'll need to add your GitHub username to your Codecademy account, log out of Codecademy, and then log back in through your GitHub account.

Screen Shot 2022-12-28 at 5 54 20 PM

Looking forward to your next Docs contribution! 😄

**Comment by Stevengdev1** [comment]
Hey Brandon,
Yeah this was my very first ever contribution I was hoping that I was doing everything right and it looks like I did since it went through.  Also, I did log back in to Codecademy with my Github acct so hopefully that could get updated soon, Thanks for the prompt response!

**Comment by Dusch4593** [comment]
@Stevengdev1 Looks good! 👍🏻 

Screen Shot 2022-12-30 at 11 47 01 AM

**Comment by Stevengdev1** [comment]
Cool! Thanks Brandon! Happy New Year!

**Pull request merged**
