### PR TITLE
[Term Entry] Python function: math.acosh()

### PR DESCRIPTION
**Pull request by FabioNH86**
### Description

- Added the math.acosh() term for python.

### Issue Solved

- Closes issue #5077 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by FabioNH86** [comment]
Hello! I hope you're doing well. My work is ready for review, and I hope I didn't make too many mistakes. If it's ready, I would love to receive credit. The link to my Codecademy profile (@Fabio_Noriega86) is on my GitHub profile. Best regards!

**Comment by FabioNH86** [comment]
Sorry, I just noticed that the issue title refers to math.cosh(), but the instructions I followed talk about math.acosh(). What should I do?

**Comment by mamtawardhani** [comment]
@FabioNH86 sorry for the inconvenience caused, I fixed it. I assigned you to the `acosh` issue.

**Review by mamtawardhani — APPROVED** [review]
Thank you for your contribution to Codecademy Docs @FabioNH86 😄 

The is nicely written and ready for a second round of review! 🚀

**Review by Sriparno08 — APPROVED** [review]
Looks good, @FabioNH86! 👍

**Pull request merged**
