### PR TITLE
[Edit] CSS Typography: font-weight

### LINKED ISSUE #4417: [Edit] CSS [Edit] CSS Typography: font-weight
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like an edit to a term within CSS `font-weight`. The term entry lives in `content/css/concepts/typography/terms/font-weight/font-weight.md`

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line. ex: [See last image here](https://www.codecademy.com/resources/docs/html/attributes/title)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by ntjnh**
### Description

I have added two example images for `font-weight: bold` and `font-weight: 600;` within the term entry for CSS font-weight in `content/css/concepts/typography/terms/font-weight/font-weight.md`

### Issue Solved

Closes #4417 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by ishg-153** [comment]
Hey @ntjnh! Can you sign the CLA as prompted above till I review your entry?

**Comment by ntjnh** [comment]
@ishg-153 Sorry missed that. Done!

**Review by ishg-153 — APPROVED** [review]
@ntjnh Great work! Made some small changes from my end. Remember to add methods, attributes, etc in single backticks.

Good for a second review.

**Review by avdhoottt — APPROVED** [review]
LGTM!!

**Pull request merged**
