### PR TITLE
php pi() function further enhancement - inclusion of constants

### PR DESCRIPTION
**Pull request by arisdelacruz**
### Description

This is an attempt to push further enhancement into the existing reference for the pi() function. Motivation emanates from the evaluation of available resources on the constants related to the mentioned function. Consideration is, therefore, requested.

### Type of Change

- Updating the documentation

### Checklist

- [ / ] All writings are my own.
- [ / ] My entry follows the Codecademy Docs style guide.
- [ / ] My changes generate no new warnings.
- [ / ] I have performed a self-review of my own writing and code.
- [ / ] I have checked my entry and corrected any misspellings.
- [ / ] I have made corresponding changes to the documentation if needed.
- [ / ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ / ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ / ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by arisdelacruz** [comment]
@SSwiniarski 

requesting that draft enhancements be considered

crossing my fingers now, hehe

thanks

**Comment by SSwiniarski** [comment]
@arisdelacruz We cannot merge this PR since you accidently deleted 27 other entries in making it. It might be better to try again with a fresh branch off of main.

**Comment by arisdelacruz** [comment]
@SSwiniarski 

oh no!!!

my bad

okay, i'll try again

thanks

**Comment by arisdelacruz** [comment]
@SSwiniarski 

Is it possible if I create another MD for pi?

or, am I using the git pull the wrong way

**Comment by SSwiniarski** [comment]
@arisdelacruz You should be able to pull changes into main, make a new branch, and edit the existing .md file. Creating a new .md file would just create a conflict that would need to be resolved.

**Comment by arisdelacruz** [comment]
@SSwiniarski 

image

if i'm receiving this message, is it right to use git pull <remote> <branch>

?

i think i need some guidance now

big thanks

**Comment by arisdelacruz** [comment]
@SSwiniarski 

i did git pull origin pi

and then

git push origin pi

i'm not sure if i was able to hurdle it

**Comment by SSwiniarski** [comment]
@arisdelacruz I think you need to start fresh with a new branch and a new pull request. This PR is deleting entries, and we can't do that.

**Comment by arisdelacruz** [comment]
@SSwiniarski 

oks, will do

Thanks

**Comment by SSwiniarski** [comment]
@arisdelacruz No, what you need to do it go to your main branch, pull all the changes from docs, create a new branch from your fork, then make edits to the pi.md file in that branch, commit those changes, and submit a new PR.

**Comment by arisdelacruz** [comment]
@SSwiniarski 

image

I did a pull from the main branch and edited pi.md

Am I on the right track now? Thanks.

**Comment by SSwiniarski** [comment]
@arisdelacruz You need to create a new branch. You're editing the same branch this PR is on. Create a new branch off of the main fork. Do the edits there. Then do a pull request from the new branch.

**Comment by SSwiniarski** [comment]
Closing because it's been replaced by [2742](https://github.com/Codecademy/docs/pull/2742)

**Pull request closed without merging**
