### PR TITLE
First commit - adding flatten doc

### PR DESCRIPTION
**Pull request by BaljiSubramani**
### Description

First commit :-) Adding new doc for numpy flatten module

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by mamtawardhani** [comment]
> [CLA assistant check](https://cla-assistant.io/Codecademy/docs?pullRequest=4842) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4842) before we can accept your contribution.
> 
> **BalajiSubramani** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4842) it.

Hey @BaljiSubramani! Could you please add the email address that is linked to your GitHub account, so that we can start the review for this pull request? 

Thank you! 😄

**Comment by BaljiSubramani** [comment]
Hello 🙂,
I updated my email id for my GitHub account.
Kindly check now!
Thank you 🙂

**Comment by mamtawardhani** [comment]
> Hello 🙂, I updated my email id for my GitHub account. Kindly check now! Thank you 🙂

Great, thanks! Could you update any small change, let's see if it reflects here in the CLA?

**Comment by BaljiSubramani** [comment]
> > Hello 🙂, I updated my email id for my GitHub account. Kindly check now! Thank you 🙂
> 
> Great, thanks! Could you update any small change, let's see if it reflects here in the CLA?

Hello :-)
I performed a commit to verify CLA. Please check now!

**Comment by mamtawardhani** [comment]
> [CLA assistant check](https://cla-assistant.io/Codecademy/docs?pullRequest=4842) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4842) before we can accept your contribution.**1** out of **2** committers have signed the CLA.✅ BaljiSubramani❌ BalajiSubramani
> 
> **BalajiSubramani** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4842) it.

@BaljiSubramani do you have any other id as well? under "BalajiSubramani". If you check this, it says that id is yet to sign the CLA.

**Comment by mamtawardhani** [comment]
> > [CLA assistant check](https://cla-assistant.io/Codecademy/docs?pullRequest=4842) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4842) before we can accept your contribution.**1** out of **2** committers have signed the CLA.✅ BaljiSubramani❌ BalajiSubramani
> > **BalajiSubramani** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> > You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4842) it.
> 
> @BaljiSubramani do you have any other id as well? under "BalajiSubramani". If you check this, it says that id is yet to sign the CLA.

Could you please check this?

**Comment by BaljiSubramani** [comment]
> > > [CLA assistant check](https://cla-assistant.io/Codecademy/docs?pullRequest=4842) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4842) before we can accept your contribution.**1** out of **2** committers have signed the CLA.✅ BaljiSubramani❌ BalajiSubramani
> > > **BalajiSubramani** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> > > You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4842) it.
> > 
> > 
> > @BaljiSubramani do you have any other id as well? under "BalajiSubramani". If you check this, it says that id is yet to sign the CLA.
> 
> Could you please check this?

Hello :-)
Sorry for late reply.
Yes, ID BalajiSubramani is mine but it is linked to office git hub account.
By mistake, i used this account to commit a change.
Can you help me to resolve this?
Thank you!

**Comment by mamtawardhani** [comment]
> > > > [CLA assistant check](https://cla-assistant.io/Codecademy/docs?pullRequest=4842) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4842) before we can accept your contribution.**1** out of **2** committers have signed the CLA.✅ BaljiSubramani❌ BalajiSubramani
> > > > **BalajiSubramani** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> > > > You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4842) it.
> > > 
> > > 
> > > @BaljiSubramani do you have any other id as well? under "BalajiSubramani". If you check this, it says that id is yet to sign the CLA.
> > 
> > 
> > Could you please check this?
> 
> Hello :-) Sorry for late reply. Yes, ID BalajiSubramani is mine, but it is linked to my office git hub account [This shall not be used outside of my organization]. By mistake, i used this account to commit a change. Can you help me to resolve this? Thank you!

Oh! Then I would suggest you close this PR and raise a new one using your email id, that would be an easy way to resolve this without using your office email id. You can let me know when you raise another PR 😃 
@BaljiSubramani

**Comment by BaljiSubramani** [comment]
> > > > > [CLA assistant check](https://cla-assistant.io/Codecademy/docs?pullRequest=4842) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=4842) before we can accept your contribution.**1** out of **2** committers have signed the CLA.✅ BaljiSubramani❌ BalajiSubramani
> > > > > **BalajiSubramani** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> > > > > You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=4842) it.
> > > > 
> > > > 
> > > > @BaljiSubramani do you have any other id as well? under "BalajiSubramani". If you check this, it says that id is yet to sign the CLA.
> > > 
> > > 
> > > Could you please check this?
> > 
> > 
> > Hello :-) Sorry for late reply. Yes, ID BalajiSubramani is mine, but it is linked to my office git hub account [This shall not be used outside of my organization]. By mistake, i used this account to commit a change. Can you help me to resolve this? Thank you!
> 
> Oh! Then I would suggest you close this PR and raise a new one using your email id, that would be an easy way to resolve this without using your office email id. You can let me know when you raise another PR 😃 @BaljiSubramani

Hello :-), I agree to above solution. I will raise a fresh PR. Thank you!

**Comment by BaljiSubramani** [comment]
Hi :-)
New PR is raised. 
Please check gh pr checkout 4875
Thank you!

**Pull request closed without merging**
