### PR TITLE
Typo fix to animation-iteration-count.md

### PR DESCRIPTION
**Pull request by DanWSDev**
Corrected inifinite to infinite on line 26

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — APPROVED** [review]
@DanWSDev Looks good for a second review.

**Comment by DanWSDev** [comment]
> @DanWSDev Looks good for a second review.

Great thank you

**Comment by caupolicandiaz** [comment]
@DanWSDev We appreciate your interest in contributing to docs; however, we've deemed this PR as not in alignment with our standards. We prefer that PRs constitute meaningful changes. In the future please comment on an existing issue (in order to be assigned) or create a new issue that we can review and approve. We ask that contributors request and receive assignment to an issue before committing any changes. Thanks

**Comment by DanWSDev** [comment]
@caupolicandiaz Okay sent it to issue and showing how to fix it

**Pull request closed without merging**
