### PR TITLE
Str repeat Edit

### PR DESCRIPTION
**Pull request by MMMMMMMZ**
### Description

Edited Str Repeat

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by MMMMMMMZ** [comment]
i cant run any of the yarn commands in the comment for some reason 

$yarn format:all
yarn run v1.22.19
$ prettier --ignore-path .prettierignore --write "./**/*.(ts|md)"
'prettier' is not recognized as an internal or external command,
operable program or batch file.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by KTom101** [comment]
@MMMMMMMZ Can you verify you're running it in the correct path? If so, you might have to try the `yarn install --force` command first and then re-run the command.

**Comment by MMMMMMMZ** [comment]
I would like my name to be on the entry on codecademy

**Comment by MMMMMMMZ** [comment]
It has been 4 days I need this Updated str repeat so I can fix my PHP exp branch timeline as it has the same mess.

**Comment by SSwiniarski** [comment]
@MMMMMMMZ Have some patience, we generally have two reviewers sign off on a PR before it's merged.

**Review by KTom101 — APPROVED** [review]
@MMMMMMMZ This is ready to be merged

**Pull request merged**
