### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by NikhilMore1**
### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by NikhilMore1** [comment]
Typescript modules and controllers are unverified and they are causes issues

**Comment by SaviDahegaonkar** [comment]
Hello @NikhilMore1, Can I know which issue this PR closes? I can't find one.

**Comment by mamtawardhani** [comment]
@SaviDahegaonkar kindly close this PR since it doesn't trace back to any issue.

**Comment by mamtawardhani** [comment]
Closing this PR as this doesn't solve any issues

**Pull request closed without merging**
