### PR TITLE
Create confirm.md

### PR DESCRIPTION
**Pull request by DaltonAC**
Add the confirm entry under Javascript/window/terms. First pass, requesting a review and suggestions.

### Description

Created an entry for the confirm method in Javascript. It included two examples and a short description about what it does and how to use it.

### Type of Change

- Adding a new entry

### Checklist

- [ x] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- x[ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by KTom101 — CHANGES_REQUESTED** [review]
@DaltonAC I've conducted a first review of this. Let me know if you have questions.

**Comment by KTom101** [comment]
@DaltonAC Just checking in to see if you need any help with the changes.

**Comment by DaltonAC** [comment]
@KTom101 I am working on getting them pushed tonight, apologies for the delay.

**Comment by DaltonAC** [comment]
Pushed my branch, let me know what further corrections are needed or information added. Thank you.

**Comment by KTom101** [comment]
@DaltonAC I took a look and there are still some changes needed. Mainly with creating a separate syntax section. If you press on the "Files Changed" Tab and then select "Conversations" (shown below) you can go back to see what I had written and see which changes still need to be made.

Screenshot 2023-06-07 at 9 22 14 PM


Screenshot 2023-06-07 at 9 23 11 PM

**Review by KTom101 — APPROVED** [review]
@DaltonAC The changes still weren't quite right. But in the interest of time, I went ahead and applied them myself in commit [6012620](https://github.com/Codecademy/docs/pull/2311/commits/60126204dcb1f808466544c46474f805f25f4f76). I also corrected the folder name for it was named "conform" instead of "confirm". 

This can go on to the next review.

**Review by SSwiniarski — APPROVED** [review]
@DaltonAC I made a couple of minor changes. Now it looks ready to merge.

**Comment by SSwiniarski** [comment]
@DaltonAC Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/javascript/window/confirm

image

**Pull request merged**
