### PR TITLE
Update machine-learning.md

### LINKED ISSUE #5425: [Edit] AI Machine Learning
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Machine Learning` concept entry under AI. The entry lives in `content/ai/concepts/machine-learning/machine-learning.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Shorten the description of the concept to not more than 160 characters
2. Fix any typo in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by Tashuuuu**
### Description

Edited ```content/ai/concepts/machine-learning/machine-learning.md``` file. Just corrected some typos.

### Issue Solved

Closes #5425

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by mamtawardhani** [comment]
> [CLA assistant check](https://cla-assistant.io/Codecademy/docs?pullRequest=5434) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5434) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5434) it.

Hey @Tashuuuu please sign the CLA

**Comment by mamtawardhani** [comment]
> [CLA assistant check](https://cla-assistant.io/Codecademy/docs?pullRequest=5434) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5434) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5434) it.

Hey @Tashuuuu please sign the CLA

**Comment by Tashuuuu** [comment]
Signed

**Review by mamtawardhani — APPROVED** [review]
Thank you for contributing to Codecademy Docs @Tashuuuu, the entry is nicely written! 😄 

It looks good for a second round of review 🚀

**Review by Sriparno08 — APPROVED** [review]
Looks good, @Tashuuuu!

**Pull request merged**
