### PR TITLE
added content on primitive type coercion

### LINKED ISSUE #5182: [Edit] JavaScript Type Coercion
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Type Coercion` concept entry under JavaScript. The entry lives in `content/javascript/concepts/type-coercion/type-coercion.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a `Codebyte Example` section that provides a codebyte example demonstrating the concept in use
2) Ensure that the codebyte example is different than all the other examples in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by AlexFernandes04**
### Description
Edited the Type Coercion entry to include more information about how type coercion works both explicitly and implicitly with different primitive data types. 

### Issue Solved
Closes #5182 

### Type of Change
- Editing an existing entry (added additional content)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by SaviDahegaonkar — CHANGES_REQUESTED** [review]
Hey @AlexFernandes04 ,
I had a look at your file and suggested a few changes, please make them asap.


Thanks,
Savi

**Comment by AlexFernandes04** [comment]
@SaviDahegaonkar, thanks for the feedback, I have made suggested changes.

**Review by SaviDahegaonkar — COMMENTED** [review]
Hey @AlexFernandes04 ,
I am unable to find any Codebyte example section so please add one and let me know so that I can make this PR available for a second review.


Thanks,
Savi

**Comment by SaviDahegaonkar** [comment]
Hay @AlexFernandes04 ,
Have you made the changes I have suggested if not then please make them asap.

Thanks,
Savi

**Comment by AlexFernandes04** [comment]
@SaviDahegaonkar Thanks for the suggestions, I've made the appropriate edits

**Review by SaviDahegaonkar — APPROVED** [review]
Hey @AlexFernandes04 ,
LGTM! The entry looks good for a second round of review.


Thanks,
Savi

**Review by Sriparno08 — APPROVED** [review]
Looks good, @AlexFernandes04!

**Pull request merged**
