### PR TITLE
[EDIT] Added images to demonstrate background-blend-mode

### LINKED ISSUE #3532: [Edit] CSS [Edit] CSS Background: background-blend-mode
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like an edit a term within the CSS Animations entry. The entry lives in docs/content/css/concepts/animations/terms/background-blend-mode/background-blend-mode.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by antriksh-9**
### Description

I was assigned this [issue](https://github.com/Codecademy/docs/issues/3532).
Added images to demonstrate the example code blocks in background-blend-mode. 
Closes #3532.

### Type of Change

- Edited an existing entry (added images).
- Updated the background-blend-mode.md file.

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by caupolicandiaz — CHANGES_REQUESTED** [review]
@antriksh-9 The images need to be saved in the media folder, the path should similar to the this
https://raw.githubusercontent.com/Codecademy/docs/main/media/html-entity-tab.png

Update the location of the files and the filepaths in the entry

**Comment by antriksh-9** [comment]
Hey @caupolicandiaz I have updated the image file path.
Thanks!

**Review by caupolicandiaz — APPROVED** [review]
@antriksh-9 This is ready for a second review.

**Review by SSwiniarski — APPROVED** [review]
@antriksh-9 I made some minor spacing edits, otherwise it looks good.

**Comment by antriksh-9** [comment]
hey @SSwiniarski I found a small typo in the url of 3rd image.
It should be this : 
https://raw.githubusercontent.com/Codecademy/docs/main/media/background-blend-mode-example3.png
instead of this : 
https://raw.githubusercontent.com/Codecademy/docs/main/media/background-blend-mode-example2.png

**Comment by SSwiniarski** [comment]
@antriksh-9 Can you make a new pull request to fix it?

**Comment by antriksh-9** [comment]
Sure!
I will make a new pull request.
Thanks!

**Comment by antriksh-9** [comment]
Hey @SSwiniarski I have made the necessary changes (fixed the image url) and made a new pull request.
[New Pull request](https://github.com/Codecademy/docs/pull/3719)
Thanks!

**Pull request merged**
