### PR TITLE
[Edit] JavaScript Substring

### PR DESCRIPTION
**Pull request by plumbae**
### Description

- Added new codebyte example in substring.md in accordance with the issue description

### Issue Solved

-Closes issue #5037

### Type of Change

- Editing an existing entry (adding example)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by cigar-galaxy82** [comment]
Hi @plumbae can you please sign the CLA

**Comment by plumbae** [comment]
Sorry i missed the CLA signing but i have signed it now

**Review by cigar-galaxy82 — CHANGES_REQUESTED** [review]

**Comment by cigar-galaxy82** [comment]
Hi @plumbae thank you for contributing to Codecademy docs, I have suggested a few changes please modify.

**Comment by plumbae** [comment]
@cigar-galaxy82 i have made the proposed changes

**Review by cigar-galaxy82 — APPROVED** [review]

**Review by mamtawardhani — APPROVED** [review]
Thank you for contributing to Codecademy Docs @plumbae 😄 

The entry is ready to be merged! 🚀

**Pull request merged**
