### PR TITLE
feat: created codebyte example

### LINKED ISSUE #4968: [Edit] JavaScript Rest Parameters
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `Rest Parameters` concept entry under JavaScript. The entry lives in `content/javascript/concepts/rest-parameters/rest-parameters.md`.

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a `Codebyte Example` section that provides a codebyte example demonstrating the concept in use
2) Ensure that the codebyte example is different than all the other examples in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by davialano**
### Description
I included a codebyte example to help and improve knowledge of rest parameters in JavaScript.

### Issue Solved

Closes #4968

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by davialano** [comment]
Hi @cigar-galaxy82, just for clarify, I have two accounts. Unfortunately, this problem occured where the commit was made under the wrong account. However, I have already corrected it using the access token.

**Comment by cigar-galaxy82** [comment]
Hi @davialano thank you for contributing to Codecademy docs, I have suggested a few changes please modify.

**Comment by davialano** [comment]
Hi @cigar-galaxy82 can u be more specific? What do I need to change?

**Comment by davialano** [comment]
I don't know if your suggestion was to I adjust the format with yarn and prettier, but there it is.

**Comment by cigar-galaxy82** [comment]
Hi @davialano 

In the Codebyte example there is a line gap after line 101 so just remove that.

**Review by cigar-galaxy82 — APPROVED** [review]

**Review by Sriparno08 — APPROVED** [review]
Looks good, @davialano! 👍

**Pull request merged**
