### PR TITLE
[Entry] Create Git `add` and `status` commands

### PR DESCRIPTION
**Pull request by Pandz18**
### Description

Created files for the explanation and usage of the git add and git status commands

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by Pandz18** [comment]
Hey, if there's anything I'm missing anything or want me to change something, please feel free to let me know.
Cheers!

**Comment by Dusch4593** [comment]
Hi, @Pandz18. Thank you for these entries. I'd be happy to do the first review, which should be finished in the next 24 hours. 

In the meantime, could you check the two remaining list items in your PR form? This is just so that 8 out of the 8 tasks will be checked and completed.

**Comment by Pandz18** [comment]
@Dusch4593 thank you for that, I have made the changes to the git add file, is that fine? Please let me know if you want me to change something!

**Comment by Pandz18** [comment]
> > sure , will do, also regarding the example for git status, can I ask the reader to refer to the git add.md as I've kind of used it over there as an example? Or would you want me to make a new example for this?
> 
> Good point! Once the entry for `git add` is live on the [Docs Git section](https://www.codecademy.com/resources/docs/git) we'll hyperlink it. But don't have to worry about that for now.

hey sure, I'm trying to push but this is popping up
```
Permission to Codecademy/docs.git denied to Pandz18.
fatal: unable to access 'https://github.com/Codecademy/docs.git/': The requested URL returned error: 403
```

**Comment by Dusch4593** [comment]
Hey @Pandz18 I found this article in the GitHub Docs about the error you are getting. You should give it a look. I have a feeling your SSH connection between git and GitHub might not be solid?

https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey#verify-the-public-key-is-attached-to-your-account

**Comment by Pandz18** [comment]
> @Pandz18 I'm sorry about this. I'm still investigating what could possibly be preventing you from pushing changes. I had a question, though. When you cloned your fork of `docs` to your local computer, did you do so with HTTPS (https://github.com/Pandz18/docs.git) or SSH ([git@github.com](mailto:git@github.com):Pandz18/docs.git)?
> 
> Also did you clone the fork (`Pandz18/docs`) or the original repo? (`Codecademy/docs`)

Hey, I've connected my Pandz18/docs to Visual Studio code .

**Comment by Pandz18** [comment]
> > Hey, I've connected the original repo (`Codecademy/docs`) to Visual Studio code .
> 
> That might be what's causing the issue. You don't have write-permissions to push changes directly to the original repo.
> 
> Try cloning your _fork_ (`Pandz18/docs`) into VS Code with the HTTPS link, makes changes there, and then push back up to that fork's branch (in your case, it's `Pandz18:Git-add-and-status`).
> 
> Could you write the complete command you're using to push your changes?

Hey sure, will do that, sorry for the trouble. It's midnight over here, so I'll try this first thing in the morning and will update you. 

I mean in a short way create file->git add -> git commit -> git push

**Comment by Pandz18** [comment]
> Absolutely!

Hey, so I've cloned my fork and pushed the changes and it showed the changes in my GitHub fork too, yet when I click on the files in this PR, it still doesn't show the changes.

**Comment by Pandz18** [comment]
> Hey, @Pandz18 so happy we were able to work out the git branch issue! I looked over your changes and left some additional comments/suggestions for you to look at and resolve. This is _really_ coming along, though. Thank you, again, for your work on this! 😄 😄

Hey, @Dusch4593 same here! I have seen that and have added a comment to your comment 😄 . It indeed is! It's been a pleasure, thank you for bearing with me and helping me through this and making this an amazing experience, truly appreciate it, thank you! I'm still a student but will still definitely try to contribute wherever I can with the knowledge I have, have an amazing day/evening Dusch, thank you again!

**Comment by Pandz18** [comment]
> Hey, @Pandz18 I went ahead and implemented some of those changes since you went through a lot with the branching issue earlier. This way, I can approve the changes and complete Review 1. On to Review 2.

Hey, sure thank you. Is there anything else that I need to do or can I begin with a new topic?

Again thanks for all the help and bearing with me 😄

**Comment by Dusch4593** [comment]
Hey @Pandz18! We're gonna perform one more review of these entries before merging. Let's give it until Monday for the next review to take place.

**Comment by Pandz18** [comment]
> Hey @Pandz18! We're gonna perform one more review of these entries before merging. Let's give it until Monday for the next review to take place.

Hey, sure no worries!

**Comment by yangc95** [comment]
> I did make some changes too, do let me know if I can add anything. I didn't know what more content I could add for the status command file so I ended it after the example.

Try the command that @Dusch4593 mentioned above. Also, I noticed that you're still making changes to your main branch rather than the PR branch "Git-add-and-status." I tried outlining a workflow that you can use when making changes on a text editor like VS Code.

**Comment by sonnynomnom** [comment]
Copying from Brandon:

Hey @Pandz18, just a heads up! We've switched from CircleCI to GitHub Actions! You'll want to merge the latest changes from `Codecademy/docs:main` into your fork and current/active branches. 

In your fork, after committing any changes you're working on, update your local `main` branch:

```
git checkout main
git pull upstream main
git push
```

Then, `checkout` into your local `golang/add-types` branch and do the following:

```
git checkout golang/add-types
git merge main
git push
```

This will catch your remote `main` and `golang/add-types` branches up with the `main` branch of the core `docs` repository and allow the tests to go forward! 😄

**Comment by Dusch4593** [comment]
Hey @jochenrui, fwiw if you get an issue on `upstream` about that remote repository not existing or some such, try this first:

```
git remote add upstream https://github.com/Codecademy/docs
```

Then, try the git commands Ithat Sonny mentioned earlier

**Comment by Dusch4593** [comment]
Hey @Pandz18, fwiw if you get an issue on upstream about that remote repository not existing or some such, try this first:

git remote add upstream https://github.com/Codecademy/docs
Then, try the git commands I mentioned earlier

**Comment by sonnynomnom** [comment]
Made some more updates: https://github.com/Codecademy/docs/commit/06d7091cb5d9afbf568d0671ee5d797845e9ad13

Mainly:

- No more than 2 items in CatalogContent metadata.
- FIle names need to be bolded.

@Pandz18 @Dusch4593 @yangc95 

We good!

**Comment by Pandz18** [comment]
> Made some more updates: [06d7091](https://github.com/Codecademy/docs/commit/06d7091cb5d9afbf568d0671ee5d797845e9ad13)
> 
> Mainly:
> 
> * No more than 2 items in CatalogContent metadata.
> * FIle names need to be bolded.
> 
> @Pandz18 @Dusch4593 @yangc95
> 
> We good!

Yay! Let's go! Thank you @sonnynomnom for fixing this and for helping me out along the way !

And thank you @Dusch4593 @yangc95 for helping me out too and for having so much patience with me!

I'll try to contribute the new file I created an issue for and I'll try to make it a smooth contribution 😅

**Pull request merged**
