### PR TITLE
Edit Contribution Guide

### PR DESCRIPTION
**Pull request by yangc95**
### Description

Add bullet point about PRs (that don't meet basic structure/criteria for review) will be removed from the queue after 2 weeks of no consistent effort for improving. For example, a PR that is mainly plagiarized and the contributor is unresponsive. Other issues may be a file that is submitted in another type of encrypted file or format that's not the standard format.

Not to deter contributors from making mistakes, questions are always welcome

### Type of Change

- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by yangc95** [comment]
@lucwhite I also remove a the `-f` for a forced push. This should not be necessary to force the action (or at least I don't use that unless I've done something wrong in the first place 😬 )

**Review by Dusch4593 — COMMENTED** [review]
@yangc95 This was all I could find. We should be good to merge after this 😄

**Comment by ethan-master-coding** [comment]
> ...content does not meet or pass standard formatting, quality, and plagiarism checks.

Umm... Will my PRs be closed if 2 checks are failing (since that's normally what happens) when I first open them?

**Comment by Dusch4593** [comment]
@ethan-master-coding Not when you first open them. As long as there is activity in the PR within a 2-week period, it doesn't matter how may checks may be failing. We just want to ensure that we see open PRs through to the end.

> PRs will be marked as **invalid** if there is no consistent activity within a **2-week period** on the contributor's part _and_ content does not meet or pass standard formatting, quality, and plagiarism checks.

**Comment by ethan-master-coding** [comment]
I have a question. If a PR that fixed a typo is closed am I allowed to open a PR making that exact change?

**Comment by Dusch4593** [comment]
@ethan-master-coding I don't quite understand your question? What do we mean opening a new PR that makes a change that was already made? Can we rephrase using [this recently merged PR of mine with a `typo` label](https://github.com/Codecademy/docs/pull/794/files) as a possible example?

**Comment by ethan-master-coding** [comment]
@Dusch4593 for example #729 is going to be closed soon due to no activity by the OP. Am I allowed to open a PR making that exact change once it is closed?

**Comment by Dusch4593** [comment]
Gotcha. If you mean open PRs that are _about_ to close due to inactivity, then yes you can totally create a new PR.

**Pull request merged**
