### PR TITLE
Fix punctuations

### PR DESCRIPTION
**Pull request by Helfese**
### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by ishg-153** [comment]
Hey @Helfese! We appreciate your interest in contributing to Codecademy Docs. Contributors are expected to request to work on available issues (even if you create the issue yourself) and wait to be assigned to it before creating a PR.

As this PR and its corresponding issue edits documentation related to Codecademy Docs, I will need consent from the team to move forward with it. Until then you can ask to work on any of the [available issues](https://github.com/Codecademy/docs/issues?q=is%3Aissue+is%3Aopen+-label%3Aclaimed) that interest you.

**Comment by KTom101** [comment]
@ishg-153 @dakshdeepHERE Since there are only punctuation changes, it's ok to proceed with this.

**Review by ishg-153 — APPROVED** [review]
@Helfese This looks good for a second review.

**Review by avdhoottt — APPROVED** [review]
LGTM 🚀

**Pull request merged**
