### PR TITLE
Fixed a typo found in the JavaScript Comments content on line 34

### PR DESCRIPTION
**Pull request by codesciousness**
### Description

In the JavaScript Comments file the second sentence on line 34, which explains the usage of comments, should be edited to be better understood.

This is the original sentence: "Comments are good ways for a variety of reasons like explaining a code block or indicating some hints, etc."

I removed the word "ways" to improve the grammar.  It now reads: "Comments are good for a variety of reasons like explaining a code block or indicating some hints, etc."

This PR closes issue #1190 that I created before.

Thanks!

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — APPROVED** [review]
@codesciousness Looks fine as is to merge.

**Review by Dusch4593 — APPROVED** [review]
@codesciousness LGTM as well. 👍🏻

Made some tiny edits to the opening sentence in 26adb6fcd689120fa00c49366a8ee9b306be7ff9.

**Comment by Dusch4593** [comment]
Thank you for contributing to Codeacdemy Docs, @codesciousness! Your changes should now be live: https://www.codecademy.com/resources/docs/javascript/comments

It looks like your Codecademy profile is anonymous on the live page. If you'd like your profile to be added, you'll need to add your GitHub username to your Codecademy profile, log out of Codecademy, and back in through GitHub. Let me know if you'd like to do this and I'd be happy to help. 😄

**Comment by Dusch4593** [comment]
@codesciousness Yup, I'm seeing it now!

**Comment by Dusch4593** [comment]
@codesciousness Yup, I'm seeing it now!

Screen Shot 2022-10-31 at 12 44 58 PM

**Pull request merged**
