### PR TITLE
[Term Entry] Python math-module math.isinf() #5028

### LINKED ISSUE #5028: [Term Entry] Python math-module math.isinf()
### Reason/inspiration (optional)

We would like a new term entry on the `math.isinf()` method of the [`math-module`](https://www.codecademy.com/resources/docs/python/math-module) concept in Python. The entry should go in a new file under `docs/content/python/concepts/math-module/terms/math-isinf/math-isinf.md`

The entry should include the following:

- A description of the term
- A ##Syntax section that includes the syntax of the method and its details
- An ##Example section that includes a ```py ``` codeblock and ```shell ``` that shows the example output.
- A ##Codebyte Example to show the working of the method

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by chmstpromotheus**
### Description

I've added a new entry on the **`math.isinf()`** method in the `math` module of Python. This entry includes a description of the function, syntax, an example, and a Codebyte example. The new entry is located in the file `docs/content/python/concepts/math-module/terms/math-isinf/math-isinf.md`.

### Issue Solved

Closes #5028

### Type of Change

- [x] Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

---

### CODE REVIEW

**Review by SaviDahegaonkar — CHANGES_REQUESTED** [review]
Hello @chmstpromotheus ,
The entry is nicely written. I have suggested a few changes please check them asap possible so that I can approve your PR. If you are facing any problems regarding this, please feel free to discuss it.

Thanks,
Savi

**Comment by chmstpromotheus** [comment]
Hi,

Waiting for your further review!

Thanks in advance!

**Review by SaviDahegaonkar — APPROVED** [review]
Hey @chmstpromotheus ,
LGTM!!, I hereby approve this and it is ready for the second round of review.

**Comment by mamtawardhani** [comment]
> [CLA assistant check](https://cla-assistant.io/Codecademy/docs?pullRequest=5142) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=5142) before we can accept your contribution.You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=5142) it.

@chmstpromotheus please sign the CLA

**Comment by chmstpromotheus** [comment]
Hi @mamtawardhani, the CLA is signed

**Review by mamtawardhani — APPROVED** [review]
Thank you for contributing to Codecademy Docs @chmstpromotheus! 😄 

The entry is ready to be merged! 🚀

**Pull request merged**
