### PR TITLE
Completed [Term Entry] Dart List .cast() #4297

### PR DESCRIPTION
**Pull request by nbarnhouse**
### Description

Added .cast() method information to Dart lists.

### Issue Solved

Closes [#4297](https://github.com/Codecademy/docs/issues/4297)

### Type of Change

- Adding a new entry

### Checklist

- [ x] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by Sriparno08 — CHANGES_REQUESTED** [review]
Hey @nbarnhouse, thanks for contributing to Codecademy!

I've listed all the modifications that you need to make in your entry below:

**Comment by nbarnhouse** [comment]
Hi @Sriparno08 let me know if there is anything else I need to change, thanks!

**Review by Sriparno08 — APPROVED** [review]
Looks good for a second review, @nbarnhouse! 👍

**Review by mamtawardhani — APPROVED** [review]
Thank you for contributing to Docs @nbarnhouse 😄 

The entry is ready to be merged 👍🏻

**Pull request merged**
