### PR TITLE
Update animation.md

### LINKED ISSUE #5133: [Edit] CSS: Animation
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

We would like to edit the `Animation` concept entry under CSS. The entry lives in `docs/content/css/concepts/animations/terms/animation/animation.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:

- Correct the typo on line 23, it says "where `<value>` can be and of the following keywords:". Change the "and" to "any"

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by vlrnsnk**
Change for a correct keyword

### Description

Fix typo in the content.

### Issue Solved

Closes #5133

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x ] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [ x] I have performed a self-review of my own writing and code.
- [ x] I have checked my entry and corrected any misspellings.
- [ x] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by vlrnsnk** [comment]
I want to work on this issue

**Comment by vlrnsnk** [comment]
I want to work on this issue

**Review by mamtawardhani — APPROVED** [review]
Hey @vlrnsnk thank you so much for contributing and highlighting the issue. The PR looks good for a second round of review! 🚀

**Comment by mamtawardhani** [comment]
@Sriparno08 assigning this to you so that this can be closed at the earliest. Thank you 😃

**Review by Sriparno08 — APPROVED** [review]
Looks good, @vlrnsnk!

**Pull request merged**
