### PR TITLE
New Java Errors term entry: Arithmeticexceptions

### PR DESCRIPTION
**Pull request by tgreencc**
### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by SSwiniarski** [comment]
@tgreencc you need to address the following issues with this PR before it gets reviewed:

- Sign the [CLA](https://cla-assistant.io/Codecademy/docs?pullRequest=1933).
- Complete the metadata, it is missing the description.
- Complete the body of the entry. Right now there's no content.

**Comment by tgreencc** [comment]
@SSwiniarski Hey thanks for the feedback. I was just doing a test run of the contribution process because my team is working on improving the contribution guide. @KTom101 will fill in the actual content!

**Comment by KTom101** [comment]
@SSwiniarski I've added the content.

**Review by caupolicandiaz — APPROVED** [review]
@tgreencc LGTM

**Comment by yangc95** [comment]
🙌 @tgreencc live link: https://www.codecademy.com/resources/docs/java/errors/arithmeticexception

Screenshot 2023-04-25 at 9 30 08 PM

> It looks as if you're anonymous. If you want to be credited follow the instructions below to add your GitHub username to your Codecademy profile. If not, there is nothing more you need to do.
> 
> 
> To add your GitHub username to your Codecademy profile:
> 
> 1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:
> 
> 
> 
> Make sure to set your visibility to “everyone”.
> 
> 2.) Then log out and log back into Codecademy using your GitHub login:
> 
> githublogin
> 
> If the steps above do not work, it may be due to an email or local configuration issue.
> 
> In addition, we may reach out in the future if any adjustments to these entries are required.
>

**Pull request merged**
