### PR TITLE
Shorten the description of the pointer description to less than 160 c…

### LINKED ISSUE #5488: [Edit] C++ pointers
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `pointers` concept entry under C++. The entry lives in `content/cpp/concepts/pointers/pointers.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Shorten the description to not more than 160 characters
2. Fix any typo in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by jvara34**
…haracters. Also checked for any typos in the entry

### Issue Solved
Closes #5488 

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by mamtawardhani** [comment]
Hey @jvara34 Please sign the CLA so that this entry can get merged

**Review by mamtawardhani — APPROVED** [review]
Thank you @jvara34 for contributing to Codecademy Docs! The entry looks good for a second round of review! 🚀

**Comment by Sriparno08** [comment]
Hey @mamtawardhani, I've used it a couple of times and the checks passed successfully. Plus, there is nothing in the style guide that suggests us to avoid using backticks in the description. So, I guess we can use it.

**Review by Sriparno08 — APPROVED** [review]
Looks good, @jvara34!

**Pull request merged**
