### PR TITLE
Update creational-design-patterns.md

### PR DESCRIPTION
**Pull request by afghan-tech-bro**
### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by yangc95** [comment]
I see this is your first contribution! Wanted to first thank you for being proactive and putting in a PR for the error you noticed. Make sure to sign the license/cla agreement first and foremost 🙏

@afghan-tech-bro Thanks for noticing this link error 🙌 Albeit the change you made here is accurate, for consistency purposes, can we actually go into the entry that is linked here and change the folder/file name from `abstract-factory` and `abstract-factory.md` to `abstract-factory-pattern` and `abstract-factory-pattern.md`? This should be a quick merge after ☺️

**Comment by KTom101** [comment]
@afghan-tech-bro Hi, just checking in to see if you need help making any of the changes above.

**Comment by yangc95** [comment]
> @afghan-tech-bro Hi, just checking in to see if you need help making any of the changes above. 

Thanks @KTom101 for putting this back on our radar! Let us know @afghan-tech-bro if you'd like any assistance, we can help make that change directly to this PR if you allow us to 🙏🏻

**Comment by yangc95** [comment]
@afghan-tech-bro hope all has been well, unfortunately this PR may have to be marked as invalid and will be closed shortly after. If you'd like to contribute again, please do

**Pull request closed without merging**
