### PR TITLE
[WIP] Dev go interfaces

### LINKED ISSUE #1503: [Concept Entry] Go: Interfaces
### Reason/inspiration (optional)

We would like a new term entry for [Go](https://www.codecademy.com/resources/docs/go) about Interfaces.

The entry should go in a new file in docs/content/go/concepts/interfaces/interfaces.md

The entry should

Describe what interfaces are and their relationship to types.
Show a type implementing an interface.
Have a syntax section illustrating an interface structure with a \`\`\`pseudo code block.
Have an example showing an interface in use with a \`\`\`go code block.
Have a runnable codebyte example in a \`\`\`codebyte/golang block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Concept Entry for Existing Topic

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by Pavan-Nambi**
### Description
closes  #1503

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by Pavan-Nambi** [comment]
i will format code (failing tests) after dng requested changes all once

**Comment by SSwiniarski** [comment]
@Pavan-Nambi you need to sign the CLA. And to do that, this has to be committed by a GitHub user. You may need to add the email to your Github account.

**Comment by Pavan-Nambi** [comment]
> @Pavan-Nambi you need to sign the CLA. And to do that, this has to be committed by a GitHub user. You may need to add the email to your GitHub account.

hey i have signed CLA before... but even when i try to sign now its saying to add gmail but my gmails are added and looking good..

**Comment by Pavan-Nambi** [comment]
## from terminal 

```
docs on  dev-go-interfaces is 📦 v1.0.0 via  v18.14.0 
❯ git config --global user.email
pavannambi999@gmail.com

docs on  dev-go-interfaces is 📦 v1.0.0 via  v18.14.0 
❯ git config --global user.name
Pavan-Nambi

docs on  dev-go-interfaces is 📦 v1.0.0 via  v18.14.0 
❯ git config user.email
pavannambi999@gmail.com
```

## in github 

image

**Comment by Pavan-Nambi** [comment]
hey appologies for this ,
i realise this look unprofessional but can this review wait a day , i have few more things i want to add
i will complete by tomorrow this time or in few hours and ping `SSwiniarski`  ok , just few more lines nd code

thankyou

**Comment by SSwiniarski** [comment]
@yangc95, @KTom101, @caupolicandiaz any ideas how to solve this?

**Comment by yangc95** [comment]
@Pavan-Nambi Would you be able to log onto: https://cla-assistant.io

And check "View my Signed CLAs." If you have this repo on there already, try deleting and Re-"Configure CLA" either through the cla-assistant site or through the link provided above [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1680)](https://cla-assistant.io/Codecademy/docs?pullRequest=1680):
Screen Shot 2023-02-19 at 7 21 16 PM

**Comment by Pavan-Nambi** [comment]
done , not working...

> @Pavan-Nambi Would you be able to log onto: https://cla-assistant.io
> 
> And check "View my Signed CLAs." If you have this repo on there already, try deleting and Re-"Configure CLA" either through the cla-assistant site or through the link provided above [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=1680): Screen Shot 2023-02-19 at 7 21 16 PM

**Comment by Pavan-Nambi** [comment]
```
Signed CLA's
StatusRepository  CLADate of Signature  
[Codecademy / docs](https://github.com/Codecademy/docs)CLA.mdFebruary 20, 2023
```
as you can see date is feb 20 i deleted previous signature and re-did 

idk why it is still in pending

**Comment by Pavan-Nambi** [comment]
should i try redoing pull request closing this?

**Comment by SSwiniarski** [comment]
@Pavan-Nambi if you don't mind, it will probably solve the CLA problem.

**Comment by Pavan-Nambi** [comment]
tested at #1704 , not worked should i create issue and ask [here](https://github.com/cla-assistant/cla-assistant/issues/new)?
@SSwiniarski

**Comment by Pavan-Nambi** [comment]
reopened this as majority of conversation happened here.. reg issue

**Comment by KTom101** [comment]
@Pavan-Nambi Taking a look at the patches, it looks like there is a typo in the email associated with commit [40bbedc](https://github.com/Codecademy/docs/pull/1680/commits/40bbedc8577cd15c0746a8dca9cd9170d7e5f745) labeled "init". Take a look at the [patch for commit 40bbedc (init)](https://github.com/Codecademy/docs/commit/40bbedc8577cd15c0746a8dca9cd9170d7e5f745.patch) and compare it to the [patch for commit 418f48f (interfaces)](https://github.com/Codecademy/docs/commit/418f48ff9e72ec8431ad7b79e719cb4f2c7d8d50.patch). The email of the first patch is missing the `@` in the email. You can also see at the top of this page that your profile icon is missing for that commit:

Screen Shot 2023-02-22 at 1 09 45 AM


Since an interactive rebase is never advised, the safest way to fix this is to open another PR but with a new branch. So let's try opening a new PR again following these instructions:

1. I believe you have done this [already](https://github.com/Codecademy/docs/pull/1680#issuecomment-1436022457), but ensure the correct email and username are configured with Git and GitHub.

2. On GitHub, make sure the `main` branch on your fork of this repo is synced
Screen Shot 2023-02-22 at 1 37 42 AM

On the terminal/command line run:

```
git checkout main
git pull
```

3. With the `main` branch now caught up both locally and remotely, create a brand new branch, like so:

`git checkout -b go-interfaces`

4. Then, transfer the file over. Remember to make the new folder named `interfaces` under `content/go/concepts/` and then add the `interfaces.md` file into the folder.

5. Add, commit, and then push these additions. Then, make the new PR on GitHub.

**Comment by Pavan-Nambi** [comment]
thankyou @KTom101

**Comment by Pavan-Nambi** [comment]
closing this as this is resolved

**Comment by KTom101** [comment]
@Pavan-Nambi You're welcome!

**Pull request closed without merging**
