### PR TITLE
Fixed issue templates

### PR DESCRIPTION
**Pull request by ethan-master-coding**
### Description

Made it so when you make an issue you are not required to check the labels added box because most people that make issues don't have access to adding them.
### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by Dusch4593** [comment]
> Made it so when you make an issue you are not required to check the labels added box because most people that make issues don't have access to adding them.

@ethan-master-coding I think that this permission is by design? 

I'm fine with turning off the requirement, but fwiw, each issue template comes with at least one label already ready added which satisfies the labels check. 

- "bug" in `bug_reports.yml`
- "enhancement" and "typo" in `entry_edit.yml`
- "new entry" in `entry_request.yml`

I was thinking, though, should we maybe edit the spacing on line #3 in each file (the space on the left side of the colon `:` in `title`) to look like this?

~~`title: "[Entry] Topic : Entry Name"`~~ -> `title: "[Entry] Topic: Entry Name"`

**Comment by yangc95** [comment]
Some other labels may apply as well. For example, if it's a new entry on a language, there's a label for that.

Approving this change! What do you think @Dusch4593?

**Comment by Dusch4593** [comment]
@yangc95 LGTM! Lemme push a few last-minute changes and we'll be good to merge!

**Review by Dusch4593 — APPROVED** [review]
@yangc95 good to go!

**Comment by Dusch4593** [comment]
Congrats, @ethan-master-coding, your changes are now merged! Thank you very much 🙏

**Pull request merged**
