### PR TITLE
FIX: update typo

### PR DESCRIPTION
**Pull request by arinze19**
### Description

Update and fix typographical errors on cpp-resources `functions.md` file 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by KTom101 — APPROVED** [review]
@arinze19 Thank you for finding this! 😁

**Comment by KTom101** [comment]
@arinze19 Thanks for contributing! Changes are [live](https://www.codecademy.com/resources/docs/cpp/functions) now. I'm noticing you're not listed as a contributor, however.

Screen Shot 2023-02-11 at 3 13 44 PM

If you wish to be added as a contributor you have to add your GitHub username to your Codecademy profile. I've added how to do this below:

1.) Add your GitHub Username to your Codecademy Profile Details, you can get there on your desktop by pressing on your profile picture in the upper right-hand corner and selecting "Profile" in the drop-down box:

[￼](https://user-images.githubusercontent.com/40783324/214706373-b2b0397b-da7d-4007-95f8-56ca8686ac24.png)

2.) Then log out and log back into Codecademy using your GitHub login:

[￼](https://user-images.githubusercontent.com/40783324/214706585-52d7394a-a1ce-4275-8674-4d3dc125b287.png)

Let me know if you need any help if you decide to do so! 😁

**Comment by arinze19** [comment]
Hey @KTom101 I used a gmail account to register my account. just linked my github in the settings. should that still work?

Screenshot 2023-02-11 at 21 50 57

**Comment by KTom101** [comment]
@arinze19 Looks like it worked. Are you going by the username @Laurent54?

image

**Comment by arinze19** [comment]
Oh yes! Thank you!!

**Pull request merged**
