### PR TITLE
[Edit] Python Iterators: `iter()`

### PR DESCRIPTION
**Pull request by KTom101**
### Description

Edit for Python: [`iter()`](https://www.codecademy.com/resources/docs/python/iterators/iter) so correct output is shown for example. Currently, the output for the section on sentinel is being shown and nothing is shown for the sentinel example.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — APPROVED** [review]
@KTom101 this looks good, but theres another issue. We just had a PR merged that covers `iter()` as a term under Python Built-in Functions. Should we leave it, try to merge them, or do something else?
@yangc95, @caupolicandiaz, @HishamT?

**Review by HishamT — APPROVED** [review]
LGTM!

**Comment by HishamT** [comment]
I'm not entirely sure what to do with this entry. There is another entry about `iter()`.

**Comment by KTom101** [comment]
@HishamT @SSwiniarski Thanks for letting me know! I'll look into combining the two so it simply lives as a built-in function. I don't think it being a term entry under iterators is a good spot for it. I just became aware of it since these errors were submitted through a feedback comment. Let me know if you have anything against `iter()` it remaining as a built-in function.

**Comment by yangc95** [comment]
@KTom101 the only other relevant method I found that can go under "Iterators" is `next()`. In which case there would just be two terms under that topic.

I think, combining them would be best under iterators, in which case we would need the original author for the newer PR https://github.com/Codecademy/docs/pull/2196 to delete the one within built-in functions and incorporate it into the older entry.

**Comment by SSwiniarski** [comment]
Has anyone reached out to @nikolaspoczekaj about this?
@yangc95, @KTom101, @HishamT?

**Comment by KTom101** [comment]
@yangc95 To clarify, we don't want this to fall under built-in functions and be linked out from the Iterators concept page like how we did for Python:[Sets](https://www.codecademy.com/resources/docs/python/sets). The set() function remained under built-in functions and was linked out from the Sets concept page.

**Comment by yangc95** [comment]
@SSwiniarski @KTom101 Sure, I can reach out to the author of the built-in iter() function entry. For the set entry, I can put in an edit issue since that was created internally.

**Comment by SSwiniarski** [comment]
Closing this as #2312 covers it.

**Pull request closed without merging**
