### PR TITLE
edit: add Codebyte example to transpose.md

### LINKED ISSUE #5375: [Edit] Python:NumPy NumPy - Built-in-functions - `.transpose()`
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `.transpose()` term entry under NumPy. The entry lives in `content/numpy/concepts/built-in-functions/terms/transpose/transpose.md`

Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md) and [markdown style](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) guide when working on the PR for this issue.

Please:

1. Add a ## Codebyte Example section that provides a codebyte example demonstrating the concept in use
2. Ensure that the codebyte example is different than all the other examples in the entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by ChinoUkaegbu**
### Description

Adds Codebyte example to numpy transpose

### Issue Solved

Closes #5375

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by mamtawardhani — APPROVED** [review]
Thank you for contributing to Codecademy Docs @ChinoUkaegbu 😄 

The entry is nicely written and is ready for a second round of review 🚀

**Comment by mamtawardhani** [comment]
For future reference please make sure that you raise a PR only after an issue has been assigned to you @ChinoUkaegbu 
Thank you 😃

**Comment by ChinoUkaegbu** [comment]
Noted, thank you :)

**Review by SaviDahegaonkar — APPROVED** [review]
Hey @ChinoUkaegbu ,
LGTM! Thank you for Contributing to Docs.

Thanks,
Savi

**Pull request merged**
