### PR TITLE
add rectangle tag for issue

### PR DESCRIPTION
**Pull request by rriver2**
https://github.com/Codecademy/docs/pull/1130

### Type of Change

- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by yangc95** [comment]
I'm unsure if this tag is needed as it may not be applicable across multiple entries. What to you think @Dusch4593 @SSwiniarski?

**Comment by SSwiniarski** [comment]
@yangc95 It seems a little too narrow.

**Comment by Dusch4593** [comment]
cc: @yangc95 @SSwiniarski @rriver2

If we're talking about the https://github.com/Codecademy/docs/labels/hacktoberfest label, then I agree that it shouldn't be here. The single change in the `tags.md` file for this pull request isn't sufficient, in my view, for that.

For @rriver2, there are two ways we can go from here:

- We could add an https://github.com/Codecademy/docs/labels/invalid label to this PR and merge as-is.
  - The only meaning behind "invalid" is that the PR will still be merged into `Codecademy/docs:main`, but it won't count towards Hacktoberfest.
- We could close this PR and you could include the new tag change in #1130.
  - And #1130 _will_ count toward Hacktoberfest! 🚀 

Let us know what we should do and we'll be happy to assist. 😄

**Comment by yangc95** [comment]
@Dusch4593 @SSwiniarski

I think the best choice of action would be marking this as invalid, but we'll go ahead and keep the two PRs separate. I'll link this PR in the comments for #1130 

cc: @rriver2

**Review by yangc95 — APPROVED** [review]

**Pull request merged**
