### PR TITLE
[Edit] Template metadata 

### PR DESCRIPTION
**Pull request by caupolicandiaz**
### Description

I've updated the docs templates so that the description text ends with a period (per our std) and that the second content slug end in an "s" as required.

### Type of Change

- Updating the documentation

### Checklist

- [*] All writings are my own.
- [*] My entry follows the Codecademy Docs style guide.
- [*] My changes generate no new warnings.
- [*] I have performed a self-review of my own writing and code.
- [*] I have checked my entry and corrected any misspellings.
- [*] I have made corresponding changes to the documentation if needed.
- [*] I have confirmed my changes are not being pushed from my forked `main` branch.
- [*] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [*] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by KTom101 — APPROVED** [review]
@caupolicandiaz LGTM 👍

**Review by CBID2 — APPROVED** [review]
Looks great! :) LGTM! :)

**Review by SSwiniarski — APPROVED** [review]
@caupolicandiaz Looks good!

**Review by yangc95 — APPROVED** [review]
LGTM

**Pull request merged**
