### PR TITLE
[Term Entry] SwiftUI ViewModifier: `.italic()`

### PR DESCRIPTION
**Pull request by matthewogtong**
### Description

- Created new terms folder inside the `ViewModifier` folder.
- Created a new entry for the SwiftUI ViewModifier `.italic()` method.
- Added new `SwiftUI ViewModifiers` tag inside `tag.md`

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by yangc95 — APPROVED** [review]
@matthewogtong Thanks for this entry and tag addition! This LGTM as is 👍

**Review by SSwiniarski — APPROVED** [review]
@matthewogtong: Looks good to me as is.

**Comment by yangc95** [comment]
@matthewogtong Thanks for this entry! live link: https://www.codecademy.com/resources/docs/swiftui/viewmodifier/italic
Screen Shot 2023-01-02 at 2 00 06 AM
Looks like you're all set.

cc: @SSwiniarski

**Comment by matthewogtong** [comment]
@SSwiniarski @yangc95 Awesome, thank you for reviewing and merging my PR.

**Pull request merged**
