### PR TITLE
[Term Entry] Java ArrayList .isEmpty()

### LINKED ISSUE #4339: [Term Entry] Java ArrayList .isEmpty()
### Reason/inspiration (optional)

Please add the `.isEmpty()` method as a new term entry for [ArrayList](https://www.codecademy.com/resources/docs/java/array-list)�. Provide the entry in a markdown file and place under the file path `content/java/concepts/array-list/terms/isEmpty/isEmpty.md`

The entry should have the following:
�	An introductory paragraph about what the method is and does.
�	A syntax section with a pseudo code block with an explanation of it.
�	An example showing the method in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by andersooi**
### Description

- Created new term entry for Java ArrayList .isEmpty()

### Issue Solved

- Closes #4339 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by Sriparno08 — COMMENTED** [review]
Hey @andersooi, thanks for contributing to Codecademy!

I've listed all the modifications that you need to make in your entry below:

**Comment by Sriparno08** [comment]
Hey @andersooi, please make the suggested changes so that we can review the entry and move on to the second review.

**Review by Sriparno08 — APPROVED** [review]
Looks good for a second review 👍

**Review by ishg-153 — APPROVED** [review]
@andersooi Great work! Ready to merge.

**Pull request merged**
