### PR TITLE
Term entry c sharp abs

### LINKED ISSUE #1605: [Term Entry] C# Math Functions `.Abs()`
### Reason/inspiration (optional)

We would like a new term entry for [C#](https://www.codecademy.com/resources/docs/c-sharp) about the `Math.Abs()` method.

The entry should go in a new file in `docs/content/c-sharp/concepts/math-functions/terms/abs/abs.md`

The entry should

- Have a syntax section illustrating the method with a ` ```pseudo ` code block.
- An example showing the method in use with a ` ```cs ` code block.
- A runnable codebyte example in a ` ```codebyte/csharp ` block.

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by cslylla**
### Description

- Added new term for C# Math functions: .Abs()
- Closes #1605 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — APPROVED** [review]
@cslylla, looks good as is. Sending it to a second review.

**Review by caupolicandiaz — APPROVED** [review]
@cslylla LGTM

**Comment by SSwiniarski** [comment]
Live link here: https://www.codecademy.com/resources/docs/c-sharp/math-functions/abs

Strangely, @caupolicandiaz is showing up as the only contributor. Anyone know why this happened? @KTom101 @yangc95 @caupolicandiaz 

image

**Comment by KTom101** [comment]
> Live link here: https://www.codecademy.com/resources/docs/c-sharp/math-functions/abs
> 
> 
> 
> Strangely, @caupolicandiaz is showing up as the only contributor. Anyone know why this happened? @KTom101 @yangc95 @caupolicandiaz 
> 
> 
> 
> image
> 
> 
> 
> 

@SSwiniarski Thanks! This has been sent along to engineering. I'll let you know when I hear a response.

**Pull request merged**
