### PR TITLE
[EDIT] HTML Add Media Videos 

### PR DESCRIPTION
**Pull request by DakuwoN**
### Description

- Added image showing an example of the content being explained
- Closes issue #3288 

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by dakshdeepHERE** [comment]
I can see another file pushed with this PR from this dir ```content/java/concepts/calendar/terms/getDisplayName/getDisplayName.md```. Is this related to some other PR? Please remove this file commit from this branch and push it again.

**Review by dakshdeepHERE — COMMENTED** [review]
Remove the Java file from this PR. Otherwise, everything looks fine.

**Comment by DakuwoN** [comment]
Wow, I am so sorry, I did not realize that! Fixing it up now.

**Comment by dakshdeepHERE** [comment]
@DakuwoN looks good

**Review by SSwiniarski — APPROVED** [review]
@DakuwoN Looks good.

**Comment by DakuwoN** [comment]
Thank you guys!

**Pull request merged**
