### PR TITLE
SwiftUI - Adds .title2/ .title3 information, link to the fontWeight modifier

### PR DESCRIPTION
**Pull request by jmar3308**
### Description

I am making this change as a requirement of the Git course in the iOS Developer/Swift/SwiftUI path.
This change adds title2 and title3 to the list of standard fonts and adds a link to the fontWeight modifier in SwiftUI

### Issue Solved

N/A This does not tie to any of the Issues

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by mohitO12-dev — APPROVED** [review]
approved

**Comment by ishg-153** [comment]
@jmar3308 It seems you used a different email (the one connected to your command line) to make this commit. Please add the same email to your GitHub account and sign the CLA.

**Comment by ishg-153** [comment]
@jmar3308 It's been a week. If you don't respond in a couple of days this PR will be closed

**Comment by jmar3308** [comment]
@ishg-153 Thank you for the message. I have changed my user email and name to match the account using git config and signed the CLA. The email linked to the original commit was a Macbook local email, which is unable to sign the CLA. 

If this does not work due to the Macbook email, I have also created a new branch, located here: https://github.com/Codecademy/docs/pull/4769 with the exact same changes, entirely on the correct email.

**Comment by ishg-153** [comment]
Alright @jmar3308! The new PR seems to be okay in terms of the CLA issue.

**Comment by ishg-153** [comment]
Closing this PR as this is a duplicate

**Pull request closed without merging**
