### PR TITLE
Issue #3231: new media added

### PR DESCRIPTION
**Pull request by nsLittle**
### Type of Change

- Updating the documentation

### Checklist

- [x ] All writings are my own.
- [x ] My entry follows the Codecademy Docs style guide.
- [x ] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [x ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by ishg-153 — CHANGES_REQUESTED** [review]
@nsLittle A couple of things..
1. When I suggest changes push them to the same branch (also good thing you created a separate branch as working on the `main` creates problems) this means no need to create a new PR every time.
2. You need to remove the images you had previously added to the media folder- `logo.png`, `open-positions.png`, and `text-link.png`.
3. Since you will be adding gifs, download the gif and add it to the `media` folder then link it in the following format
`https://raw.githubusercontent.com/Codecademy/docs/main/media/` followed by the gif name.

**Comment by ishg-153** [comment]
@nsLittle I checked out the loom video link you added, and it's great that you took the time to create that. But for the gif, we expect something like [the example here](https://www.codecademy.com/resources/docs/uiux/fitts-law). I'm sure if you download and cut the video you can use that to create a gif using any video to gif website available.

**Review by ishg-153 — CHANGES_REQUESTED** [review]
@nsLittle the gifs look great!

Can you please remove the previously added images from the media folders `logo.png` `open-positions.png` and `text-link.png`

**Comment by nsLittle** [comment]
.png files deleted.  TY.

**Comment by ishg-153** [comment]
@nsLittle The gifs you are using have a watermark, is it possible to remove or blur them out? We prefer not to have watermarks on media.

**Comment by nsLittle** [comment]
My apologies.  I wanted to only use free services, so I tried using Loom
(it doesn't allow for free download, nor conversion to gif), and settled on
using Vimeo (it allows for screen video plus conversion to gif, albeit with
the watermark).  I've searched around elsewhere, but seem to only come upon
paid services.  Do you know of any service, or set of services, that would
allow me to videotape a browser window and turn the video into a gfi?

**Comment by KTom101** [comment]
@nsLittle You can use [Convertio](https://convertio.co/) to upload your video and convert it into a gif for free.

**Comment by ishg-153** [comment]
@nsLittle Were you able to get a watermark-free gif using @KTom101 's suggestion?

**Comment by ishg-153** [comment]
@nsLittle Due to lack of response on your end I will have to close this PR.

**Pull request closed without merging**
