### PR TITLE
[Term Entry] Lua Tables clone()

### LINKED ISSUE #3114: [Term Entry] Lua Tables clone()
### Reason/inspiration (optional)

Please add the `clone()` function as a new term entry as part of the tables functions terms. Provide the entry in a markdown file and place under the file path `content/lua/concepts/tables/terms/clone/clone.md`

The entry should have the following:

� An introductory paragraph about what the function is and does. "Returns a shallow copy of the provided table. A shallow copy refers to an independent clone separate from its original table."
� A syntax section with a pseudo code block with an explanation of it.
� An example showing the function in use.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by ShatilKhan**
### Description

Added term entry for Lua Table function clone() .
File Location: content\lua\concepts\tables\terms\clone\clone.md. Closes #3114 

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have made corresponding changes to the documentation if needed.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.
- [X] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [X] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by SSwiniarski** [comment]
@caupolicandiaz, @yangc95, @KTom101: Looking around and trying on-line interpreters, it doesn't seem that `clone()` or `shallow_copy()` are standard Lua functions. Can any of you find something that says different?

**Comment by KTom101** [comment]
@SSwiniarski No, it is not standard. I'm wondering if this issue was created by mistake.

**Comment by ShatilKhan** [comment]
Hey,  thanks for the clarification. I was also confused as I couldn’t find any standard clone() functions.

**Comment by ShatilKhan** [comment]
Hey Guys, I guess we can close this PR and the issue if not needed, or if there's any update, let me know.

**Comment by SSwiniarski** [comment]
@KTom101, @ShatilKhan I'm going to close this PR and the issue.

**Comment by SSwiniarski** [comment]
Closing as this is not a standard Lua function.

**Pull request closed without merging**
