### PR TITLE
for the issue: [Edit] Subject: Erroneous link in Codecademy Docs file/document -> Docs/JavaScript/Objects #4427

### LINKED ISSUE #4427: [Edit] Subject: Erroneous link in Codecademy Docs file/document -> Docs/JavaScript/Objects
### Type of Edit (select all that apply)

Fix grammar, spelling, formatting

### Description (optional)

There is a broken link in https://www.codecademy.com/resources/docs/javascript/objects

In the section Object classes the sentence:

"An additional step can be made to optimize this procedure through the use of a [constructor](https://www.codecademy.com/resources/docs/javascript/constructor)."

The link refers to the constructor doc but is missing an "s" in the link.

Current link: https://www.codecademy.com/resources/docs/javascript/constructor
Correct link: https://www.codecademy.com/resources/docs/javascript/constructors

I hope I categorized this correct.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by zkhOlga**
### Description

The link to constructors (https://www.codecademy.com/resources/docs/javascript/constructors) in objects.md (in https://www.codecademy.com/resources/docs/javascript/objects)

### Issue Solved

Closes #4427

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist
- [ ] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by S1791 — COMMENTED** [review]
The change is not quite correct. There are two possible "solutions":

1. An additional step can be made to optimize this procedure through the use of [constructors](https://www.codecademy.com/resources/docs/javascript/constructors).

OR

3. An additional step can be made to optimize this procedure through the use of a [constructor](https://www.codecademy.com/resources/docs/javascript/constructors).

**Review by ishg-153 — APPROVED** [review]
@zkhOlga made small changes from my end looks good to for a second review.

**Review by S1791 — APPROVED** [review]
The link issue looks good to me. 👍🏼

**Review by avdhoottt — APPROVED** [review]
LGTM!

**Pull request merged**
