### PR TITLE
Added media files to hsl.md

### LINKED ISSUE #3648: [Edit] CSS [Edit] CSS Colors: hsl()
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to a term within CSS Colors. The term entry lives in docs/content/css/concepts/colors/terms/hsl/hsl.md

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add supplemental media (preferred .png or .gif, <1MB).
2) Media (images, gifs) should accurately represent the existing code blocks in the example sections and fit in-line. ex: [See last image here](https://www.codecademy.com/resources/docs/html/attributes/title)

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by codewithjazzy**
### Description

Edited CSS Colors: hsl.md, added example images 
Closes #3648 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by caupolicandiaz — CHANGES_REQUESTED** [review]
@codewithjazzy Overall, this looks good. But the images appear to be low resolution. Preferably all images have a dpi of 300 or higher. Please replace the images with higher resolution files.

**Comment by codewithjazzy** [comment]
@caupolicandiaz I updated the images.

**Review by caupolicandiaz — APPROVED** [review]
@codewithjazzy This is ready for a second review.

**Comment by codewithjazzy** [comment]
@caupolicandiaz Am I supposed to tag another maintainer, use the "re-request review" option at the top left, or simply wait?
Thanks!

**Comment by caupolicandiaz** [comment]
> @caupolicandiaz Am I supposed to tag another maintainer, use the "re-request review" option at the top left, or simply wait?
> Thanks!

We've got a lot of PRs to cover, someone will review it. Please be patient

**Comment by codewithjazzy** [comment]
@caupolicandiaz Yes, of course, I can do that! I wasn't able to find any documentation specifically for my question, so I was just making sure that I was on the right track. Thank you for letting me know and thank you for all your hard work 😊

**Review by SSwiniarski — APPROVED** [review]
@codewithjazzy Looks good.

**Pull request merged**
