### PR TITLE
Csharp commentss

### PR DESCRIPTION
**Pull request by RashmitTopG**
### Issue Solved

Fixed Documentation and added definitions and codeblocks for comments.

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [✓] All writings are my own.
- [✓] My entry follows the Codecademy Docs style guide.
- [✓] My changes generate no new warnings.
- [✓] I have performed a self-review of my own writing and code.
- [✓] I have checked my entry and corrected any misspellings.
- [✓] I have made corresponding changes to the documentation if needed.
- [✓] I have confirmed my changes are not being pushed from my forked `main` branch.
- [✓] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [✓] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by RashmitTopG** [comment]
@SaviDahegaonkar can you please review this PR !?

**Comment by SaviDahegaonkar** [comment]
> @SaviDahegaonkar can you please review this PR !?

Sure.

**Comment by SaviDahegaonkar** [comment]
Hey @RashmitTopG , Can you please mention the issue which this PR closes. Also I find some conflicts in this file. Can you please check it and raise a new PR for this which mentions the issue to which this PR relates to and also does not consist of any conflicting files, so for now I am closing this PR.

Thanks,
Savi

**Comment by Radhika-okhade** [comment]
There are 2 files on the same branch, so closing this PR. 
Author is inactive as well.

**Pull request closed without merging**
