### PR TITLE
[Term Entry] Dart Type Conversion: .toStringAsPrecision() 

### PR DESCRIPTION
**Pull request by tomasbaublys**
### Description

- Added the .toStringAsPrecision() term for Dart.
- Closes issue #4567

### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by mamtawardhani** [comment]
@tomasbaublys could you please sign the CLA?

**Comment by tomasbaublys** [comment]
> @tomasbaublys could you please sign the CLA?

@mamtawardhani it looks like I pulled without my username and email and now can't sign CLA. Could you please advise?

**Comment by mamtawardhani** [comment]
Hey @tomasbaublys! 
If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by tomasbaublys** [comment]
> Hey @tomasbaublys! If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

@mamtawardhani The problem is that I didn’t use any email during this commit.

**Comment by mamtawardhani** [comment]
@tomasbaublys Then I would suggest you close this PR and create another one with the same file. Make sure you sign-in with your GitHub this time before you create the PR 😄

**Pull request closed without merging**
