### PR TITLE
[Edit] JavaScript Strings: toUpperCase()

### LINKED ISSUE #4154: [Edit] Strings: Adding codebyte for the entry `.toUpperCase()`
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

[PLEASE DO NOT WORK ON THIS ISSUE UNTIL YOU HAVE BEEN ASSIGNED] We would like an edit to the `toUpperCase.md` entry. The term entry lives in docs/content/javascript/concepts/strings/terms/toUpperCase/toUpperCase.md.

Please refer to the [term entry templates](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a codebyte which shows how we can use `.toUpperCase()`.
2) You can be creative with the codebyte snippet but make sure you don't deviate a lot from the entry.

### Codebyte Example

image

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by ivaaane**
### Description

- Added a new example using codebyte.

### Issue Solved

Closes #4154.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by mamtawardhani — CHANGES_REQUESTED** [review]
Hey @ivaaane thank you for the contribution. However, the issue [#4154](https://github.com/Codecademy/docs/issues/4154) requires a ##Codebyte Example block.
You are supposed add this block below the Example 2 block, and the code should not be similar to any of the examples already used in the file. 
So, please make sure that you are not supposed to change the other examples, revert those changes, just add a ##Codebyte Example block below the existing examples.
Feel free to discuss if you have any doubts. Thank you! 😃

**Comment by ivaaane** [comment]
@mamtawardhani Oop, sorry for the confusion. And thanks! I will work on it now

**Comment by ivaaane** [comment]
> @mamtawardhani Oop, sorry for the confusion. And thanks! I will work on it now

Done

**Review by mamtawardhani — APPROVED** [review]
@ivaaane Thanks for making the required changes! Entry looks good for a second review!

**Comment by ivaaane** [comment]
I hate asking, but... Why is there one failing check, and how to fix it?

**Comment by Sriparno08** [comment]
Hey @ivaaane, we'll fix it from our side. So, don't worry about that.

**Review by Sriparno08 — APPROVED** [review]
Looks good, @ivaaane! 👍

**Pull request merged**
