### PR TITLE
Update classes.md

### PR DESCRIPTION
**Pull request by vlrnsnk**
### Description

Corrected a statement about abstract classes and methods. The previous text inaccurately suggested that any class containing abstraction (methods, fields, etc.) must be abstract. The updated text clarifies that a class must be declared abstract only if it contains abstract methods.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by vlrnsnk** [comment]
I want to work on this issue

**Comment by mamtawardhani** [comment]
Hey @vlrnsnk I've raised an issue for this PR, you can find it here #5184. Please comment on it so that it can be assigned to you and we can close the PR. Thank you! 😃

**Review by mamtawardhani — APPROVED** [review]
Thank you for pointing this out @vlrnsnk 

The entry is ready to be merged! 🚀

**Comment by vlrnsnk** [comment]
Dear Mamta,

I'm listed as an anonymous contributor and the link to the forum thread to
fix it is 404.
Can you please help me solve this?

Kind regards,

**Pull request merged**
