### PR TITLE
added pngs and a new example to further explain the matter

### PR DESCRIPTION
**Pull request by RAFIMIKI**
### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Changes

- Changed the 'top' typo from the css blocks to the correct 'right'
- added example 3 to further explain how to use it
- added PNGS to visualize everything

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by ishg-153 — CHANGES_REQUESTED** [review]
Hey @RAFIMIKI! You need to add the images to the media folder in docs and then link them in this format: `https://raw.githubusercontent.com/Codecademy/docs/main/media/` followed by the image name.

Also please sign the CLA.

**Comment by RAFIMIKI** [comment]
I signed the CLA and put the pngs in the media folder

will be finished very soon

**Comment by ishg-153** [comment]
@RAFIMIKI Are you still working on the requested change?

**Review by Helfese — APPROVED** [review]

**Comment by ishg-153** [comment]
@RAFIMIKI It's been 2 weeks. If you don't respond with an update or push the changes within the next week. This PR will be closed.

**Comment by RAFIMIKI** [comment]
> @RAFIMIKI It's been 2 weeks. If you don't respond with an update or push the changes within the next week. This PR will be closed.

Sorry for not responding I’ve been busy, I did a push request and it was accepted, thought that it was done, what’s left to do?

**Comment by ishg-153** [comment]
> Sorry for not responding I’ve been busy, I did a push request and it was accepted, thought that it was done, what’s left to do?

The images aren't reflected in the media folder, please take a look at my previous comment one more time to get a better understanding

**Comment by ishg-153** [comment]
@RAFIMIKI It's been two weeks are you still working on this PR.

**Comment by ishg-153** [comment]
@RAFIMIKI Due to your lack of response this PR is being closed and the corresponding issue unassigned.

**Pull request closed without merging**
