### PR TITLE
Documenting scatter.md

### LINKED ISSUE #4558: [Term Entry] Python Plotly .scatter()
### Reason/inspiration (optional)

We would like a new term entry in the `Data Visualization` concept for Plotly: `.scatter()`. The entry should go in a new file under `docs/content/plotly/concepts/express/terms/scatter/scatter.md`

The entry should describe the term and how it is used. Also include:

- An introductory paragraph that describes the concept
- A 'Syntax' section that includes the syntax for the concept (if applicable)
- An 'Example' section that shows the concept in use

Please refer to the [entry templates](https://github.com/Codecademy/docs/blob/main/documentation/), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by KarinaNi**
### Description

Added documentation of scatter md

### Issue Solved
Closes #4558  

### Type of Change

- Adding a new entry
- Updating the documentation

### Checklist

- [x ] All writings are my own.
- [ x] My entry follows the Codecademy Docs style guide.
- [ x] My changes generate no new warnings.
- [x ] I have performed a self-review of my own writing and code.
- [x ] I have checked my entry and corrected any misspellings.
- [x ] I have made corresponding changes to the documentation if needed.
- [ x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x ] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by KarinaNi** [comment]
image
Should I update the branch or no?

**Comment by mamtawardhani** [comment]
No worries @KarinaNi i'll do that. Thanks for the entry, will review it asap 😃

**Review by mamtawardhani — CHANGES_REQUESTED** [review]
@KarinaNi the entry is well written. I'm requesting just one change, the output image for the second example seems incorrect, could you please run that code and attach the correct image for the output of the second example? Thank you! 😃

**Comment by KarinaNi** [comment]
what do you think @mamtawardhani

**Review by mamtawardhani — APPROVED** [review]
Looks perfecto spectronium @KarinaNi! Many thanks for making the required changes 😃 

Looks good for a second round of review 🚀

**Pull request merged**
