### PR TITLE
add .encodeToHexString() new term entry

### PR DESCRIPTION
**Pull request by rusliabdulgani**
### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by rusliabdulgani** [comment]
i have already sign the CLA, but the status still not signed

**Comment by ishg-153** [comment]
> i have already sign the CLA, but the status still not signed

@rusliabdulgani Can you retry signing the CLA [here](https://cla-assistant.io/Codecademy/docs?pullRequest=3937)?

**Comment by rusliabdulgani** [comment]
already sign with your link, but still pending.. 
Screenshot 2023-11-18 at 07 38 28

**Comment by ishg-153** [comment]
@fullertonhealthapp You seem to have added the commit but [this](https://github.com/Codecademy/docs/issues/3873) issue was assigned to @rusliabdulgani.

**Comment by rusliabdulgani** [comment]
> [CLA assistant check](https://cla-assistant.io/Codecademy/docs?pullRequest=3937) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Codecademy/docs?pullRequest=3937) before we can accept your contribution.**1** out of **2** committers have signed the CLA.✅ rusliabdulgani❌ fullertonhealthappYou have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Codecademy/docs?pullRequest=3937) it.

Could you please just remove commit from fullertonhealthapp username ? it my mistake to commit with this account, but i cannot take down also forgot the email for this account

**Comment by rusliabdulgani** [comment]
> @fullertonhealthapp You seem to have added the commit but [this](https://github.com/Codecademy/docs/issues/3873) issue was assigned to @rusliabdulgani.

**Comment by rusliabdulgani** [comment]
i make a mistake, closed the pull request, please open again

**Pull request closed without merging**
