### PR TITLE
Added arrays.md file in the kotlin array folder

### PR DESCRIPTION
**Pull request by dakshdeepHERE**
### Type of Change

- Adding a new entry
- Updating the documentation
- Added Arrays.md file for the Kotlin folder

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by dakshdeepHERE** [comment]
Please check the commit and if theres any changes required I will do it.

**Comment by SSwiniarski** [comment]
@Dusch4593, @yangc95 any ideas how to fix @dakshdeepHERE's issue with the CLA?

**Comment by dakshdeepHERE** [comment]
@SSwiniarski  Upon submitting the pull request for data type issues, I discovered that there was no issue with the Contributor License Agreement. It is my assumption that this issue arose because I signed the CLA before creating the pull request. If the current pull request for arrays is rejected and I resubmit it, I believe the CLA issue will be resolved.I will also link the screenshots of workflow checks for the data types pr. 
Screenshot 2022-12-29 at 2 37 33 PM

**Comment by dakshdeepHERE** [comment]
@SSwiniarski  as you can see above in the screen cla issue was not there for data type pr.

**Comment by SSwiniarski** [comment]
@dakshdeepHERE To fix the CLA issue, lets close this PR and reissue a new one.

**Pull request closed without merging**
