### PR TITLE
Add section on iterators to Python classes

### PR DESCRIPTION
**Pull request by mitchellfaulk**
### Type of Change

- Updating the documentation

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by Dusch4593** [comment]
Hi @mitchellfaulk! Brandon from the Free Team at Codecademy.

I'm not sure your proposed changes fit best in the `classes.md` file. However, we do already have a published [Python: Iterators](https://www.codecademy.com/resources/docs/python/iterators) (`python/concepts/iterators/iterators.md`) entry that you could incorporate your changes into, within this PR. 😄

There are some changes that we could still make in the `classes.md`, too! Let me know how you'd like to move forward.

**Comment by mitchellfaulk** [comment]
Hi Brandon,

Thanks so much for the feedback! 

I’d be happy to incorporate some changes into the iterators entry. I’m sorry I didn’t notice that entry earlier! 

I would also be happy to make some changes to the classes.md file as necessary! I could prepare a separate PR for this too, if you have any particular changes in mind. :)

Thanks!
Mitchell

**Comment by Dusch4593** [comment]
Hey @mitchellfaulk thanks for the quick response! 🚀 Let's just keep all the changes in this one PR. 😄

**Comment by mitchellfaulk** [comment]
Okay, great! I’ll try to rework the PR by the end of the day, incorporating my changes into the Iterators entry. 

Also, you said that there are some changes we could still make in the classes.md, too. I would be happy to make those changes if you have an outline of them. I could do this in a separate PR later this week or something. 

Thanks,
Mitchell

**Comment by mitchellfaulk** [comment]
Got it, thanks!!

**Comment by Dusch4593** [comment]
Hey @mitchellfaulk did you have any questions or need any help with implementing the feedback? As a reminder, today is the last day to merge your PRs and have them count toward Hacktoberfest. 👀

**Comment by Dusch4593** [comment]
@mitchellfaulk Closing this PR for now due to weeks of inactivity. Please feel free to comment on this thread if you're still interested in working on this contribution and we will re-open. 😄

**Pull request closed without merging**
