### PR TITLE
[Concept Entry] C++ Unordered set unordered_set #5315

### PR DESCRIPTION
**Pull request by Jack-Race**
### Description

Created a first draft for a concept entry of C++ Unordered sets. Used the beginner guidelines to create the entry, included introduction, syntax, example and a codebyte example. Found this issue while completing the git & github codecademy course. Let me know how I can improve it. I used the 'sets' concepts page to help me and keep it uniform between ordered and unordered sets, I did change all the descriptions but let me know if they're too similar. All the best!

### Type of Change

- Adding a new entry

### Checklist

- [X] All writings are my own.
- [X] My entry follows the Codecademy Docs style guide.
- [X] My changes generate no new warnings.
- [X] I have performed a self-review of my own writing and code.
- [X] I have checked my entry and corrected any misspellings.
- [X] I have confirmed my changes are not being pushed from my forked `main` branch.

### CODE REVIEW

**Comment by mamtawardhani** [comment]
Hey @Jack-Race please comment claim on [this](https://github.com/Codecademy/docs/issues/5456) issue, so that it can be assigned to you.

**Review by mamtawardhani — APPROVED** [review]
Thank you for contributing to Codecademy Docs @Jack-Race 😄 

The entry looks good for a second round of review! 🚀

**Review by Sriparno08 — APPROVED** [review]
Looks good, @Jack-Race!

**Comment by Jack-Race** [comment]
Hiya, is there a way to be credited for this, the attached link is not working for me, thanks!

**Comment by Sriparno08** [comment]
Hey @Jack-Race, here are the steps to be credited:

1. Go to your Codecademy dashboard.
2. Click on your profile image in the top-right and then choose "Profile".
3. Then click "Edit Profile".
4. In the "GitHub Username" field, add your username (without the @).
5. Click "Save Changes"

**Pull request merged**
