### PR TITLE
Add Flutter topic

### PR DESCRIPTION
**Pull request by max-torch**
### Description

Adds a new topic for Flutter. We now have [Flutter content in Codecademy](https://www.codecademy.com/learn/intro-to-flutter).

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — CHANGES_REQUESTED** [review]
@max-torch I did a review and don't have any comments on the body of the entry. However, I would like you to change this from a topic, to a General concept entry. (move to `content/general/concepts/flutter/flutter.md` and update the metadata to reflect a concept entry.)

**Comment by max-torch** [comment]
> @max-torch I did a review and don't have any comments on the body of the entry. However, I would like you to change this from a topic, to a General concept entry. (move to `content/general/concepts/flutter/flutter.md` and update the metadata to reflect a concept entry.)

File location has been moved and metadata updated. Please review.

**Review by SSwiniarski — APPROVED** [review]
@max-torch This looks good for a second review.

**Review by dakshdeepHERE — APPROVED** [review]
Looks good to merge.

**Pull request merged**
