### PR TITLE
[Term Entry] Swift Dictionaries .updateValue()

### PR DESCRIPTION
**Pull request by WiggleXO**
### Description

- Created the .updateValue () term entry for Swift Dictionaries
- Closes Issue #2025 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by WiggleXO** [comment]
@yangc95 No problem. 👍  Let me know if there's anything I need to do

**Review by SSwiniarski — APPROVED** [review]
@WiggleXO I did a second review and it looks good to merge.

**Comment by SSwiniarski** [comment]
@WiggleXO Congrats on the new entry! Live link here: https://www.codecademy.com/resources/docs/swift/dictionaries/updateValue

image

**Comment by WiggleXO** [comment]
Awesome, thank you for this opportunity :)

**Pull request merged**
