### PR TITLE
To bold or not to bold

### PR DESCRIPTION
**Pull request by yangc95**
Reflecting bolding in content standards

### CODE REVIEW

**Review by caupolicandiaz — APPROVED** [review]
@yangc95 I added a matching edit to the style guide as well

**Review by SSwiniarski — APPROVED** [review]
@yangc95 Looks good to me.

**Comment by SSwiniarski** [comment]
@yangc95 I also used the opportunity to fix a typo in the style guide.

**Review by HishamT — COMMENTED** [review]
LGTM!

**Review by aherman91 — COMMENTED** [review]
Looks good, thanks Christine!

**Pull request merged**
