### PR TITLE
[Term Entry]  PyTorch Tensors: .randn()

### PR DESCRIPTION
**Pull request by ompharate**
### Description

-Added the PyTorch Tensors .randn()
-Closes Issue #4939 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by cigar-galaxy82 — CHANGES_REQUESTED** [review]

**Comment by cigar-galaxy82** [comment]
Hi @ompharate thank you for Contributing to Codecademy docs, the entry is well written I have suggested a few changes please modify

**Comment by cigar-galaxy82** [comment]
Hi @ompharate everything looks good just make one change I suggested to give a link gap after line 14

**Comment by ompharate** [comment]
@cigar-galaxy82  updated

**Review by cigar-galaxy82 — APPROVED** [review]

**Comment by ompharate** [comment]
@cigar-galaxy82  why i can not see [https://www.codecademy.com/resources/docs/pytorch/tensors/randn](https://www.codecademy.com/resources/docs/pytorch/tensors/randn)

**Pull request merged**
