### PR TITLE
[Edit] JavaScript: AJAX (typo)

### PR DESCRIPTION
**Pull request by KTom101**
### Description

There's a typo in the first sentence, "programmng" should be "programming".

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by SSwiniarski — APPROVED** [review]
Looks good.

**Comment by OmarHussari** [comment]
Hi there! I would like to contribute to this entry. Doing it for Codecademy Web Dev Project. Already spotted some typos :D

**Comment by KTom101** [comment]
@OmarHussari Thank you for your interest 🙏 Feel free to open up a new pull request with your edits. If making edits to multiple entries, please limit the pull request to 2-3 files. You can create make new pull requests for additional files.

**Comment by OmarHussari** [comment]
@KTom101 Thanks a lot. I just submitted a pull request.
As this is my first time, kindly let me know if there are any mistakes I have made in the process of contributing. Or any conventions I have not followed.
Regards :D

**Pull request merged**
