### PR TITLE
Add .remove() Method.

### LINKED ISSUE #4645: [Term Entry] Python sets .remove()
### Reason/inspiration (optional)

We would like a new term entry on the '.disjoint()' method for Sets in Python. The entry should go in a new file under `docs/content/python/concepts/sets/terms/remove/remove.md`
 
 The entry should include the following:
 
 - A description of the function
 - A ## Syntax section that includes the syntax of the function and its details
 - An ## Example section that includes a ```python ``` codeblock and ```shell ``` that shows the example output.
 - A ## Codebyte Example that includes a ```codebyte/python ``` runnable codeblock
 
 Please refer to the [concept entry template](https://github.com/Codecademy/docs/blob/main/documentation/concept-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

### Entry Type (select all that apply)

New Term for Existing Concept Entry

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [X] Labels added
- [ ] Issue is assigned

### PR DESCRIPTION
**Pull request by ULTRAPAIN**
Added remove markdown File

### Description
I have created the article about the .remove() method for set objects in Python.
It's my first contribution to GitHub, which I'm currently learning on the Codecademy platform.

### Issue Solved
Closes #4645 

### Type of Change

- Adding a new entry

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by mamtawardhani — CHANGES_REQUESTED** [review]
Hey @ULTRAPAIN! Thank you for contributing to the Codecademy Docs!

I've suggested some changes for this entry, could you please review and modify those at your earliest convenience? Also, this entry was very similar to our `.discard()` entry, so I have requested some changes in the phrasings as well.

Thank you!

**Comment by ULTRAPAIN** [comment]
Hi @mamtawardhani I have done the changes as per the suggestions :)

**Review by mamtawardhani — APPROVED** [review]
Thank you @ULTRAPAIN for making the changes.

Looks good to me for the second review!

**Comment by ULTRAPAIN** [comment]
when is the pull request going to merge , I want to contribute to another docs

**Comment by mamtawardhani** [comment]
Hey @ULTRAPAIN, your entry is in the queue for the second review, once that is done, it will get merged. It should be done by the first half of the next week. 💯

**Review by Sriparno08 — APPROVED** [review]
Looks good, @ULTRAPAIN! 👍

**Pull request merged**
