### PR TITLE
General reorganization test

### PR DESCRIPTION
**Pull request by yangc95**
### Description

Previous workflow failed. Continued test using git commit --author='Name <Email>' -m “Move file”

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by KTom101 — APPROVED** [review]
👍

**Comment by yangc95** [comment]
This workflow is good.

Upon moving a file with `git mv oldfilepath newfilepath`, use `git commit --author='Name <email>' -m “Move file”` to include authors.

cc: @caupolicandiaz @Dusch4593 @HishamT @KTom101 @lucwhite @SSwiniarski

**Comment by Dusch4593** [comment]
Thank you so much @yangc95! Just to clarify, do we run these two commands in between each file being moved?

In my head, I'm envisioning...

- Moved `file_1`
- `git mv oldfilepath/file_1 newfilepath/file_1` + `git commit --author='Author 1 <email>' -m "Move file_1"`
- Moved another one, `file_2`
- `git mv oldfilepath/file_2 newfilepath/file_2` + `git commit --author='Author 2 <email>' -m "Move file_2"`

**Comment by yangc95** [comment]
> This workflow is good.
> 
> Upon moving a file with `git mv oldfilepath newfilepath`, use `git commit --author='Name <email>' -m “Move file”` to include authors.
> 
> cc: @caupolicandiaz @Dusch4593 @HishamT @KTom101 @lucwhite @SSwiniarski

EDIT: The workflow may have worked only because the file was moved back to its original location and there was history of the author. But upon moving to the new location again with the same command, it failed again. Going to continue testing.

**Comment by yangc95** [comment]
> Thank you so much @yangc95! Just to clarify, do we run these two commands in between each file being moved?
> 
> In my head, I'm envisioning...
> 
> * Moved `file_1`
> * `git mv oldfilepath/file_1 newfilepath/file_1` + `git commit --author='Author 1 <email>' -m "Move file_1"`
> * Moved another one, `file_2`
> * `git mv oldfilepath/file_2 newfilepath/file_2` + `git commit --author='Author 2 <email>' -m "Move file_2"`

This would have been the workflow had it worked :/ it has the same effect as manually writing in a co-author upon squash merge.

**Pull request merged**
