### PR TITLE
Update ABC explanation in inheritance.md

### PR DESCRIPTION
**Pull request by bcbecker**
### Description

Language: Python
File: python/concepts/inheritance/inheritance.md
Edited File: inheritance .md

Under the "Abstract Base Class" heading in inheritance.md, I noticed references to an 'Employee' class that does not exist. I corrected these references to the intended class, 'AbstractClass', and reworked the explanation to make it a bit more clear.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.

### CODE REVIEW

**Comment by Dusch4593** [comment]
@bcbecker The changes on the live site look good on my end! How about yours?

https://www.codecademy.com/resources/docs/python/inheritance

**Comment by bcbecker** [comment]
> @bcbecker The changes on the live site look good on my end! How about yours?
> 
> https://www.codecademy.com/resources/docs/python/inheritance

Everything looks good! Thanks Brandon

**Comment by Dusch4593** [comment]
Btw, I noticed that I don't see you under the list of contributors for the entry (just the Anonymous icon): 

Screen Shot 2022-02-17 at 2 38 06 PM

If you wanted to receive credit, try logging out of your Codecademy profile and relogging in with your GitHub account. As long as the email address is the same for both accounts, you should be good! 😄

**Comment by bcbecker** [comment]
> Btw, I noticed that I don't see you under the list of contributors for the entry (just the Anonymous icon):
> 
> Screen Shot 2022-02-17 at 2 38 06 PM
> 
> If you wanted to receive credit, try logging out of your Codecademy profile and relogging in with your GitHub account. As long as the email address is the same for both accounts, you should be good! 😄

Thanks for letting me know. I don't do it for the fame 😆

**Comment by Dusch4593** [comment]
@bcbecker 😆 fair enough.

**Pull request merged**
