### PR TITLE
Update software-testing.md

### PR DESCRIPTION
**Pull request by wgallagher89**
### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Comment by cigar-galaxy82** [comment]
Hey @wgallagher89 

Thank you for contributing to Codecademy Docs!

I've suggested a few changes modify them at your convenience

Thank you!

**Comment by wgallagher89** [comment]
Hi @cigar-galaxy82

I think your suggestion was more appropriate than mine. Thank you for your help!

**Comment by cigar-galaxy82** [comment]
@wgallagher89 welcome

**Review by mohitO12-dev — APPROVED** [review]
Approved. All checks are passed.

**Pull request merged**
