### PR TITLE
Edit - CSS - sepia.md

### LINKED ISSUE #4869: [Edit] CSS [Edit] CSS: Filter Functions `sepia`
### Type of Edit (select all that apply)

Add new content (definitions, codeblocks, etc.)

### Description (optional)

We would like to edit the `sepia` term entry under Filter Functions concept in CSS. The entry lives in `content/css/concepts/filter-functions/terms/sepia/sepia.md`.

Please refer to the [term entry template](https://github.com/Codecademy/docs/blob/main/documentation/term-entry-template.md), [content standards](https://github.com/Codecademy/docs/blob/main/documentation/content-standards.md), and [markdown style guide](https://curriculum-documentation.codecademy.com/content-guidelines/markdown-style-guide/) when working on the PR for this issue.

Please:
1) Add a output image comparing the original image in the example already given in the entry to its sepia filter version.

### Code of Conduct

- [X] By submitting this issue, I agree to follow Codecademy Doc's [Code of Conduct](https://github.com/Codecademy/docs/blob/main/.github/CODE_OF_CONDUCT.md).

### For Maintainers

- [x] Labels added
- [x] Issue is assigned

### PR DESCRIPTION
**Pull request by danitellini**
### Description

Topic: Edit - CSS - Filter Funtions - sepia.md
File Edited: `docs/content/css/concepts/filter-functions/terms/sepia/sepia.md`
Files Added: `docs/media/sepia-example-original.jpg` and `docs/media/sepia-example-filtered.jpg`
Closes an open issue

### Issue Solved

Closes #4869 

### Type of Change

- ~Adding a new entry~
- Editing an existing entry (fixing a typo, bug, issues, etc)
- ~Updating the documentation~

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] I have linked any issues that are relevant to this PR in the `Issues Solved` section.

### CODE REVIEW

**Review by SaviDahegaonkar — APPROVED** [review]
Hey @danitellini,
Thank you for contributing to Codecademy Docs! :) This entry looks good for second round of review. 🚀

**Comment by danitellini** [comment]
I apologize, I don't know why this was closed 😓

**Comment by danitellini** [comment]
@Sriparno08 @mamtawardhani @PragatiVerma18 Besides the fact that I somehow deleted this PR before, is there an issue with this? It's been back up for a week 😅

**Review by PragatiVerma18 — APPROVED** [review]
Hey @danitellini, this looks good to go! 🚀

**Pull request closed without merging**
