### PR TITLE
My contribution

### PR DESCRIPTION
**Pull request by GuinnessStout113**
### Type of Change

- Adding a new entry
- Editing an existing entry (fixing a typo, bug, issues, etc)
- Updating the documentation

### Checklist

- [ ] All writings are my own.
- [ ] My entry follows the Codecademy Docs style guide.
- [ ] My changes generate no new warnings.
- [ ] I have performed a self-review of my own writing and code.
- [ ] I have checked my entry and corrected any misspellings.
- [ ] I have made corresponding changes to the documentation if needed.
- [ ] I have confirmed my changes are not being pushed from my forked `main` branch.
- [ ] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [ ] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by SSwiniarski** [comment]
@caupolicandiaz, @KTom101, @yangc95: This isn't appropriate for it's own topic, but I'm wondering where it should go. I'm leaning toward General, but I suppose it could be under C++ as well.

**Comment by yangc95** [comment]
@SSwiniarski C++ seems like a good place for this concept to live

@GuinnessStout113 can you move this file to its own concept folder there?

**Comment by SSwiniarski** [comment]
@GuinnessStout113 so before we review this, can you do the following:

Move the file here: `docs/content/cpp/concepts/carbon/carbon.md`
Update the metadata to be in line with a concept entry, as described [here](https://github.com/Codecademy/docs/blob/main/documentation/style-guide.md#metadata).

Tag me when this is done and I'll go ahead with a review.

**Comment by SSwiniarski** [comment]
@GuinnessStout113 are you having problems with my instructions?

**Comment by SSwiniarski** [comment]
@yangc95, @KTom101, @caupolicandiaz. It's been four weeks with no response. This seems abandoned. Should we just close it?

**Comment by caupolicandiaz** [comment]
> @yangc95, @KTom101, @caupolicandiaz. It's been four weeks with no response. This seems abandoned. Should we just close it?

I say we just close it

**Comment by SSwiniarski** [comment]
Closing due to lack of response.

**Pull request closed without merging**
