### PR TITLE
HTML Add Media: style #3556

### PR DESCRIPTION
**Pull request by kitttrick**
### Description

- Added a media example of the style attribute
- Added wording to accompany example image
- Closes issue #3556 

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Review by kitttrick — COMMENTED** [review]
Sorry this took so long, I was having a lot of trouble working out how to delete the old files from the PR - I ended up just creating a new branch/PR, hope that's okay.

One comment from the previous PR was that the image wasn't legible (too small). This image has a larger font size, but this does mean that the example does not represent the code exactly... not sure how else I could approach this though. I changed the 'unstyled' text to font size 18, and the styled text to size 20 to show that there is a difference between the two. If you aren't happy with this, could you please advise how I can adhere to the correct style whilst also making it legible?! Thank you :)

**Review by ishg-153 — APPROVED** [review]
@kitttrick Great! This is ready for a second review.

**Comment by ishg-153** [comment]
> Sorry this took so long, I was having a lot of trouble working out how to delete the old files from the PR - I ended up just creating a new branch/PR, hope that's okay.
> 
> One comment from the previous PR was that the image wasn't legible (too small). This image has a larger font size, but this does mean that the example does not represent the code exactly... not sure how else I could approach this though. I changed the 'unstyled' text to font size 18, and the styled text to size 20 to show that there is a difference between the two. If you aren't happy with this, could you please advise how I can adhere to the correct style whilst also making it legible?! Thank you :)

That's totally fine! I'll just make the change in the example code to reflect the same font size.

**Review by SSwiniarski — APPROVED** [review]
@kitttrick Looks good.

**Pull request merged**
