### PR TITLE
Update video.md

### PR DESCRIPTION
**Pull request by ethan-master-coding**
### Description

Fixed the size of the output of the video tag.

### Type of Change

- Editing an existing entry (fixing a typo, bug, issues, etc)

### Checklist

- [x] All writings are my own.
- [x] My entry follows the Codecademy Docs style guide.
- [x] My changes generate no new warnings.
- [x] I have performed a self-review of my own writing and code.
- [x] I have checked my entry and corrected any misspellings.
- [x] I have made corresponding changes to the documentation if needed.
- [x] I have confirmed my changes are not being pushed from my forked `main` branch.
- [x] I have confirmed that I'm pushing from a new branch named after the changes I'm making.
- [x] Under "Development" on the right, I have linked any issues that are relevant to this PR (write "Closes #<issue number> in the "Description" above).

### CODE REVIEW

**Comment by ethan-master-coding** [comment]
@Dusch4593 The video is huge so we need to limit the size. And nothing is showing up for the audio tag.

**Comment by Dusch4593** [comment]
I don't think the `width/height` attribute will fix the problem because they only accept absolute CSS values (like pixels `px`). Therefore, the video will still break out of small screens.

I've already passed this info along to my colleagues in engineering since this falls squarely in their court now; we've done all we could from our end. Will let you know what they say, but am closing this PR for now.

**Comment by ethan-master-coding** [comment]
@Dusch4593 Passed along the stuff with the video tag and the audio tag or just the video tag stuff?

**Comment by Dusch4593** [comment]
Both

**Pull request closed without merging**
